openMF/web-app

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/user-story-template.md
Add issue template for bug reports.
Fixes: #15
> chore: add bug_report.md

- .github/CODE_OF_CONDUCT.md
Add code of conduct to be followed by the contributors of the project.
Fixes: #16
> chore: add CODE_OF_CONDUCT.md

- .github/COMMIT_MESSAGE.md
Add guidelines to be followed for a meaningful commit message.
Fixes: #18
> chore: add COMMIT_MESSAGE.md

- .github/CODE_OF_CONDUCT.md
Update code of conduct with email address.
#25 
> chore: update CODE_OF_CONDUCT.md

- package-lock.json
- package.json
- src/app/clients/clients.module.ts
- src/app/clients/create-client/create-client.component.html
> feat : angular wizard added

- .travis.yml
Fix error that occurred while merging of the pull request.
> ci: update .travis.yml

- README.md
- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/core/shell/header/header.component.html
- src/app/home/dashboard/dashboard.component.html
- src/app/home/dashboard/dashboard.component.scss
- src/app/home/dashboard/dashboard.component.spec.ts
- src/app/home/dashboard/dashboard.component.ts
- src/app/home/dashboard/data.ts
- src/app/home/home-routing.module.ts
- src/app/home/home.module.ts
- src/app/login/login.component.scss
> Dashboard UI 

- src/app/accounting/accounting-routing.module.ts
- src/app/accounting/accounting.component.html
- src/app/clients/clients-routing.module.ts
- src/app/clients/clients.component.html
- src/app/clients/create-client/create-client.component.html
- src/app/clients/view-client/view-client.component.html
- src/app/clients/view-loan/view-loan.component.html
- src/app/navigation/navigation-routing.module.ts
- src/app/navigation/navigation.component.html
Remove multiple usage of app header component and use the shell component
to route with shell, loading the header only once initially.
#47 
> fix: multiple usage of app header

- src/app/app.module.ts
- src/app/core/shell/header/header.component.html
- src/app/self-service/create-user/create-user.component.html
- src/app/self-service/create-user/create-user.component.spec.ts
- src/app/self-service/create-user/create-user.component.ts
- src/app/self-service/self-service-routing.module.ts
- src/app/self-service/self-service.module.spec.ts
- src/app/self-service/self-service.module.ts
- src/app/self-service/user-management/user-management.component.html
- src/app/self-service/user-management/user-management.component.scss
- src/app/self-service/user-management/user-management.component.spec.ts
- src/app/self-service/user-management/user-management.component.ts
- src/app/self-service/view-user/view-user.component.html
- src/app/self-service/view-user/view-user.component.spec.ts
- src/app/self-service/view-user/view-user.component.ts
- src/main.scss
Add initial UI design for self service user management.
#33 
#34 
> feat: UI for self service user management

- .travis.yml
update travis.yml for deployment to gh-pages
(Issue in deployment)
> ci: update travis.yml

- src/main.ts
Add hammer.js for touch gesture support.
#54 
> build(main.ts): add hammer.js

- src/app/core/core.module.ts
- src/app/core/progress-bar.service.spec.ts
- src/app/core/progress-bar.service.ts
- src/app/core/progress.interceptor.ts
- src/app/core/shell/shell.component.html
- src/app/core/shell/shell.component.ts
Add progress bar for loading data via HTTP requests.
#65 
> feat: add progress bar

- src/assets/styles/_helper.scss
- src/assets/styles/_loader.scss
- src/index.html
- src/main.scss
Integrate animation loader to be shown while the application is bootstrapped.
#58 
> feat: integrate animation loader

- .travis.yml
- package.json
Update Travis build to prevent hashing of files for theme configuration.
#70 
> ci: update travis build

- angular.json
- src/app/core/shell/toolbar/theme-picker/theme-picker.component.html
- src/app/core/shell/toolbar/theme-picker/theme-picker.component.ts
- src/app/home/home.component.html
- src/app/home/home.component.scss
- src/app/home/home.module.ts
- src/theme/custom/denim-yellowgreen.scss
- src/theme/custom/pictonblue-yellowgreen.scss
Add custom themes based on logo of Mifos
[x] denim-yellowgreen
[x] pictonblue-yellowgreen
#73 
> feat: add custom themes

- src/app/core/core.module.ts
- src/app/self-service/create-user/create-user.component.html
- src/app/self-service/create-user/create-user.component.ts
- src/app/self-service/edit-user/edit-user.component.html
- src/app/self-service/edit-user/edit-user.component.spec.ts
- src/app/self-service/edit-user/edit-user.component.ts
- src/app/self-service/self-service-routing.module.ts
- src/app/self-service/self-service.module.ts
- src/app/self-service/user-management/user-management.component.html
- src/app/self-service/user-management/user-management.component.scss
- src/app/self-service/user-management/user-management.component.ts
- src/app/self-service/view-user/view-user.component.html
- src/app/self-service/view-user/view-user.component.ts
Update UI for self-service user management using angular-material.
#33 
#34 
> feat: update UI for self service user management

- src/app/app.module.ts
- src/app/core/core.module.ts
- src/app/core/shell/sidenav/sidenav.component.html
- src/app/core/shell/toolbar/toolbar.component.html
- src/app/self-service/app-configuration/app-configuration.component.html
- src/app/self-service/app-configuration/app-configuration.component.spec.ts
- src/app/self-service/app-configuration/app-configuration.component.ts
- src/app/self-service/self-service-routing.module.ts
- src/app/self-service/self-service.module.ts
- src/app/settings/settings-routing.module.ts
- src/app/settings/settings.component.html
- src/app/settings/settings.component.spec.ts
- src/app/settings/settings.component.ts
- src/app/settings/settings.module.spec.ts
- src/app/settings/settings.module.ts
- src/app/shared/file-upload/file-upload.component.html
- src/app/shared/file-upload/file-upload.component.spec.ts
- src/app/shared/file-upload/file-upload.component.ts
- src/app/shared/shared.module.ts
Add settings and app configuration UI for web-app and self-service applications.
#35 
#36 
> feat: add settings and app configuration UI

- src/app/core/shell/shell.component.ts
- src/app/core/shell/toolbar/toolbar.component.ts
> feat: change default state of sidebar

- src/app/clients/clients.service.ts
- src/app/clients/view-client/view-client.component.html
- src/app/clients/view-client/view-client.component.ts
> feat(notes): Notes feature added with GET/POST

- src/app/core/core.module.ts
- src/app/core/shell/shell.component.ts
- src/app/self-service/user-management/user-management.component.html
- src/app/self-service/user-management/user-management.component.scss
- src/app/self-service/user-management/user-management.component.ts
- src/app/self-service/user.service.spec.ts
- src/app/self-service/user.service.ts
Add user management service for self-service and update http interceptor for the progress bar.
NA
> feat: add user management service

- src/app/core/authentication/authentication.service.ts
- src/app/self-service/user.service.ts
- tslint.json
Update API for self-service user management to leverage current HTTP interceptors for setting the API prefix and request headers.
#123 
NA
> fix(self-service): update API to leverage current HTTP interceptors

- package-lock.json
- package.json
- src/app/core/shell/toolbar/theme-picker/theme-picker.component.ts
- src/app/core/shell/toolbar/theme-picker/theme-storage.service.ts
Remove unnecessary dependency and use browser local storage to store theme instead.
#125 
NA
> build(theme): remove unnecessary dependency on @ngx-pwa/local-storage

- src/app/accounting/accounting-routing.module.ts
- src/app/accounting/accounting.component.html
- src/app/accounting/accounting.module.ts
- src/app/accounting/accounting.service.ts
- src/app/accounting/create-journal-entry/create-journal-entry.component.html
- src/app/accounting/create-journal-entry/create-journal-entry.component.spec.ts
- src/app/accounting/create-journal-entry/create-journal-entry.component.ts
Add create journal entries component for manual transactions.
#143 
> feat(accounting): create journal entries component

- .github/CONTRIBUTING.md
- README.md
- src/environments/environment.prod.ts
- src/environments/environment.ts
Update README.md and CONTRIBUTING.md
NA
NA
> chore: update guidelines

- README.md
Fix installation link for node package manager.
NA
NA
> fix: installation link in README.md

- src/app/app.module.ts
- src/app/centers/centers-routing.module.ts
- src/app/centers/centers.component.html
- src/app/centers/centers.component.scss
- src/app/centers/centers.component.ts
- src/app/centers/centers.module.ts
- src/app/centers/centers.service.ts
- src/app/clients/clients-routing.module.ts
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
- src/app/clients/edit-address/edit-address.component.html
- src/app/clients/edit-address/edit-address.component.scss
- src/app/clients/edit-address/edit-address.component.spec.ts
- src/app/clients/edit-address/edit-address.component.ts
- src/app/clients/view-client/view-client-component-dialog.html
- src/app/clients/view-client/view-client.component.html
- src/app/clients/view-client/view-client.component.ts
- src/app/core/shell/toolbar/toolbar.component.html
- src/app/groups/groups-routing.module.ts
- src/app/groups/groups.component.html
- src/app/groups/groups.component.scss
- src/app/groups/groups.component.ts
- src/app/groups/groups.module.ts
- src/app/groups/groups.service.ts
> feat(centers && groups) : Centers and groups list

- src/app/clients/clients.component.html
- src/app/clients/clients.component.scss
- src/app/clients/clients.component.ts
> fix(clients): improve clients active/inactive icons

- src/app/accounting/accounting-routing.module.ts
- src/app/accounting/accounting.module.ts
- src/app/accounting/accounting.service.ts
- src/app/accounting/chart-of-accounts/chart-of-accounts.component.html
- src/app/accounting/chart-of-accounts/chart-of-accounts.component.ts
- src/app/accounting/chart-of-accounts/create-gl-account/create-gl-account.component.html
- src/app/accounting/chart-of-accounts/create-gl-account/create-gl-account.component.scss
- src/app/accounting/chart-of-accounts/create-gl-account/create-gl-account.component.spec.ts
- src/app/accounting/chart-of-accounts/create-gl-account/create-gl-account.component.ts
- src/app/accounting/chart-of-accounts/edit-gl-account/edit-gl-account.component.html
- src/app/accounting/chart-of-accounts/edit-gl-account/edit-gl-account.component.spec.ts
- src/app/accounting/chart-of-accounts/edit-gl-account/edit-gl-account.component.ts
- src/app/accounting/chart-of-accounts/view-gl-account/view-gl-account.component.html
- src/app/accounting/chart-of-accounts/view-gl-account/view-gl-account.component.scss
- src/app/accounting/chart-of-accounts/view-gl-account/view-gl-account.component.spec.ts
- src/app/accounting/chart-of-accounts/view-gl-account/view-gl-account.component.ts
- src/app/accounting/chart-of-accounts/view-gl-account/view-gl-account.resolver.ts
> Accounting: General Ledger Account

- src/app/accounting/accounting-routing.module.ts
- src/app/accounting/accounting.component.html
- src/app/accounting/accounting.module.ts
- src/app/accounting/accounting.service.ts
- src/app/accounting/periodic-accruals/periodic-accruals.component.html
- src/app/accounting/periodic-accruals/periodic-accruals.component.scss
- src/app/accounting/periodic-accruals/periodic-accruals.component.spec.ts
- src/app/accounting/periodic-accruals/periodic-accruals.component.ts
Add periodic accruals component to execute periodic accrual accounting till a specified date.
#273 
> feat(accounting): add periodic accruals component

- src/app/accounting/accounting-routing.module.ts
- src/app/accounting/accounting.component.html
- src/app/accounting/accounting.module.ts
- src/app/accounting/accounting.service.ts
- src/app/accounting/migrate-opening-balances/migrate-opening-balances.component.html
- src/app/accounting/migrate-opening-balances/migrate-opening-balances.component.scss
- src/app/accounting/migrate-opening-balances/migrate-opening-balances.component.spec.ts
- src/app/accounting/migrate-opening-balances/migrate-opening-balances.component.ts
Add migrate opening balances component to set the opening balances for GL Accounts for a branch or entire organization.
#276 
> feat(accounting): migrate opening balances

- package-lock.json
Update adm-zip from 0.4.4 to 0.4.11
NA
NA
> build: remove vulnerability

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/self-service/self-service.module.ts
- src/app/settings/settings-routing.module.ts
- src/app/settings/settings.component.html
- src/app/settings/settings.component.scss
- src/app/settings/settings.component.ts
- src/app/settings/settings.module.ts
- src/app/shared/shared.module.ts
- src/app/web-app.component.ts
> refractor: app module and settings

- src/app/system/codes/codes.component.html
- src/app/system/codes/codes.component.scss
- src/app/system/codes/codes.component.ts
- src/app/system/codes/codes.resolver.ts
- src/app/system/system-routing.module.ts
- src/app/system/system.module.ts
- src/app/system/system.service.spec.ts
- src/app/system/system.service.ts
Adds Functionality for Codes Component
Fixes #172 
> feat: add functionality for codes component

- src/app/system/codes/codes.component.html
- src/app/system/codes/create-code/create-code.component.html
- src/app/system/codes/create-code/create-code.component.scss
- src/app/system/codes/create-code/create-code.component.spec.ts
- src/app/system/codes/create-code/create-code.component.ts
- src/app/system/system-routing.module.ts
- src/app/system/system.module.ts
- src/app/system/system.service.ts
Adds UI and functionality for Adding a Code.
**Note:** Currently it Redirects to the Codes Table after successful submission.
> feat: add add-code component

- src/app/system/manage-data-tables/manage-data-tables.component.html
- src/app/system/manage-data-tables/manage-data-tables.component.scss
- src/app/system/manage-data-tables/manage-data-tables.component.spec.ts
- src/app/system/manage-data-tables/manage-data-tables.component.ts
- src/app/system/manage-data-tables/manage-data-tables.resolver.ts
- src/app/system/system-routing.module.ts
- src/app/system/system.component.html
- src/app/system/system.module.ts
- src/app/system/system.service.ts
Implemented datatables component as shown in #170.
#170 
> feat: add datatables component

- src/app/system/manage-hooks/manage-hooks.component.html
- src/app/system/manage-hooks/manage-hooks.component.scss
- src/app/system/manage-hooks/manage-hooks.component.spec.ts
- src/app/system/manage-hooks/manage-hooks.component.ts
- src/app/system/manage-hooks/manage-hooks.resolver.ts
- src/app/system/system-routing.module.ts
- src/app/system/system.component.html
- src/app/system/system.module.ts
- src/app/system/system.service.ts
Implemented datatables component as shown in #179.
#179 
(GIF file is corrupted when analyzing the green/red colors (not sure why). I tried to record many times so here is screenshot to clear up any confusion.)
> feat: add hooks component

- src/app/system/manage-surveys/manage-surveys.component.html
- src/app/system/manage-surveys/manage-surveys.component.scss
- src/app/system/manage-surveys/manage-surveys.component.spec.ts
- src/app/system/manage-surveys/manage-surveys.component.ts
- src/app/system/manage-surveys/manage-surveys.resolver.ts
- src/app/system/system-routing.module.ts
- src/app/system/system.component.html
- src/app/system/system.module.ts
- src/app/system/system.service.ts
There is no survey component in the web app. This adds a survey component into the >System directory and routes it up.
#186 
> feat: Manage Surveys Component

- src/app/products/charges/charges.component.html
- src/app/products/charges/charges.component.scss
- src/app/products/charges/charges.component.spec.ts
- src/app/products/charges/charges.component.ts
- src/app/products/charges/charges.resolver.ts
- src/app/products/products-routing.module.ts
- src/app/products/products.component.html
- src/app/products/products.module.ts
- src/app/products/products.service.ts
Implemented charges component. It is a bit different from community-app screen. I made the Is Penalty? into red/green circles with checks/times for yes/no. I made the status into red/green circles.
187
There are a few visual errors with the circles in the gif, but they do not occur when testing on machine.
> feat: add charges component

- src/app/products/fixed-deposit-products/fixed-deposit-products.component.html
- src/app/products/fixed-deposit-products/fixed-deposit-products.component.scss
- src/app/products/fixed-deposit-products/fixed-deposit-products.component.spec.ts
- src/app/products/fixed-deposit-products/fixed-deposit-products.component.ts
- src/app/products/fixed-deposit-products/fixed-deposit-products.resolver.ts
- src/app/products/products-routing.module.ts
- src/app/products/products.component.html
- src/app/products/products.module.ts
- src/app/products/products.service.ts
Implemented Fixed deposit products component.
#187 
> feat: add fixed deposit products component

- src/app/products/products-mix/products-mix.component.html
- src/app/products/products-mix/products-mix.component.scss
- src/app/products/products-mix/products-mix.component.spec.ts
- src/app/products/products-mix/products-mix.component.ts
- src/app/products/products-mix/products-mix.resolver.ts
- src/app/products/products-routing.module.ts
- src/app/products/products.component.html
- src/app/products/products.module.ts
- src/app/products/products.service.ts
Implements product mix component
#195
> feat: add product mix component

- src/app/accounting/accounting.component.html
- src/app/core/authentication/credentials.model.ts
- src/app/core/shell/toolbar/toolbar.component.html
- src/app/login/login.component.html
- src/app/self-service/app-configuration/app-configuration.component.html
- src/app/settings/settings.component.html
Changed all instances of 'organisation' to 'organization'
#330
> refactor: following American Eng conventions by default

- src/app/clients/view-client/view-client.component.html
- src/app/clients/view-client/view-client.component.ts
Implement pagination to view the loans/savings/Shares in the client page
#133 
> refactor:implement pagination to view loan/saving/share in client page 

- src/app/products/products-routing.module.ts
- src/app/products/products.service.ts
Reformatted docs in products.service.ts in the comments.
#348
> docs: correct comments in products directory

- src/app/core/shell/shell.component.scss
- src/app/core/shell/sidenav/sidenav.component.html
- src/app/core/shell/sidenav/sidenav.component.scss
- update shell.component.scss file to add scroll bar when content overflows 
- update sidenav.component.scss to remove absolute positioned app icon and fix frequently visted links spacing.
- update sidenav.component.html to move frequently  visted links heading to parent container.
#358 
> fix: made side-nav scrollable (#358)

- src/app/app.module.ts
- src/app/loans/add-loan-charge/add-loan-charge.component.html
- src/app/loans/add-loan-charge/add-loan-charge.component.scss
- src/app/loans/add-loan-charge/add-loan-charge.component.spec.ts
- src/app/loans/add-loan-charge/add-loan-charge.component.ts
- src/app/loans/common-resolvers/loan-charge-template.resolver.ts
- src/app/loans/loans-routing.module.spec.ts
- src/app/loans/loans-routing.module.ts
- src/app/loans/loans.module.spec.ts
- src/app/loans/loans.module.ts
- src/app/loans/loans.service.spec.ts
- src/app/loans/loans.service.ts
- Add Loans Module.(taking reference from community app)
- Add add-loan-charge component.
- Add loans-routing.module.ts 
- Add loan-charge-template.resolver.ts
I discovered that Loan View files had been created in clients module and its code is commented so I left a comment in  loans-routing.module.ts to add  the component there.
#247 
> feat: Add Loan Charge to existing loan accounts.

- src/app/products/manage-tax-components/manage-tax-components.component.html
- src/app/products/manage-tax-components/manage-tax-components.component.scss
- src/app/products/manage-tax-components/manage-tax-components.component.spec.ts
- src/app/products/manage-tax-components/manage-tax-components.component.ts
- src/app/products/manage-tax-components/manage-tax-components.resolver.ts
- src/app/products/manage-tax-configurations/manage-tax-configurations.component.html
- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
Add manage tax components component
#197 
Checklist
> feat: add manage tax components component (#197)

- src/app/system/codes/code.resolver.ts
- src/app/system/codes/codes.component.html
- src/app/system/codes/codes.component.scss
- src/app/system/codes/create-code/create-code.component.ts
- src/app/system/codes/edit-code/edit-code.component.html
- src/app/system/codes/edit-code/edit-code.component.scss
- src/app/system/codes/edit-code/edit-code.component.spec.ts
- src/app/system/codes/edit-code/edit-code.component.ts
- src/app/system/codes/view-code/code-values.resolver.ts
- src/app/system/codes/view-code/view-code.component.html
- src/app/system/codes/view-code/view-code.component.scss
- src/app/system/codes/view-code/view-code.component.spec.ts
- src/app/system/codes/view-code/view-code.component.ts
- src/app/system/system-routing.module.ts
- src/app/system/system.module.ts
- src/app/system/system.service.ts
Added view-code and edit-code component, designed their screens and added functionality too.
Functionalities added are -
- View Code
- Edit Code
- Delete Code
- View Code Value
- Edit Code Value
- Delete Code Value
#379
_View Code_
_Edit Code_
> feat: add edit-code and view-code component

- src/app/app.module.ts
- src/app/clients/clients-routing.module.ts
- src/app/clients/clients-view/clients-view.component-theme.scss
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.scss
- src/app/clients/clients-view/clients-view.component.spec.ts
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/clients/clients-view/general-tab/general-tab.component.scss
- src/app/clients/clients-view/general-tab/general-tab.component.spec.ts
- src/app/clients/clients-view/general-tab/general-tab.component.ts
- src/app/clients/clients.component.html
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
- src/app/clients/common-resolvers/client-accounts.resolver.ts
- src/app/clients/common-resolvers/client-charges.resolver.ts
- src/app/clients/common-resolvers/client-summary.resolver.ts
- src/app/clients/common-resolvers/client-view.resolver.ts
- src/app/pipes/accounts-filter.pipe.spec.ts
- src/app/pipes/accounts-filter.pipe.ts
- src/app/pipes/fetch-image.pipe.spec.ts
- src/app/pipes/pipes.module.spec.ts
- src/app/pipes/pipes.module.ts
- src/app/pipes/status-lookup.pipe.spec.ts
- src/app/pipes/status-lookup.pipe.ts
- src/app/shared/shared.module.ts
- src/assets/styles/_colours.scss
- src/assets/styles/_helper.scss
- src/theme/custom/denim-yellowgreen.scss
- src/theme/custom/pictonblue-yellowgreen.scss
- add client view page
- add general tab 
- add status lookup pipe to store styles based on status
- add accounts filter pipe to filter accounts
- add status related colors in _color.scss
#216
> feat: add clients view page

- src/app/clients/clients.service.ts
- src/app/pipes/fetch-image.pipe.spec.ts
Clients service was not being injected correctly.
#416
> fix: production build on gh-pages

- src/app/clients/clients-routing.module.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients-view/family-members-tab/family-members-tab.component.html
- src/app/clients/clients-view/family-members-tab/family-members-tab.component.scss
- src/app/clients/clients-view/family-members-tab/family-members-tab.component.spec.ts
- src/app/clients/clients-view/family-members-tab/family-members-tab.component.ts
- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
- src/app/clients/common-resolvers/client-family-member.resolver.ts
- src/app/clients/common-resolvers/client-family-members.resolver.ts
- src/app/clients/common-resolvers/client-template.resolver.ts
- src/app/shared/delete-dialog/delete-dialog.component.html
- add family member tab component
- Change delete button color to warn in  delete dialog box
#262 , #80
> feat:family members list

- src/app/clients/clients-routing.module.ts
- src/app/clients/clients-view/family-members-tab/add-family-member/add-family-member.component.html
- src/app/clients/clients-view/family-members-tab/add-family-member/add-family-member.component.scss
- src/app/clients/clients-view/family-members-tab/add-family-member/add-family-member.component.spec.ts
- src/app/clients/clients-view/family-members-tab/add-family-member/add-family-member.component.ts
- src/app/clients/clients-view/family-members-tab/edit-family-member/edit-family-member.component.html
- src/app/clients/clients-view/family-members-tab/edit-family-member/edit-family-member.component.scss
- src/app/clients/clients-view/family-members-tab/edit-family-member/edit-family-member.component.spec.ts
- src/app/clients/clients-view/family-members-tab/edit-family-member/edit-family-member.component.ts
- src/app/clients/clients.module.ts
- add/edit family member page
#263
> feat: add/edit family member page

- src/app/clients/clients-routing.module.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/identities-tab/identities-tab.component.html
- src/app/clients/clients-view/identities-tab/identities-tab.component.scss
- src/app/clients/clients-view/identities-tab/identities-tab.component.spec.ts
- src/app/clients/clients-view/identities-tab/identities-tab.component.ts
- src/app/clients/clients-view/upload-document-dialog/upload-document-dialog.component.html
- src/app/clients/clients-view/upload-document-dialog/upload-document-dialog.component.spec.ts
- src/app/clients/clients-view/upload-document-dialog/upload-document-dialog.component.ts
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
- src/app/clients/common-resolvers/client-identities.resolver.ts
- src/app/core/authentication/authentication.interceptor.ts
- src/app/shared/icons.module.ts
- add identities-tab component
- add upload-document-dialog component
- remove content-type header from authentication interceptor in order to send a multipart/form-data request to upload files
#261
> feat: clients identities page

- src/app/clients/clients-routing.module.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/edit-notes-dialog/edit-notes-dialog.component.html
- src/app/clients/clients-view/edit-notes-dialog/edit-notes-dialog.component.spec.ts
- src/app/clients/clients-view/edit-notes-dialog/edit-notes-dialog.component.ts
- src/app/clients/clients-view/notes-tab/notes-tab.component.html
- src/app/clients/clients-view/notes-tab/notes-tab.component.scss
- src/app/clients/clients-view/notes-tab/notes-tab.component.spec.ts
- src/app/clients/clients-view/notes-tab/notes-tab.component.ts
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
- src/app/clients/common-resolvers/client-notes.resolver.ts
- src/app/shared/icons.module.ts
- add notes-tab.component
- add edit-note-dialog.coponent
#111
> feat: client notes page

- src/environments/environment.ts
> ci: change default server to staging

- src/environments/environment.prod.ts
- src/environments/environment.ts
changed default server to staging in  environment.prod.ts file 
#423
> change default production build server to staging

- src/app/shared/form-dialog/form-dialog.component.html
- src/app/shared/form-dialog/form-dialog.component.spec.ts
- src/app/shared/form-dialog/form-dialog.component.ts
- src/app/shared/form-dialog/form-group.service.spec.ts
- src/app/shared/form-dialog/form-group.service.ts
- src/app/shared/form-dialog/formfield/formfield.component.html
- src/app/shared/form-dialog/formfield/formfield.component.spec.ts
- src/app/shared/form-dialog/formfield/formfield.component.ts
- src/app/shared/form-dialog/formfield/model/formfield-base.ts
- src/app/shared/form-dialog/formfield/model/input-base.ts
- src/app/shared/form-dialog/formfield/model/select-base.ts
- src/app/shared/shared.module.ts
This custom component will help in the creation of dynamic forms within a modal.
- Add formfield, input, select base (model)
- Add formfield component
- Add form-group service
- Add form-dialog component
#427 
N/A
> feat: add form dialog component

- .travis.yml
- package.json
- Fix heap memory allocation issue
- Update package.json and .travis.yml
#436 
N/A
> build: update production build script

- src/app/clients/clients-routing.module.ts
- src/app/clients/clients-view/identities-tab/identities-tab.component.html
- src/app/clients/clients-view/identities-tab/identities-tab.component.ts
- src/app/clients/clients.service.ts
- src/app/clients/common-resolvers/client-identifier-template.resolver.ts
- src/app/shared/form-dialog/form-dialog.component.html
- added feature to add client identifiers
#260
> feat (clients) : add client identifier

- src/app/products/loan-products/loan-product.resolver.ts
- src/app/products/loan-products/loan-products.component.html
- src/app/products/loan-products/loan-products.component.scss
- src/app/products/loan-products/view-loan-product/view-loan-product.component.html
- src/app/products/loan-products/view-loan-product/view-loan-product.component.scss
- src/app/products/loan-products/view-loan-product/view-loan-product.component.spec.ts
- src/app/products/loan-products/view-loan-product/view-loan-product.component.ts
- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
Add view loan product component to view a loan product.
#438 
> feat: view loan product component

- src/app/clients/clients-view/address-tab/address-tab.component.html
- src/app/clients/clients-view/address-tab/address-tab.component.ts
- src/app/clients/clients.service.ts
- add/edit/enable/disable address feature implemented
#259
> feat (clients) : add, edit, enable, disable address

- src/app/clients/clients-view/datatable-tab/multi-row/multi-row.component.html
- src/app/clients/clients-view/datatable-tab/multi-row/multi-row.component.ts
- src/app/clients/clients.service.ts
- add feature to allow user to make a multi row datatable entry
#449
> feat (clients): add data in multi row datatables

- src/app/pipes/charges-filter.pipe.ts
- src/app/products/loan-products/create-loan-product/create-loan-product.component.html
- src/app/products/loan-products/edit-loan-product/edit-loan-product.component.html
- src/app/products/loan-products/edit-loan-product/edit-loan-product.component.spec.ts
- src/app/products/loan-products/edit-loan-product/edit-loan-product.component.ts
- src/app/products/loan-products/edit-loan-product/loan-product-and-template.resolver.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-accounting-step/loan-product-accounting-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-accounting-step/loan-product-accounting-step.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-charges-step/loan-product-charges-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-charges-step/loan-product-charges-step.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-currency-step/loan-product-currency-step.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-details-step/loan-product-details-step.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-terms-step/loan-product-terms-step.component.ts
- src/app/products/loan-products/view-loan-product/view-loan-product.component.html
- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
- src/app/shared/form-dialog/form-dialog.component.ts
- Update loan product stepper components to support editing
- Add edit loan product component
- Add pristine property to form dialog
#439 
> feat: add edit loan product component

- src/app/products/products-routing.module.ts
- src/app/products/products.component.html
- src/app/products/products.module.ts
- src/app/products/products.service.ts
- src/app/products/saving-products/saving-products.component.html
- src/app/products/saving-products/saving-products.component.spec.ts
- src/app/products/saving-products/saving-products.component.ts
- src/app/products/saving-products/saving-products.resolver.ts
Add saving products component to list all saving products.
#440 
> feat(products): add saving products component

- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
- src/app/products/saving-products/saving-product.resolver.ts
- src/app/products/saving-products/saving-products.component.html
- src/app/products/saving-products/saving-products.component.scss
- src/app/products/saving-products/view-saving-product/view-saving-product.component.html
- src/app/products/saving-products/view-saving-product/view-saving-product.component.scss
- src/app/products/saving-products/view-saving-product/view-saving-product.component.spec.ts
- src/app/products/saving-products/view-saving-product/view-saving-product.component.ts
Add view saving product component to view a saving product.
#452 
> feat: view saving product component

- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
- src/app/products/saving-products/edit-saving-product/edit-saving-product.component.html
- src/app/products/saving-products/edit-saving-product/edit-saving-product.component.spec.ts
- src/app/products/saving-products/edit-saving-product/edit-saving-product.component.ts
- src/app/products/saving-products/edit-saving-product/saving-product-and-template.resolver.ts
- src/app/products/saving-products/saving-product-stepper/saving-product-accounting-step/saving-product-accounting-step.component.ts
- src/app/products/saving-products/saving-product-stepper/saving-product-charges-step/saving-product-charges-step.component.ts
- src/app/products/saving-products/saving-product-stepper/saving-product-currency-step/saving-product-currency-step.component.ts
- src/app/products/saving-products/saving-product-stepper/saving-product-details-step/saving-product-details-step.component.html
- src/app/products/saving-products/saving-product-stepper/saving-product-details-step/saving-product-details-step.component.ts
- src/app/products/saving-products/saving-product-stepper/saving-product-settings-step/saving-product-settings-step.component.ts
- src/app/products/saving-products/saving-product-stepper/saving-product-terms-step/saving-product-terms-step.component.ts
- src/app/products/saving-products/view-saving-product/view-saving-product.component.html
- Update saving product stepper components to support editing
- Add edit saving product component
#453 
> feat: add edit saving product component

- src/app/clients/clients-view/datatable-tab/multi-row/multi-row.component.html
- src/app/clients/clients-view/datatable-tab/multi-row/multi-row.component.ts
- src/app/clients/clients-view/datatable-tab/single-row/single-row.component.html
- src/app/clients/clients-view/datatable-tab/single-row/single-row.component.scss
- src/app/clients/clients-view/datatable-tab/single-row/single-row.component.ts
- src/app/clients/clients.service.ts
- src/app/shared/form-dialog/formfield/formfield.component.html
- src/app/shared/form-dialog/formfield/model/checkbox-base.ts
- add checkbox-base.ts 
- update clients.service.ts file
- add delete feature in multi-row and single datatables
#460
> feat(clients): add/edit/delete data in single row data tables

- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
- src/app/products/share-products/share-product-resolver.ts
- src/app/products/share-products/share-product-stepper/share-product-preview-step/share-product-preview-step.component.html
- src/app/products/share-products/share-products.component.html
- src/app/products/share-products/share-products.component.scss
- src/app/products/share-products/view-share-product/view-share-product.component.html
- src/app/products/share-products/view-share-product/view-share-product.component.scss
- src/app/products/share-products/view-share-product/view-share-product.component.spec.ts
- src/app/products/share-products/view-share-product/view-share-product.component.ts
Add view share product component to view a share product.
#463
> feat: view share product component

- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
- src/app/products/share-products/edit-share-product/edit-share-product.component.html
- src/app/products/share-products/edit-share-product/edit-share-product.component.spec.ts
- src/app/products/share-products/edit-share-product/edit-share-product.component.ts
- src/app/products/share-products/edit-share-product/share-product-and-template.resolver.ts
- src/app/products/share-products/share-product-stepper/share-product-accounting-step/share-product-accounting-step.component.ts
- src/app/products/share-products/share-product-stepper/share-product-charges-step/share-product-charges-step.component.ts
- src/app/products/share-products/share-product-stepper/share-product-currency-step/share-product-currency-step.component.ts
- src/app/products/share-products/share-product-stepper/share-product-details-step/share-product-details-step.component.ts
- src/app/products/share-products/share-product-stepper/share-product-market-price-step/share-product-market-price-step.component.ts
- src/app/products/share-products/share-product-stepper/share-product-settings-step/share-product-settings-step.component.ts
- src/app/products/share-products/share-product-stepper/share-product-terms-step/share-product-terms-step.component.ts
- src/app/products/share-products/view-share-product/view-share-product.component.html
- Update share product stepper components to support editing
- Add edit share product component
#464 
> feat: add edit share product component

- src/app/system/manage-reports/create-report/create-report.component.html
- src/app/system/manage-reports/create-report/create-report.component.scss
- src/app/system/manage-reports/create-report/create-report.component.spec.ts
- src/app/system/manage-reports/create-report/create-report.component.ts
- src/app/system/manage-reports/edit-report/edit-report.component.html
- src/app/system/manage-reports/edit-report/edit-report.component.scss
- src/app/system/manage-reports/edit-report/edit-report.component.spec.ts
- src/app/system/manage-reports/edit-report/edit-report.component.ts
- src/app/system/manage-reports/manage-reports.component.html
- src/app/system/manage-reports/manage-reports.component.scss
- src/app/system/manage-reports/manage-reports.component.spec.ts
- src/app/system/manage-reports/manage-reports.component.ts
- src/app/system/manage-reports/report-parameter-dialog/report-parameter-dialog.component.html
- src/app/system/manage-reports/report-parameter-dialog/report-parameter-dialog.component.spec.ts
- src/app/system/manage-reports/report-parameter-dialog/report-parameter-dialog.component.ts
- src/app/system/manage-reports/report-template.resolver.ts
- src/app/system/manage-reports/report.resolver.ts
- src/app/system/manage-reports/reports.resolver.ts
- src/app/system/manage-reports/view-report/view-report.component.html
- src/app/system/manage-reports/view-report/view-report.component.scss
- src/app/system/manage-reports/view-report/view-report.component.spec.ts
- src/app/system/manage-reports/view-report/view-report.component.ts
- src/app/system/system-routing.module.ts
- src/app/system/system.component.html
- src/app/system/system.module.ts
- src/app/system/system.service.ts
Components added are:
- manage-reports
- view-report
- create-report
- edit-report
#174
Create Report
Edit Report
View All Reports
View Report
Report Parameter dialog with error
> feat: add multiple components for reports

- src/app/system/roles-and-permissions/add-role/add-role.component.html
- src/app/system/roles-and-permissions/add-role/add-role.component.scss
- src/app/system/roles-and-permissions/add-role/add-role.component.spec.ts
- src/app/system/roles-and-permissions/add-role/add-role.component.ts
- src/app/system/roles-and-permissions/roles-and-permissions.component.html
- src/app/system/system-routing.module.ts
- src/app/system/system.module.ts
- src/app/system/system.service.ts
Have added a new add role component. The component is supposed to link to a view roles page, however, this has not yet been created. I will create this in a following PR.
https://github.com/openMF/web-app/issues/487
> feat: add add role component

- src/app/organization/loan-provisioning-criteria/loan-provisioning-criteria.component.html
- src/app/organization/loan-provisioning-criteria/loan-provisioning-criteria.component.scss
- src/app/organization/loan-provisioning-criteria/loan-provisioning-criteria.component.spec.ts
- src/app/organization/loan-provisioning-criteria/loan-provisioning-criteria.component.ts
- src/app/organization/loan-provisioning-criteria/loan-provisioning-criteria.resolver.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.component.html
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.spec.ts
- src/app/organization/organization.service.ts
- Add Loan Provisioning Criteria Component
- Add Organization Service
#165 
Community App
Web App
> feat: add loan provisioning criteria component

- src/app/organization/offices/offices.component.html
- src/app/organization/offices/offices.component.scss
- src/app/organization/offices/offices.component.spec.ts
- src/app/organization/offices/offices.component.ts
- src/app/organization/offices/offices.resolver.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.component.html
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
> feat: add offices component

- src/app/organization/employees/employees.component.html
- src/app/organization/employees/employees.component.scss
- src/app/organization/employees/employees.component.spec.ts
- src/app/organization/employees/employees.component.ts
- src/app/organization/employees/employees.resolver.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.component.html
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- Add employees component
#156
> feat: add employees component

- src/app/templates/template.resolver.ts
- src/app/templates/templates-routing.module.ts
- src/app/templates/templates.component.html
- src/app/templates/templates.component.scss
- src/app/templates/templates.module.ts
- src/app/templates/templates.service.ts
- src/app/templates/view-template/view-template.component.html
- src/app/templates/view-template/view-template.component.scss
- src/app/templates/view-template/view-template.component.spec.ts
- src/app/templates/view-template/view-template.component.ts
- Add view template component
#512
> feat: add view template component

- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.component.html
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- src/app/organization/sms-campaigns/sms-campaigns.component.html
- src/app/organization/sms-campaigns/sms-campaigns.component.scss
- src/app/organization/sms-campaigns/sms-campaigns.component.spec.ts
- src/app/organization/sms-campaigns/sms-campaigns.component.ts
- src/app/organization/sms-campaigns/sms-campaigns.resolver.ts
- src/app/pipes/status-lookup.pipe.ts
- Add SMS campaigns component
#166 
> feat: add sms campaigns component

- src/app/organization/adhoc-query/adhoc-queries.resolver.ts
- src/app/organization/adhoc-query/adhoc-query.component.html
- src/app/organization/adhoc-query/adhoc-query.component.scss
- src/app/organization/adhoc-query/adhoc-query.component.spec.ts
- src/app/organization/adhoc-query/adhoc-query.component.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.component.html
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- Add Adhoc Query component
#511
Adhoc Query
> feat: add adhoc query component

- src/app/app.module.ts
- src/app/core/shell/toolbar/toolbar.component.html
- src/app/users/users-routing.module.ts
- src/app/users/users.component.html
- src/app/users/users.component.scss
- src/app/users/users.component.spec.ts
- src/app/users/users.component.ts
- src/app/users/users.module.ts
- src/app/users/users.resolver.ts
- src/app/users/users.service.ts
> feat: add users components

- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.component.html
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- src/app/organization/tellers/tellers.component.html
- src/app/organization/tellers/tellers.component.scss
- src/app/organization/tellers/tellers.component.spec.ts
- src/app/organization/tellers/tellers.component.ts
- src/app/organization/tellers/tellers.resolver.ts
> feat: add tellers component

- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.component.html
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- src/app/organization/payment-types/payment-types.component.html
- src/app/organization/payment-types/payment-types.component.scss
- src/app/organization/payment-types/payment-types.component.spec.ts
- src/app/organization/payment-types/payment-types.component.ts
- src/app/organization/payment-types/payment-types.resolver.ts
- Add payment types component
#163
> feat: add payment types component

- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.component.html
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- src/app/organization/password-preferences/password-preferences-template.resolver.ts
- src/app/organization/password-preferences/password-preferences.component.html
- src/app/organization/password-preferences/password-preferences.component.scss
- src/app/organization/password-preferences/password-preferences.component.spec.ts
- src/app/organization/password-preferences/password-preferences.component.ts
- Add password preferences component
- Implemented password preferences template resolver
#510
> feat: add password preferences component

- src/app/organization/entity-data-table-checks/entity-data-table-checks.component.html
- src/app/organization/entity-data-table-checks/entity-data-table-checks.component.scss
- src/app/organization/entity-data-table-checks/entity-data-table-checks.component.spec.ts
- src/app/organization/entity-data-table-checks/entity-data-table-checks.component.ts
- src/app/organization/entity-data-table-checks/entity-data-table-checks.resolver.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.component.html
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- Add entity data table checks component
#168
> feat: add entity data table checks component

- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.component.html
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- src/app/organization/working-days/working-days.component.html
- src/app/organization/working-days/working-days.component.scss
- src/app/organization/working-days/working-days.component.spec.ts
- src/app/organization/working-days/working-days.component.ts
- src/app/organization/working-days/working-days.resolver.ts
Added the working days component, connected it to the app via routing and implemented the Required API.
#162 
> feat: add working days component (#162)

- src/app/organization/offices/create-office/create-office.component.html
- src/app/organization/offices/create-office/create-office.component.scss
- src/app/organization/offices/create-office/create-office.component.spec.ts
- src/app/organization/offices/create-office/create-office.component.ts
- src/app/organization/offices/offices.component.html
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
Add routing to Create Office button in Office directory, implement the API and design the UI.
#147 
> feat: add create offices component

- src/app/organization/employees/create-employee/create-employee.component.html
- src/app/organization/employees/create-employee/create-employee.component.scss
- src/app/organization/employees/create-employee/create-employee.component.spec.ts
- src/app/organization/employees/create-employee/create-employee.component.ts
- src/app/organization/employees/employees.component.html
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- Add create employee component
#157
> feat: add create employee component

- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- src/app/organization/payment-types/create-payment-type/create-payment-type.component.html
- src/app/organization/payment-types/create-payment-type/create-payment-type.component.scss
- src/app/organization/payment-types/create-payment-type/create-payment-type.component.spec.ts
- src/app/organization/payment-types/create-payment-type/create-payment-type.component.ts
- src/app/organization/payment-types/payment-types.component.html
Added Routing to the Create Payment Type Button, implemented the API and designed its UI
#164
> feat: add create payment type component

- src/app/users/create-user/create-user.component.html
- src/app/users/create-user/create-user.component.scss
- src/app/users/create-user/create-user.component.spec.ts
- src/app/users/create-user/create-user.component.ts
- src/app/users/users-routing.module.ts
- src/app/users/users-template.resolver.ts
- src/app/users/users.component.html
- src/app/users/users.module.ts
- src/app/users/users.service.ts
- Add create user component
#532
Email only required if user doesn't manually enter password 
> feat: add create user component

- src/app/organization/employees/employee.resolver.ts
- src/app/organization/employees/employees.component.html
- src/app/organization/employees/view-employee/view-employee.component.html
- src/app/organization/employees/view-employee/view-employee.component.scss
- src/app/organization/employees/view-employee/view-employee.component.spec.ts
- src/app/organization/employees/view-employee/view-employee.component.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
Added routing to the rows in Employee data table, implemented the API and designed the UI.
#534 
> feat: add view employee component

- src/app/organization/adhoc-query/adhoc-query.component.html
- src/app/organization/adhoc-query/adhoc-query.resolver.ts
- src/app/organization/adhoc-query/view-adhoc-query/view-adhoc-query.component.html
- src/app/organization/adhoc-query/view-adhoc-query/view-adhoc-query.component.scss
- src/app/organization/adhoc-query/view-adhoc-query/view-adhoc-query.component.spec.ts
- src/app/organization/adhoc-query/view-adhoc-query/view-adhoc-query.component.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
Added routing to rows in adhoc query table, implemented the API and designed the UI.
#538 
> feat: add view adhoc query component

- src/app/users/user.resolver.ts
- src/app/users/users-routing.module.ts
- src/app/users/users.component.html
- src/app/users/users.module.ts
- src/app/users/users.service.ts
- src/app/users/view-user/view-user.component.html
- src/app/users/view-user/view-user.component.scss
- src/app/users/view-user/view-user.component.spec.ts
- src/app/users/view-user/view-user.component.ts
Added the view user component, connected it via routing, designed its interface and connected it to the API.
#533 
> feat: add view user component

- src/app/products/charges/charge.resolver.ts
- src/app/products/charges/charges.component.html
- src/app/products/charges/view-charge/view-charge.component.html
- src/app/products/charges/view-charge/view-charge.component.scss
- src/app/products/charges/view-charge/view-charge.component.spec.ts
- src/app/products/charges/view-charge/view-charge.component.ts
- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
Added routing to the rows in Charges table, implemented the API and designed the UI.
#539 
> feat: add view charge component

- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- src/app/organization/tellers/teller.resolver.ts
- src/app/organization/tellers/tellers.component.html
- src/app/organization/tellers/view-teller/view-teller.component.html
- src/app/organization/tellers/view-teller/view-teller.component.scss
- src/app/organization/tellers/view-teller/view-teller.component.spec.ts
- src/app/organization/tellers/view-teller/view-teller.component.ts
**For your ease of review, here are the changes which deviate from the View Teller Page in the Community App :**
- Added `ngIf` directive to show the Description and End Date only when the data is available for them.
- Added `titlecase` pipe to Teller Status to improve the presentation of Status.
#535 
> feat: add view teller component

- src/app/products/manage-tax-components/manage-tax-components.component.html
- src/app/products/manage-tax-components/tax-component.resolver.ts
- src/app/products/manage-tax-components/view-tax-component/view-tax-component.component.html
- src/app/products/manage-tax-components/view-tax-component/view-tax-component.component.scss
- src/app/products/manage-tax-components/view-tax-component/view-tax-component.component.spec.ts
- src/app/products/manage-tax-components/view-tax-component/view-tax-component.component.ts
- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
Added the view tax component, connected it via routing, designed its interface and connected it to the API.
#540 
> feat: add view tax component

- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- src/app/organization/payment-types/edit-payment-type/edit-payment-type.component.html
- src/app/organization/payment-types/edit-payment-type/edit-payment-type.component.scss
- src/app/organization/payment-types/edit-payment-type/edit-payment-type.component.spec.ts
- src/app/organization/payment-types/edit-payment-type/edit-payment-type.component.ts
- src/app/organization/payment-types/payment-type.resolver.ts
- src/app/organization/payment-types/payment-types.component.html
Added routing to the Edit Button in Payment types table, implemented the API and designed the UI.
#536 
> feat: add edit payment type component

- src/app/products/floating-rates/create-floating-rate/create-floating-rate.component.html
- src/app/products/floating-rates/create-floating-rate/create-floating-rate.component.scss
- src/app/products/floating-rates/create-floating-rate/create-floating-rate.component.spec.ts
- src/app/products/floating-rates/create-floating-rate/create-floating-rate.component.ts
- src/app/products/floating-rates/edit-floating-rate/edit-floating-rate.component.html
- src/app/products/floating-rates/edit-floating-rate/edit-floating-rate.component.scss
- src/app/products/floating-rates/edit-floating-rate/edit-floating-rate.component.spec.ts
- src/app/products/floating-rates/edit-floating-rate/edit-floating-rate.component.ts
- src/app/products/floating-rates/floating-rate-period-dialog/floating-rate-period-dialog.component.html
- src/app/products/floating-rates/floating-rate-period-dialog/floating-rate-period-dialog.component.spec.ts
- src/app/products/floating-rates/floating-rate-period-dialog/floating-rate-period-dialog.component.ts
- src/app/products/floating-rates/floating-rate.resolver.ts
- src/app/products/floating-rates/floating-rates.component.html
- src/app/products/floating-rates/floating-rates.component.scss
- src/app/products/floating-rates/floating-rates.component.spec.ts
- src/app/products/floating-rates/floating-rates.component.ts
- src/app/products/floating-rates/floating-rates.resolver.ts
- src/app/products/floating-rates/view-floating-rate/view-floating-rate.component.html
- src/app/products/floating-rates/view-floating-rate/view-floating-rate.component.scss
- src/app/products/floating-rates/view-floating-rate/view-floating-rate.component.spec.ts
- src/app/products/floating-rates/view-floating-rate/view-floating-rate.component.ts
- src/app/products/products-routing.module.ts
- src/app/products/products.component.html
- src/app/products/products.module.ts
- src/app/products/products.service.ts
Functionalities added are:
- View all floating rates
- Create a floating rate
- View floating rate
- Edit floating rate
Components added are:
- floating-rates
- create-floating-rate
- view-floating-rate
- edit-floating-rate
#194 #187 
Create Floating Rate
Edit Floating Rate
View all Floating Rates
View Floating Rate
Floating Rate Period Dialog
> feat: add multiple components for floating rates

- src/app/system/manage-hooks/add-event-dialog/add-event-dialog.component.html
- src/app/system/manage-hooks/add-event-dialog/add-event-dialog.component.spec.ts
- src/app/system/manage-hooks/add-event-dialog/add-event-dialog.component.ts
- src/app/system/manage-hooks/create-hook/create-hook.component.html
- src/app/system/manage-hooks/create-hook/create-hook.component.scss
- src/app/system/manage-hooks/create-hook/create-hook.component.spec.ts
- src/app/system/manage-hooks/create-hook/create-hook.component.ts
- src/app/system/manage-hooks/edit-hook/edit-hook.component.html
- src/app/system/manage-hooks/edit-hook/edit-hook.component.scss
- src/app/system/manage-hooks/edit-hook/edit-hook.component.spec.ts
- src/app/system/manage-hooks/edit-hook/edit-hook.component.ts
- src/app/system/manage-hooks/hooks-template.resolver.ts
- src/app/system/manage-hooks/manage-hooks.component.html
- src/app/system/manage-hooks/manage-hooks.component.ts
- src/app/system/manage-hooks/view-hook/hook.resolver.ts
- src/app/system/manage-hooks/view-hook/view-hook.component.html
- src/app/system/manage-hooks/view-hook/view-hook.component.scss
- src/app/system/manage-hooks/view-hook/view-hook.component.spec.ts
- src/app/system/manage-hooks/view-hook/view-hook.component.ts
- src/app/system/system-routing.module.ts
- src/app/system/system.module.ts
- src/app/system/system.service.ts
Functionalities added are:
- Create Hook
- View Hook
- Edit Hook
Components added are:
- create-hook
- view-hook
- edit-hook
#180
Create Hook
Edit Hook
View Hook
Add Event Dialog
> feat: add multiple components for hooks

- src/app/users/create-user/create-user.component.ts
User is redirected to the created user after Submitting the Create User Form, instead of redirecting to the Users page.
#557 
> fix: redirect to created user after submitting create user form

- src/app/bulk-import/bulk-import-routing.module.ts
- src/app/bulk-import/bulk-import.component.html
- src/app/bulk-import/bulk-import.component.spec.ts
- src/app/bulk-import/bulk-import.component.ts
- src/app/bulk-import/bulk-import.module.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.component.html
- Add bulk import component
- Implemented module loaded with lazy loading
#542
> feat: add bulk import component

- src/app/products/manage-tax-components/create-tax-component/create-tax-component.component.html
- src/app/products/manage-tax-components/create-tax-component/create-tax-component.component.scss
- src/app/products/manage-tax-components/create-tax-component/create-tax-component.component.spec.ts
- src/app/products/manage-tax-components/create-tax-component/create-tax-component.component.ts
- src/app/products/manage-tax-components/manage-tax-components.component.html
- src/app/products/manage-tax-components/tax-component-template.resolver.ts
- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
Added the create tax component, connected it via routing, designed its interface and connected it to the API.
#198 
> feat: add create tax component

- src/app/organization/adhoc-query/adhoc-query-template.resolver.ts
- src/app/organization/adhoc-query/adhoc-query.component.html
- src/app/organization/adhoc-query/create-adhoc-query/create-adhoc-query.component.html
- src/app/organization/adhoc-query/create-adhoc-query/create-adhoc-query.component.scss
- src/app/organization/adhoc-query/create-adhoc-query/create-adhoc-query.component.spec.ts
- src/app/organization/adhoc-query/create-adhoc-query/create-adhoc-query.component.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
Added the create adhoc query component, connected it via routing, designed its interface and connected it to the API.
#537 
> feat: add create adhoc query component

- src/app/centers/centers.component.html
- src/app/centers/centers.component.scss
- src/app/centers/centers.component.ts
- src/app/centers/centers.datasource.ts
- src/app/centers/centers.module.ts
- src/app/centers/centers.service.ts
- Add Server-side pagination, sort and search for centers component
- Refactored code to meet current guidelines
#234
> feat: add server-side pagination sort and search for centers component

- src/app/groups/groups-routing.module.ts
- src/app/groups/groups.component.html
- src/app/groups/groups.component.scss
- src/app/groups/groups.component.ts
- src/app/groups/groups.datasource.ts
- src/app/groups/groups.module.ts
- src/app/groups/groups.service.ts
- Add server-side pagination, sort and search to groups component
- Refactor code to conform to current guidelines
#234
> feat: add server-side pagination, sort and search to groups component

- src/app/core/shell/sidenav/sidenav.component.html
Frequent Postings in side-nav routing resolved.
#731 
> fix: frequent posting route in side-nav

- src/app/core/shell/sidenav/sidenav.component.html
- src/app/core/shell/sidenav/sidenav.component.scss
Added routing functionality from the logo and text.
#717 
> feat: configure route in home logo

- src/app/core/shell/sidenav/sidenav.component.scss
horizontal scroll removed in sidebar
#651 
> fix: remove horizontal scroll in sidebar

- src/app/users/view-user/view-user.component.html
email will be only displayed if it is present in view user.
Now the email is only displayed if it is present in view user.
#584 
>  fix: make user email conditional

- src/app/organization/holidays/holidays.component.html
- src/app/organization/holidays/holidays.component.scss
- src/app/organization/holidays/holidays.component.spec.ts
- src/app/organization/holidays/holidays.component.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.component.html
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
Added routing to 'Manage Holidays' button in Organization directory, implemented the API and designed the UI for Holidays component.
#153 
> feat: add holidays component

- README.md
> fix: ng build --prod in README

- src/environments/environment.ts
Changes the Server URL so that application can work seamless.
#666 
> fix: change server URL

- src/app/organization/offices/edit-office/edit-office.component.html
- src/app/organization/offices/edit-office/edit-office.component.scss
- src/app/organization/offices/edit-office/edit-office.component.spec.ts
- src/app/organization/offices/edit-office/edit-office.component.ts
- src/app/organization/offices/edit-office/edit-office.resolver.ts
- src/app/organization/offices/offices.component.html
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
**Description**
Edit Office component completed
**Related issues and discussion**
#662 
**Screenshots, if any**
**Checklist**
> feat: add edit office component

- src/app/system/manage-scheduler-jobs/manage-scheduler-jobs.component.html
- src/app/system/manage-scheduler-jobs/view-scheduler-job/view-scheduler-job.component.html
- src/app/system/manage-scheduler-jobs/view-scheduler-job/view-scheduler-job.component.scss
- src/app/system/manage-scheduler-jobs/view-scheduler-job/view-scheduler-job.component.spec.ts
- src/app/system/manage-scheduler-jobs/view-scheduler-job/view-scheduler-job.component.ts
- src/app/system/manage-scheduler-jobs/view-scheduler-job/view-scheduler-job.resolver.ts
- src/app/system/system-routing.module.ts
- src/app/system/system.module.ts
- src/app/system/system.service.ts
**Description**
Component to view selected Job.
**Related issues and discussion**
#673 
**Screenshots, if any**
**Checklist**
> feat: add view scheduler job component

- src/environments/environment.prod.ts
Update production server URL to `staging.mifos.io`
#666 
N/A
> fix: update production server URL

- src/app/organization/employees/edit-employee.resolver.ts
- src/app/organization/employees/edit-employee/edit-employee.component.html
- src/app/organization/employees/edit-employee/edit-employee.component.scss
- src/app/organization/employees/edit-employee/edit-employee.component.spec.ts
- src/app/organization/employees/edit-employee/edit-employee.component.ts
- src/app/organization/employees/view-employee/view-employee.component.html
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
add edit employee component.
#581 
> feat: add edit employee component

- src/app/system/manage-scheduler-jobs/edit-scheduler-job/edit-scheduler-job.component.html
- src/app/system/manage-scheduler-jobs/edit-scheduler-job/edit-scheduler-job.component.scss
- src/app/system/manage-scheduler-jobs/edit-scheduler-job/edit-scheduler-job.component.spec.ts
- src/app/system/manage-scheduler-jobs/edit-scheduler-job/edit-scheduler-job.component.ts
- src/app/system/manage-scheduler-jobs/manage-scheduler-job.resolver.ts
- src/app/system/system-routing.module.ts
- src/app/system/system.module.ts
- src/app/system/system.service.ts
**Description**
Component to edit selected scheduler job completed.
**Related issues and discussion**
#677 
**Screenshots, if any**
**Checklist**
> feat: add edit scheduler job component

- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/clients/clients-view/general-tab/general-tab.component.ts
- src/app/clients/clients.service.ts
Payment and waive flag actions are added to the upcoming charges on general tab.
#691 
> feat: add waive flag and payment functions

- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- src/app/organization/tellers/create-teller/create-teller.component.html
- src/app/organization/tellers/create-teller/create-teller.component.scss
- src/app/organization/tellers/create-teller/create-teller.component.spec.ts
- src/app/organization/tellers/create-teller/create-teller.component.ts
- src/app/organization/tellers/tellers.component.html
add the create teller feature.
#160
> feat: add create teller component

- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- src/app/organization/tellers/edit-teller/edit-teller.component.html
- src/app/organization/tellers/edit-teller/edit-teller.component.scss
- src/app/organization/tellers/edit-teller/edit-teller.component.spec.ts
- src/app/organization/tellers/edit-teller/edit-teller.component.ts
- src/app/organization/tellers/view-teller/view-teller.component.html
add edit teller component.
#596
> feat: add edit teller component

- src/app/organization/organization.service.ts
Changed the request URL to properly fetch all the employees. This is the same as the one used in https://mobile.openmf.org/
#606 
> fix: inactive employees not being displayed

- src/app/centers/centers-routing.module.ts
- src/app/centers/centers.component.html
- src/app/centers/centers.module.ts
- src/app/centers/centers.service.ts
- src/app/centers/create-center/create-center.component.html
- src/app/centers/create-center/create-center.component.scss
- src/app/centers/create-center/create-center.component.spec.ts
- src/app/centers/create-center/create-center.component.ts
- src/app/groups/groups.service.ts
Added routing to 'Create Center' button in Center's List View, designed the UI for Create Center Form
and connected it to the API.
#210
**UI**
**Group Addition/Deletion**
> feat: add create center page

- src/app/products/manage-tax-components/edit-tax-component/edit-tax-component.component.html
- src/app/products/manage-tax-components/edit-tax-component/edit-tax-component.component.scss
- src/app/products/manage-tax-components/edit-tax-component/edit-tax-component.component.spec.ts
- src/app/products/manage-tax-components/edit-tax-component/edit-tax-component.component.ts
- src/app/products/manage-tax-components/view-tax-component/view-tax-component.component.html
- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
> feat: add edit tax component

- src/app/shared/change-password-dialog/change-password-dialog.component.html
- src/app/shared/change-password-dialog/change-password-dialog.component.spec.ts
- src/app/shared/change-password-dialog/change-password-dialog.component.ts
- src/app/shared/shared.module.ts
- src/app/users/users.service.ts
- src/app/users/view-user/view-user.component.html
- src/app/users/view-user/view-user.component.ts
Modal form for changing user password created.
#657 
> feat: add change user password model

- src/app/self-service/users/user.service.ts
- src/app/self-service/users/users.component.html
- src/app/self-service/users/view-user/view-user.component.html
- src/app/self-service/users/view-user/view-user.component.ts
- src/app/shared/change-password-dialog/change-password-dialog.component.html
Modal for password changing of the users.
#669 
> feat: self service change user password

- src/app/organization/loan-provisioning-criteria/loan-provisioning-criteria.component.html
- src/app/organization/loan-provisioning-criteria/loan-provisioning-criteria.component.ts
- src/app/organization/loan-provisioning-criteria/loan-provisioning-criteria.resolver.ts
- src/app/organization/loan-provisioning-criteria/loan-provisioning-criterias.resolver.ts
- src/app/organization/loan-provisioning-criteria/view-loan-provisioning-criteria/view-loan-provisioning-criteria.component.html
- src/app/organization/loan-provisioning-criteria/view-loan-provisioning-criteria/view-loan-provisioning-criteria.component.scss
- src/app/organization/loan-provisioning-criteria/view-loan-provisioning-criteria/view-loan-provisioning-criteria.component.spec.ts
- src/app/organization/loan-provisioning-criteria/view-loan-provisioning-criteria/view-loan-provisioning-criteria.component.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
Created ViewLoanProvisioningCriteria component to view selected criteria.
#571 
> feat: add loan provisioning page

- src/app/products/charges/charges-template.resolver.ts
- src/app/products/charges/edit-charge/edit-charge.component.html
- src/app/products/charges/edit-charge/edit-charge.component.spec.ts
- src/app/products/charges/edit-charge/edit-charge.component.ts
- src/app/products/charges/view-charge/view-charge.component.html
- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
Created Edit Charge component for editing charges.
#586
> feat: add edit charge component 

- src/app/accounting/accounting.component.html
- src/app/accounting/accounting.module.ts
- src/app/directives/directives.module.ts
- src/app/directives/has-permission/has-permission.directive.spec.ts
- src/app/directives/has-permission/has-permission.directive.ts
Initialized Directives Module and Developed Has-permission structural directive.
Refactored `accounting.component.html` to use the has-permission directive.
#721 
> feat: add has-permission structural directive

- src/app/groups/common-resolvers/group-notes.resolver.ts
- src/app/groups/groups-routing.module.ts
- src/app/groups/groups-view/groups-view.component.html
- src/app/groups/groups-view/notes-tab/notes-tab.component.html
- src/app/groups/groups-view/notes-tab/notes-tab.component.scss
- src/app/groups/groups-view/notes-tab/notes-tab.component.spec.ts
- src/app/groups/groups-view/notes-tab/notes-tab.component.ts
- src/app/groups/groups.module.ts
- src/app/groups/groups.service.ts
Developed the groups view page notes tab.
#778 
> feat: add groups view page (notes-tab)

- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- src/app/organization/tellers/cashier.resolver.ts
- src/app/organization/tellers/tellers.component.html
- src/app/organization/tellers/view-cashier/view-cashier.component.html
- src/app/organization/tellers/view-cashier/view-cashier.component.scss
- src/app/organization/tellers/view-cashier/view-cashier.component.spec.ts
- src/app/organization/tellers/view-cashier/view-cashier.component.ts
View Cashier component created.
#761 
> feat: add view cashier component

- src/app/organization/holidays/holiday.resolver.ts
- src/app/organization/holidays/holidays.component.html
- src/app/organization/holidays/view-holidays/view-holidays.component.html
- src/app/organization/holidays/view-holidays/view-holidays.component.scss
- src/app/organization/holidays/view-holidays/view-holidays.component.spec.ts
- src/app/organization/holidays/view-holidays/view-holidays.component.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
Component for viewing holidays created.
#749 
> feat: add view holiday component

- src/app/centers/centers-routing.module.ts
- src/app/centers/centers-view/centers-view.component.html
- src/app/centers/centers-view/centers-view.component.ts
- src/app/centers/centers-view/datatable-tab/datatable-tab.component.html
- src/app/centers/centers-view/datatable-tab/datatable-tab.component.spec.ts
- src/app/centers/centers-view/datatable-tab/datatable-tab.component.ts
- src/app/centers/centers-view/datatable-tab/multi-row/multi-row.component.html
- src/app/centers/centers-view/datatable-tab/multi-row/multi-row.component.scss
- src/app/centers/centers-view/datatable-tab/multi-row/multi-row.component.spec.ts
- src/app/centers/centers-view/datatable-tab/multi-row/multi-row.component.ts
- src/app/centers/centers-view/datatable-tab/single-row/single-row.component.html
- src/app/centers/centers-view/datatable-tab/single-row/single-row.component.scss
- src/app/centers/centers-view/datatable-tab/single-row/single-row.component.spec.ts
- src/app/centers/centers-view/datatable-tab/single-row/single-row.component.ts
- src/app/centers/centers.module.ts
- src/app/centers/centers.service.ts
- src/app/centers/common-resolvers/center-datatable.resolver.ts
- src/app/centers/common-resolvers/center-datatables.resolver.ts
1. Implemented Single Row and Multiple Row Datatables
2. Added permissions wherever required
3. Some styling changes
#775 #798 
> feat: add center view page (datatable-tabs)

- src/app/directives/has-permission/has-permission.directive.ts
Modifies code to clear template beforehand to prevent template repetition OnChanges.
#794 
> fix: has-permission directive for OnChanges

- src/app/users/edit-user/edit-user.component.html
- src/app/users/edit-user/edit-user.component.scss
- src/app/users/edit-user/edit-user.component.spec.ts
- src/app/users/edit-user/edit-user.component.ts
- src/app/users/users-routing.module.ts
- src/app/users/users.module.ts
- src/app/users/users.service.ts
- src/app/users/view-user/view-user.component.html
- added the edit user component
- updated routing path for the viewing of the user from /users/id to /users/view/id. The user edit component can be found at /users/view/id/edit.
#585
> feat: add edit user component

- README.md
- src/environments/environment.prod.ts
- src/environments/environment.ts
Update server details leveraging latest fineract backend to support #742
#666 
NA
> fix: update server details

- src/app/core/authentication/authentication.service.ts
related to https://issues.apache.org/jira/browse/FINERACT-726
#741
NA
> fix: login to current versions of Fineract API (#741)

- src/app/clients/clients-routing.module.ts
- src/app/clients/clients-view/charges-overview/charge-overview.resolver.ts
- src/app/clients/clients-view/charges-overview/charges-overview.component.html
- src/app/clients/clients-view/charges-overview/charges-overview.component.scss
- src/app/clients/clients-view/charges-overview/charges-overview.component.spec.ts
- src/app/clients/clients-view/charges-overview/charges-overview.component.ts
- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
Description
Component to view client charges completed.
Related issues and discussion
#680 
Screenshots, if any
Checklist
> feat: view client charge overview 

- src/app/pipes/status-lookup.pipe.ts
Removes the duplicate element from the `status-lookup.pipe.ts` file.
#805 
> fix: remove duplicate element in status-lookup file

- src/app/products/manage-tax-groups/manage-tax-groups.component.html
- src/app/products/manage-tax-groups/manage-tax-groups.component.scss
- src/app/products/manage-tax-groups/tax-group.resolver.ts
- src/app/products/manage-tax-groups/view-tax-group/view-tax-group.component.html
- src/app/products/manage-tax-groups/view-tax-group/view-tax-group.component.scss
- src/app/products/manage-tax-groups/view-tax-group/view-tax-group.component.spec.ts
- src/app/products/manage-tax-groups/view-tax-group/view-tax-group.component.ts
- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
View Tax Group component created.
#587 
> feat: add view tax group

- src/app/organization/holidays/holidays.component.ts
Remove deleted holidays from manage holidays list page.
#797 
> fix: delete holiday visible in holidays list page

- src/app/reports/common-models/chart-data.model.ts
- src/app/reports/common-models/report-parameter.model.ts
- src/app/reports/common-models/select-option.model.ts
- src/app/reports/reports-routing.module.ts
- src/app/reports/reports.component.html
- src/app/reports/reports.module.ts
- src/app/reports/reports.service.ts
- src/app/reports/run-report/chart/chart.component.html
- src/app/reports/run-report/chart/chart.component.spec.ts
- src/app/reports/run-report/chart/chart.component.ts
- src/app/reports/run-report/pentaho/pentaho.component.html
- src/app/reports/run-report/pentaho/pentaho.component.spec.ts
- src/app/reports/run-report/pentaho/pentaho.component.ts
- src/app/reports/run-report/run-report.component.html
- src/app/reports/run-report/run-report.component.scss
- src/app/reports/run-report/run-report.component.spec.ts
- src/app/reports/run-report/run-report.component.ts
- src/app/reports/run-report/run-report.resolver.ts
- src/app/reports/run-report/table-and-sms/table-and-sms.component.html
- src/app/reports/run-report/table-and-sms/table-and-sms.component.scss
- src/app/reports/run-report/table-and-sms/table-and-sms.component.spec.ts
- src/app/reports/run-report/table-and-sms/table-and-sms.component.ts
- src/typings.d.ts
Added run report component which output's data for report categories "Table", "SMS", "Chart" and "Pentaho".
Declared `chart.js` module in `typings.d.ts` as it is an untyped .js module.
Commented _community_ app code for this component explaining corresponding _web_ app code:
https://gist.github.com/karantakalkar/c7cee52de34698b4f45abe9f51ae42c6
**Sample Cases:**
**SMS**
> Prospective Clients
**Table**
>  Client Listing, Txnrunning balances (Decimal choice implementation) 
**Charts:** 
> Test Chart, yyyy
**Pentaho**
> Balance Sheet, Income Statement, Balance Outstanding
#233
**Pentaho Reports** 
| Form |
| --- |
| ![Screenshot from 2020-05-27 13-42-46](https://user-images.githubusercontent.com/54709463/82995606-6eb5e200-a021-11ea-8d52-2f8c60241fb3.png) |
| HTML | XLSX Sheet  | PDF |
| --- …
> feat: add create report page

- src/app/home/dashboard/amount-collected-pie/amount-collected-pie.component.html
- src/app/home/dashboard/amount-collected-pie/amount-collected-pie.component.scss
- src/app/home/dashboard/amount-collected-pie/amount-collected-pie.component.spec.ts
- src/app/home/dashboard/amount-collected-pie/amount-collected-pie.component.ts
- src/app/home/dashboard/amount-disbursed-pie/amount-disbursed-pie.component.html
- src/app/home/dashboard/amount-disbursed-pie/amount-disbursed-pie.component.scss
- src/app/home/dashboard/amount-disbursed-pie/amount-disbursed-pie.component.spec.ts
- src/app/home/dashboard/amount-disbursed-pie/amount-disbursed-pie.component.ts
- src/app/home/dashboard/client-trends-bar/client-trends-bar.component.html
- src/app/home/dashboard/client-trends-bar/client-trends-bar.component.scss
- src/app/home/dashboard/client-trends-bar/client-trends-bar.component.spec.ts
- src/app/home/dashboard/client-trends-bar/client-trends-bar.component.ts
- src/app/home/dashboard/dashboard.component-theme.scss
- src/app/home/dashboard/dashboard.component.html
- src/app/home/dashboard/dashboard.component.scss
- src/app/home/dashboard/dashboard.component.ts
- src/app/home/home-routing.module.ts
- src/app/home/home.module.ts
- src/app/home/home.service.spec.ts
- src/app/home/home.service.ts
- src/app/pipes/pipes.module.ts
- src/app/pipes/url-to-string.pipe.spec.ts
- src/app/pipes/url-to-string.pipe.ts
- src/app/shared/icons.module.ts
- src/app/web-app.component.ts
- src/theme/custom/denim-yellowgreen.scss
- src/theme/custom/pictonblue-yellowgreen.scss
Developed the Dashboard Component.
#808 
> feat: add dashboard component

- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
- src/app/products/share-products/dividends-share-product/dividends.component.html
- src/app/products/share-products/dividends-share-product/dividends.component.scss
- src/app/products/share-products/dividends-share-product/dividends.component.spec.ts
- src/app/products/share-products/dividends-share-product/dividends.components.ts
- src/app/products/share-products/dividends-share-product/dividends.resolver.ts
- src/app/products/share-products/view-share-product/view-share-product.component.html
Added view for dividends in share product.
Fixes #769
> feat: add dividends list page

- src/app/system/entity-to-entity-mapping/entity-to-entity-mapping.component.html
- src/app/system/entity-to-entity-mapping/entity-to-entity-mapping.component.spec.ts
- src/app/system/entity-to-entity-mapping/entity-to-entity-mapping.component.ts
- src/app/system/entity-to-entity-mapping/entity-to-entity-mapping.resolver.ts
- src/app/system/system-routing.module.ts
- src/app/system/system.component.html
- src/app/system/system.module.ts
- src/app/system/system.service.ts
Added Entity to Entity Mapping List with the view of the particular clicked mapping entity.
#485 
> feat: add entity to entity mapping

- src/app/system/entity-to-entity-mapping/entity-to-entity-mapping.component.html
- src/app/system/entity-to-entity-mapping/entity-to-entity-mapping.component.scss
- src/app/system/entity-to-entity-mapping/entity-to-entity-mapping.component.ts
- src/app/system/system.module.ts
- src/app/system/system.service.ts
Adds the feature to add new entity mapping based on the relation id.
Follows: #613 
#767 
> feat: add new entity mapping

- src/app/system/entity-to-entity-mapping/entity-to-entity-mapping.component.html
- src/app/system/entity-to-entity-mapping/entity-to-entity-mapping.component.ts
- src/app/system/system.service.ts
- Add edit entity to entity mapping
- Add delete entity to entity mapping
Follows: #822
#768
> feat: add edit entity mapping

- src/app/loans/common-resolvers/loan-notes-resolver.ts
- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/general-tab/general-tab.component.scss
- src/app/loans/loans-view/loans-view.component.html
- src/app/loans/loans-view/notes-tab/notes-tab.component.html
- src/app/loans/loans-view/notes-tab/notes-tab.component.scss
- src/app/loans/loans-view/notes-tab/notes-tab.component.spec.ts
- src/app/loans/loans-view/notes-tab/notes-tab.component.ts
- src/app/loans/loans.module.ts
- src/app/loans/loans.service.ts
Add Notes Tab for the view loan
- User can add, edit and delete notes
- Enabled permission directive for edit notes
- Implemented the form-dialog for the edit notes option 
Needs to be merged after #661 
#815 
> feat: add view loans (notes tab)

- src/app/loans/common-resolvers/loan-details-charges.resolver.ts
- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/charges-tab/charges-tab.component.html
- src/app/loans/loans-view/charges-tab/charges-tab.component.scss
- src/app/loans/loans-view/charges-tab/charges-tab.component.spec.ts
- src/app/loans/loans-view/charges-tab/charges-tab.component.ts
- src/app/loans/loans-view/loans-view.component.html
- src/app/loans/loans.module.ts
- src/app/loans/loans.service.ts
Add Charges Tab for the view loans
- User can view the charges data, if available
Needs to be merged after PR #819
#816 
> feat: add view loan (charges tab)

- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/loans-view.component.html
- src/app/loans/loans-view/original-schedule-tab/original-schedule-tab.component.html
- src/app/loans/loans-view/original-schedule-tab/original-schedule-tab.component.scss
- src/app/loans/loans-view/original-schedule-tab/original-schedule-tab.component.spec.ts
- src/app/loans/loans-view/original-schedule-tab/original-schedule-tab.component.ts
- src/app/loans/loans.module.ts
Add Original Schedule Tab for the view loans
#812 
> feat: add view loan (original schedule tab)

- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- src/app/organization/sms-campaigns/common-resolvers/sms-campaign.resolver.ts
- src/app/organization/sms-campaigns/common-resolvers/sms-campaigns.resolver.ts
- src/app/organization/sms-campaigns/sms-campaigns.component.html
- src/app/organization/sms-campaigns/view-campaign/view-campaign.component.html
- src/app/organization/sms-campaigns/view-campaign/view-campaign.component.scss
- src/app/organization/sms-campaigns/view-campaign/view-campaign.component.spec.ts
- src/app/organization/sms-campaigns/view-campaign/view-campaign.component.ts
- Developed View SMS Campaign Page
- Enabled Permissions
#563 
| Active Campaign |
| --- |
| ![Screenshot from 2020-06-01 20-18-11](https://user-images.githubusercontent.com/54709463/83427207-fea6c200-a44d-11ea-8327-9507e8369c0c.png) |
| Pending Campaign | Closed Campaign |
| --- | --- |
| ![Screenshot from 2020-06-01 20-16-39](https://user-images.githubusercontent.com/54709463/83427283-1da55400-a44e-11ea-844b-3c3dda39c3b7.png) | ![Screenshot from 2020-06-01 21-07-09](https://user-images.githubusercontent.com/54709463/83427317-2d249d00-a44e-11ea-9373-1db90008fc2a.png) |
| SMS Tab Example (Pre) | SMS Tab Example (Post) |
| --- | --- |
| ![Screenshot from 2020-06-01 21-28-40](https://user-images.githubusercontent.com/54709463/83427826-f8fdac00-a44e-11ea-9da4-a637909c4e79.png) | ![Screenshot …
> feat: add view sms campaign page

- src/app/pipes/url-to-string.pipe.ts
> fix: URL to String pipe to decode URLs

- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/loans-view.component.html
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.html
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.scss
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.spec.ts
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.ts
- src/app/loans/loans.module.ts
Add Repayment schedule tab for the loans page 
#813 
> feat: add view loan (repayment schedule tab)

- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/loans-view.component.html
- src/app/loans/loans-view/transactios-tab/transactios-tab.component.html
- src/app/loans/loans-view/transactios-tab/transactios-tab.component.scss
- src/app/loans/loans-view/transactios-tab/transactios-tab.component.spec.ts
- src/app/loans/loans-view/transactios-tab/transactios-tab.component.ts
- src/app/loans/loans.module.ts
Add Transactions tab for the loans page
#814 
**View Accruals**
**Hide Accruals**
> feat: add view loan (transactions tab)

- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/button-config.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.scss
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.spec.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans-view/loan-account-actions/loans-account-close/loans-account-close.component.html
- src/app/loans/loans-view/loan-account-actions/loans-account-close/loans-account-close.component.spec.ts
- src/app/loans/loans-view/loan-account-actions/loans-account-close/loans-account-close.component.ts
- src/app/loans/loans-view/loans-view.component.html
- src/app/loans/loans-view/loans-view.component.ts
- src/app/loans/loans-view/notes-tab/notes-tab.component.ts
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.ts
- src/app/loans/loans-view/transactios-tab/transactios-tab.component.ts
- src/app/loans/loans.module.ts
- src/app/loans/loans.service.ts
This PR implements:
- Basic setup of routes for the action buttons
- Add close loan account
- Basic refactoring of the code
#849 
> feat: add loan button (close action)

- src/app/savings/common-resolvers/savings-datatable.resolver.ts
- src/app/savings/common-resolvers/savings-datatables.resolver.ts
- src/app/savings/savings-account-view/datatable-tabs/datatable-tabs.component.html
- src/app/savings/savings-account-view/datatable-tabs/datatable-tabs.component.spec.ts
- src/app/savings/savings-account-view/datatable-tabs/datatable-tabs.component.ts
- src/app/savings/savings-account-view/datatable-tabs/multi-row/multi-row.component.html
- src/app/savings/savings-account-view/datatable-tabs/multi-row/multi-row.component.scss
- src/app/savings/savings-account-view/datatable-tabs/multi-row/multi-row.component.spec.ts
- src/app/savings/savings-account-view/datatable-tabs/multi-row/multi-row.component.ts
- src/app/savings/savings-account-view/datatable-tabs/single-row/single-row.component.html
- src/app/savings/savings-account-view/datatable-tabs/single-row/single-row.component.scss
- src/app/savings/savings-account-view/datatable-tabs/single-row/single-row.component.spec.ts
- src/app/savings/savings-account-view/datatable-tabs/single-row/single-row.component.ts
- src/app/savings/savings-account-view/savings-account-view.component.html
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings-routing.module.ts
- src/app/savings/savings.module.ts
- src/app/savings/savings.service.ts
Developed Savings single and multi row datatables.
#863, #864 
| Single Row Data Table | Edit Data Table |
| --- | --- |
| ![Screenshot from 2020-06-11 18-48-51](https://user-images.githubusercontent.com/54709463/84390031-9bb6e700-ac14-11ea-9df2-3e5f74b627cf.png) | ![Screenshot from 2020-06-11 18-49-00](https://user-images.githubusercontent.com/54709463/84390054-a70a1280-ac14-11ea-9ea6-42669a6dd4ac.png) |
| Multi Row Data Table | Add Row |
| --- | --- |
| ![Screenshot from 2020-06-11 18-48-27](https://user-images.githubusercontent.com/54709463/84390102-b9844c00-ac14-11ea-97c6-20c062ae713f.png) | ![Screenshot from 2020-06-11 18-48-37](https://user-images.githubusercontent.com/54709463/84390158-d02aa300-ac14-11ea-88e1-83bc9b772fd8.png) |
Please make sure these boxes are checked before …
> feat: add savings accounts datatables

- src/app/loans/common-resolvers/loan-action-button-resolver.ts
- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/loan-account-actions/assign-loan-officer/assign-loan-officer.component.html
- src/app/loans/loans-view/loan-account-actions/assign-loan-officer/assign-loan-officer.component.spec.ts
- src/app/loans/loans-view/loan-account-actions/assign-loan-officer/assign-loan-officer.component.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans-view/loan-account-actions/undo-approval/undo-approval.component.ts
- src/app/loans/loans-view/loans-view.component.ts
- src/app/loans/loans.module.ts
- src/app/loans/loans.service.ts
- src/environments/environment.ts
This PR implements:
- Assign Loan Officer Action
- Change Loan Officer Action
#248 
> feat: add loan button (assign/change loan officer)

- src/app/loans/loans-view/loan-account-actions/assign-loan-officer/assign-loan-officer.component.ts
- src/app/loans/loans-view/loan-account-actions/foreclosure/foreclosure.component.html
- src/app/loans/loans-view/loan-account-actions/foreclosure/foreclosure.component.spec.ts
- src/app/loans/loans-view/loan-account-actions/foreclosure/foreclosure.component.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans.module.ts
- src/app/loans/loans.service.ts
Adds the foreclosure action
#244 
> feat: add loan button (foreclosure)

- src/app/loans/common-resolvers/loan-action-button.resolver.ts
- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/loan-account-actions/foreclosure/foreclosure.component.html
- src/app/loans/loans-view/loan-account-actions/foreclosure/foreclosure.component.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans-view/loan-account-actions/loans-account-close/loans-account-close.component.ts
- src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.html
- src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.scss
- src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.spec.ts
- src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.ts
- src/app/loans/loans-view/loan-account-actions/prepay-loan/prepay-loan.component.html
- src/app/loans/loans-view/loan-account-actions/prepay-loan/prepay-loan.component.scss
- src/app/loans/loans-view/loan-account-actions/prepay-loan/prepay-loan.component.spec.ts
- src/app/loans/loans-view/loan-account-actions/prepay-loan/prepay-loan.component.ts
- src/app/loans/loans.module.ts
- src/app/loans/loans.service.ts
- Add Prepay Loan Action button
- Add Repayment Loan Action button
#243 
#242
| Show Payment details in collapsed view | Show Payment details in expanded view |
| --- | --- |
| ![Screenshot from 2020-06-13 15-00-54](https://user-images.githubusercontent.com/36980003/84566294-9df08100-ad8d-11ea-85be-84b9d455a82f.png) | ![Screenshot from 2020-06-13 15-49-41](https://user-images.githubusercontent.com/36980003/84566298-a0eb7180-ad8d-11ea-8036-3672a9b93def.png) |
| Show Payment details in collapsed view | Show Payment details in expanded view |
| --- | --- |
| ![Screenshot from 2020-06-13 16-29-02](https://user-images.githubusercontent.com/36980003/84567199-ae582a00-ad94-11ea-80ce-fe0e605fff4f.png) | ![Screenshot from 2020-06-13 16-29-10](https://user-images.githubusercontent.com/36980003/84567 …
> feat: add loan action button

- src/app/loans/common-resolvers/loan-action-button.resolver.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans-view/loan-account-actions/waive-interest/waive-interest.component.html
- src/app/loans/loans-view/loan-account-actions/waive-interest/waive-interest.component.spec.ts
- src/app/loans/loans-view/loan-account-actions/waive-interest/waive-interest.component.ts
- src/app/loans/loans.module.ts
Component to waive loan interested added.
#846 
> feat: add waive interest component

- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/floating-interest-rates/floating-interest-rates.component.html
- src/app/loans/loans-view/floating-interest-rates/floating-interest-rates.component.scss
- src/app/loans/loans-view/floating-interest-rates/floating-interest-rates.component.spec.ts
- src/app/loans/loans-view/floating-interest-rates/floating-interest-rates.component.ts
- src/app/loans/loans-view/loans-view.component.html
- src/app/loans/loans.module.ts
Add Floating Interest Rates Tab
#871 
> feat: add view loan page (floating interest rates tab)

- src/app/loans/common-resolvers/loan-action-button.resolver.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans-view/loan-account-actions/write-off-page/write-off-page.component.html
- src/app/loans/loans-view/loan-account-actions/write-off-page/write-off-page.component.spec.ts
- src/app/loans/loans-view/loan-account-actions/write-off-page/write-off-page.component.ts
- src/app/loans/loans.module.ts
Write Off page component added.
#847 
> feat: add write off page

- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/loan-account-actions/write-off-page/write-off-page.component.ts
- src/app/loans/loans-view/loan-tranche-details/loan-tranche-details.component.html
- src/app/loans/loans-view/loan-tranche-details/loan-tranche-details.component.scss
- src/app/loans/loans-view/loan-tranche-details/loan-tranche-details.component.spec.ts
- src/app/loans/loans-view/loan-tranche-details/loan-tranche-details.component.ts
- src/app/loans/loans-view/loans-view.component.html
- src/app/loans/loans.module.ts
Add Loan tranche details tab
#870 
> feat: add view loan page (loan tranche details tab)

- src/app/clients/clients-view/clients-view.component.html
- src/app/shared/icons.module.ts
- src/app/shares/common-resolvers/shares-account-template.resolver.ts
- src/app/shares/create-shares-account/create-shares-account.component.html
- src/app/shares/create-shares-account/create-shares-account.component.spec.ts
- src/app/shares/create-shares-account/create-shares-account.component.ts
- src/app/shares/shares-account-stepper/shares-account-charges-step/shares-account-charges-step.component.html
- src/app/shares/shares-account-stepper/shares-account-charges-step/shares-account-charges-step.component.scss
- src/app/shares/shares-account-stepper/shares-account-charges-step/shares-account-charges-step.component.spec.ts
- src/app/shares/shares-account-stepper/shares-account-charges-step/shares-account-charges-step.component.ts
- src/app/shares/shares-account-stepper/shares-account-details-step/shares-account-details-step.component.html
- src/app/shares/shares-account-stepper/shares-account-details-step/shares-account-details-step.component.spec.ts
- src/app/shares/shares-account-stepper/shares-account-details-step/shares-account-details-step.component.ts
- src/app/shares/shares-account-stepper/shares-account-preview-step/shares-account-preview-step.component.html
- src/app/shares/shares-account-stepper/shares-account-preview-step/shares-account-preview-step.component.scss
- src/app/shares/shares-account-stepper/shares-account-preview-step/shares-account-preview-step.component.spec.ts
- src/app/shares/shares-account-stepper/shares-account-preview-step/shares-account-preview-step.component.ts
- src/app/shares/shares-account-stepper/shares-account-terms-step/shares-account-terms-step.component.html
- src/app/shares/shares-account-stepper/shares-account-terms-step/shares-account-terms-step.component.scss
- src/app/shares/shares-account-stepper/shares-account-terms-step/shares-account-terms-step.component.spec.ts
- src/app/shares/shares-account-stepper/shares-account-terms-step/shares-account-terms-step.component.ts
- src/app/shares/shares-routing.module.ts
- src/app/shares/shares.module.ts
- src/app/shares/shares.service.ts
Developed Create Share Account Page
#223
| Details Step | Charges Step |
| --- | --- |
| ![Screenshot from 2020-06-15 20-06-05](https://user-images.githubusercontent.com/54709463/84670971-6e37a980-af44-11ea-8fe9-f25dddea8863.png) | ![Screenshot from 2020-06-15 20-06-35](https://user-images.githubusercontent.com/54709463/84671082-8e676880-af44-11ea-85c4-b7f4d2680dc9.png)|
| Terms Step | Preview Step |
| --- | --- |
| ![Screenshot from 2020-06-15 20-17-42](https://user-images.githubusercontent.com/54709463/84671749-5ca2d180-af45-11ea-8b2d-d0e78d36ee61.png) | ![Screenshot from 2020-06-15 20-07-08](https://user-images.githubusercontent.com/54709463/84671171-ab03a080-af44-11ea-8808-641b8c512ded.png) |
> feat: add create shares account page

- src/app/shares/common-resolvers/share-account-and-template.resolver.ts
- src/app/shares/edit-shares-account/edit-shares-account.component.html
- src/app/shares/edit-shares-account/edit-shares-account.component.spec.ts
- src/app/shares/edit-shares-account/edit-shares-account.component.ts
- src/app/shares/shares-account-stepper/shares-account-charges-step/shares-account-charges-step.component.ts
- src/app/shares/shares-account-stepper/shares-account-details-step/shares-account-details-step.component.ts
- src/app/shares/shares-account-stepper/shares-account-preview-step/shares-account-preview-step.component.html
- src/app/shares/shares-account-stepper/shares-account-terms-step/shares-account-terms-step.component.ts
- src/app/shares/shares-account-view/shares-account-view.component.html
- src/app/shares/shares-account-view/shares-account-view.component.ts
- src/app/shares/shares-account-view/shares-buttons.config.ts
- src/app/shares/shares-routing.module.ts
- src/app/shares/shares.module.ts
- src/app/shares/shares.service.ts
Developed Edit Shares Account Page.
#880 
> feat: add edit share account page

- src/app/clients/clients-view/clients-view.component.html
- src/app/savings/common-resolvers/savings-account-template.resolver.ts
- src/app/savings/create-savings-account/create-savings-account.component.html
- src/app/savings/create-savings-account/create-savings-account.component.spec.ts
- src/app/savings/create-savings-account/create-savings-account.component.ts
- src/app/savings/savings-account-stepper/savings-account-charges-step/savings-account-charges-step.component.html
- src/app/savings/savings-account-stepper/savings-account-charges-step/savings-account-charges-step.component.scss
- src/app/savings/savings-account-stepper/savings-account-charges-step/savings-account-charges-step.component.spec.ts
- src/app/savings/savings-account-stepper/savings-account-charges-step/savings-account-charges-step.component.ts
- src/app/savings/savings-account-stepper/savings-account-details-step/savings-account-details-step.component.html
- src/app/savings/savings-account-stepper/savings-account-details-step/savings-account-details-step.component.spec.ts
- src/app/savings/savings-account-stepper/savings-account-details-step/savings-account-details-step.component.ts
- src/app/savings/savings-account-stepper/savings-account-preview-step/savings-account-preview-step.component.html
- src/app/savings/savings-account-stepper/savings-account-preview-step/savings-account-preview-step.component.scss
- src/app/savings/savings-account-stepper/savings-account-preview-step/savings-account-preview-step.component.spec.ts
- src/app/savings/savings-account-stepper/savings-account-preview-step/savings-account-preview-step.component.ts
- src/app/savings/savings-account-stepper/savings-account-terms-step/savings-account-terms-step.component.html
- src/app/savings/savings-account-stepper/savings-account-terms-step/savings-account-terms-step.component.scss
- src/app/savings/savings-account-stepper/savings-account-terms-step/savings-account-terms-step.component.spec.ts
- src/app/savings/savings-account-stepper/savings-account-terms-step/savings-account-terms-step.component.ts
- src/app/savings/savings-routing.module.ts
- src/app/savings/savings.module.ts
- src/app/savings/savings.service.ts
- src/app/shares/shares-account-stepper/shares-account-charges-step/shares-account-charges-step.component.ts
- src/app/shares/shares-account-stepper/shares-account-preview-step/shares-account-preview-step.component.html
-  Developed create savings account page
- Refactored shares charges step 
#882 
| Details Step | Charges Step |
| --- | --- |
|![Screenshot from 2020-06-19 16-10-04](https://user-images.githubusercontent.com/54709463/85148868-427f3100-b26e-11ea-9d2d-a69dbcd46764.png) | ![Screenshot from 2020-06-19 18-31-47](https://user-images.githubusercontent.com/54709463/85148895-4ca12f80-b26e-11ea-887c-60cbb2ea54a1.png) |
| Terms Step | Preview Step |
| --- | --- |
| ![Screenshot from 2020-06-19 16-11-39](https://user-images.githubusercontent.com/54709463/85148952-5f1b6900-b26e-11ea-8f6d-ea1dbdff8dad.png) | ![Screenshot from 2020-06-19 18-32-15](https://user-images.githubusercontent.com/54709463/85148981-6773a400-b26e-11ea-9f6d-d2bd53cf991d.png) |
Please make sure these boxes are checked before …
> feat: add create savings account page

- src/app/savings/common-resolvers/savings-account-and-template.resolver.ts
- src/app/savings/edit-savings-account/edit-savings-account.component.html
- src/app/savings/edit-savings-account/edit-savings-account.component.spec.ts
- src/app/savings/edit-savings-account/edit-savings-account.component.ts
- src/app/savings/savings-account-stepper/savings-account-charges-step/savings-account-charges-step.component.html
- src/app/savings/savings-account-stepper/savings-account-charges-step/savings-account-charges-step.component.ts
- src/app/savings/savings-account-stepper/savings-account-details-step/savings-account-details-step.component.ts
- src/app/savings/savings-account-stepper/savings-account-preview-step/savings-account-preview-step.component.html
- src/app/savings/savings-account-stepper/savings-account-terms-step/savings-account-terms-step.component.ts
- src/app/savings/savings-account-view/savings-account-view.component.html
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings-account-view/savings-buttons.config.ts
- src/app/savings/savings-routing.module.ts
- src/app/savings/savings.module.ts
- src/app/savings/savings.service.ts
- src/app/shares/shares-account-stepper/shares-account-charges-step/shares-account-charges-step.component.ts
- src/app/shares/shares-account-stepper/shares-account-terms-step/shares-account-terms-step.component.ts
- Developed Edit Savings Account Page
- Refactored Savings and Shares steppers
#222 
> feat: add edit savings account page

- src/app/organization/manage-funds/manage-funds.component.html
- src/app/organization/manage-funds/manage-funds.component.scss
- src/app/organization/manage-funds/manage-funds.component.spec.ts
- src/app/organization/manage-funds/manage-funds.component.ts
- src/app/organization/manage-funds/manage-funds.resolver.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.component.html
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
Developed Manage Funds Component.
#155 
> feat: add manage funds component

- src/app/organization/currencies/currencies.component.html
- src/app/organization/currencies/manage-currencies/manage-currencies.component.html
- src/app/organization/currencies/manage-currencies/manage-currencies.component.scss
- src/app/organization/currencies/manage-currencies/manage-currencies.component.spec.ts
- src/app/organization/currencies/manage-currencies/manage-currencies.component.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
Developed manage currencies component
#152 
> feat: add manage currencies page

- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/shares/shares-account-actions/approve-shares-account/approve-shares-account.component.html
- src/app/shares/shares-account-actions/approve-shares-account/approve-shares-account.component.scss
- src/app/shares/shares-account-actions/approve-shares-account/approve-shares-account.component.spec.ts
- src/app/shares/shares-account-actions/approve-shares-account/approve-shares-account.component.ts
- src/app/shares/shares-account-actions/shares-account-actions.component.html
- src/app/shares/shares-account-actions/shares-account-actions.component.spec.ts
- src/app/shares/shares-account-actions/shares-account-actions.component.ts
- src/app/shares/shares-account-view/shares-account-view.component.ts
- src/app/shares/shares-account-view/shares-buttons.config.ts
- src/app/shares/shares-routing.module.ts
- src/app/shares/shares.module.ts
- src/app/shares/shares.service.ts
- Developed shares approve form
- Created action buttons component
- Refactor indents
#889 
> feat: shares account actions (approve)

- src/app/shares/shares-account-actions/reject-shares-account/reject-shares-account.component.html
- src/app/shares/shares-account-actions/reject-shares-account/reject-shares-account.component.scss
- src/app/shares/shares-account-actions/reject-shares-account/reject-shares-account.component.spec.ts
- src/app/shares/shares-account-actions/reject-shares-account/reject-shares-account.component.ts
- src/app/shares/shares-account-actions/shares-account-actions.component.html
- src/app/shares/shares-account-actions/shares-account-actions.component.ts
- src/app/shares/shares-account-view/shares-account-view.component.html
- src/app/shares/shares-account-view/shares-account-view.component.ts
- src/app/shares/shares.module.ts
Developed shares account reject page
#891 
> feat: shares account actions (reject)

- src/app/shares/shares-account-view/shares-account-view.component.ts
- src/app/shares/shares.service.ts
Developed shares account delete
#893 
> feat: shares account actions (delete)

- src/app/shares/shares-account-actions/close-shares-account/close-shares-account.component.html
- src/app/shares/shares-account-actions/close-shares-account/close-shares-account.component.scss
- src/app/shares/shares-account-actions/close-shares-account/close-shares-account.component.spec.ts
- src/app/shares/shares-account-actions/close-shares-account/close-shares-account.component.ts
- src/app/shares/shares-account-actions/shares-account-actions.component.html
- src/app/shares/shares-account-actions/shares-account-actions.component.ts
- src/app/shares/shares-account-view/shares-account-view.component.ts
- src/app/shares/shares.module.ts
Developed close shares page
#895
> feat: shares account actions (close)

- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/shares/shares-account-actions/activate-shares-account/activate-shares-account.component.html
- src/app/shares/shares-account-actions/activate-shares-account/activate-shares-account.component.scss
- src/app/shares/shares-account-actions/activate-shares-account/activate-shares-account.component.spec.ts
- src/app/shares/shares-account-actions/activate-shares-account/activate-shares-account.component.ts
- src/app/shares/shares-account-actions/shares-account-actions.component.html
- src/app/shares/shares-account-actions/shares-account-actions.component.ts
- src/app/shares/shares-account-view/shares-account-view.component.ts
- src/app/shares/shares.module.ts
Developed shares account activate page.
#897 
> feat: shares account actions (activate)

- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/shares/shares-account-actions/shares-account-actions.component.html
- src/app/shares/shares-account-actions/shares-account-actions.component.ts
- src/app/shares/shares-account-actions/undo-approval-shares-account/undo-approval-shares-account.component.html
- src/app/shares/shares-account-actions/undo-approval-shares-account/undo-approval-shares-account.component.scss
- src/app/shares/shares-account-actions/undo-approval-shares-account/undo-approval-shares-account.component.spec.ts
- src/app/shares/shares-account-actions/undo-approval-shares-account/undo-approval-shares-account.component.ts
- src/app/shares/shares-account-view/shares-account-view.component.ts
- src/app/shares/shares.module.ts
Developed shares undo approval
#899
> feat: shares account actions (undo-approval)

- src/app/shares/shares-account-actions/activate-shares-account/activate-shares-account.component.ts
- src/app/shares/shares-account-actions/apply-shares/apply-shares.component.html
- src/app/shares/shares-account-actions/apply-shares/apply-shares.component.scss
- src/app/shares/shares-account-actions/apply-shares/apply-shares.component.spec.ts
- src/app/shares/shares-account-actions/apply-shares/apply-shares.component.ts
- src/app/shares/shares-account-actions/approve-shares-account/approve-shares-account.component.ts
- src/app/shares/shares-account-actions/close-shares-account/close-shares-account.component.ts
- src/app/shares/shares-account-actions/reject-shares-account/reject-shares-account.component.ts
- src/app/shares/shares-account-actions/shares-account-actions.component.html
- src/app/shares/shares-account-actions/shares-account-actions.component.ts
- src/app/shares/shares-account-actions/undo-approval-shares-account/undo-approval-shares-account.component.html
- src/app/shares/shares-account-actions/undo-approval-shares-account/undo-approval-shares-account.component.ts
- src/app/shares/shares-account-view/shares-account-view.component.ts
- src/app/shares/shares-routing.module.ts
- src/app/shares/shares.module.ts
- Developed apply shares component
- Refactored routing and code
#901 
> feat: shares account actions (apply-shares)

- src/app/shares/shares-account-actions/redeem-shares/redeem-shares.component.html
- src/app/shares/shares-account-actions/redeem-shares/redeem-shares.component.scss
- src/app/shares/shares-account-actions/redeem-shares/redeem-shares.component.spec.ts
- src/app/shares/shares-account-actions/redeem-shares/redeem-shares.component.ts
- src/app/shares/shares-account-actions/shares-account-actions.component.html
- src/app/shares/shares-account-actions/shares-account-actions.component.ts
- src/app/shares/shares-account-view/shares-account-view.component.ts
- src/app/shares/shares.module.ts
Developed redeem shares page
#903 
> feat: shares account actions (redeem-shares)

- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/savings/saving-account-actions/approve-savings-account/approve-savings-account.component.html
- src/app/savings/saving-account-actions/approve-savings-account/approve-savings-account.component.scss
- src/app/savings/saving-account-actions/approve-savings-account/approve-savings-account.component.spec.ts
- src/app/savings/saving-account-actions/approve-savings-account/approve-savings-account.component.ts
- src/app/savings/saving-account-actions/saving-account-actions.component.html
- src/app/savings/saving-account-actions/saving-account-actions.component.ts
- src/app/savings/savings-account-view/savings-account-view.component.html
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings-account-view/savings-buttons.config.ts
- src/app/savings/savings-routing.module.ts
- src/app/savings/savings.module.ts
- src/app/savings/savings.service.ts
- Developed savings approve page
- Refactored the code
#905
> feat: savings account actions (approve)

- src/app/pipes/status-lookup.pipe.ts
- src/app/shares/shares-account-actions/apply-shares/apply-shares.component.ts
- src/app/shares/shares-account-actions/approve-shares/approve-share-dialog/approve-share-dialog.component.html
- src/app/shares/shares-account-actions/approve-shares/approve-share-dialog/approve-share-dialog.component.spec.ts
- src/app/shares/shares-account-actions/approve-shares/approve-share-dialog/approve-share-dialog.component.ts
- src/app/shares/shares-account-actions/approve-shares/approve-shares.component.html
- src/app/shares/shares-account-actions/approve-shares/approve-shares.component.scss
- src/app/shares/shares-account-actions/approve-shares/approve-shares.component.spec.ts
- src/app/shares/shares-account-actions/approve-shares/approve-shares.component.ts
- src/app/shares/shares-account-actions/redeem-shares/redeem-shares.component.ts
- src/app/shares/shares-account-actions/shares-account-actions.component.html
- src/app/shares/shares-account-actions/shares-account-actions.component.ts
- src/app/shares/shares-account-view/shares-account-view.component.ts
- src/app/shares/shares.module.ts
Developed shares approval page
#907 
| Table | Dialog |
| --- | --- |
| ![Screenshot from 2020-06-24 23-47-57](https://user-images.githubusercontent.com/54709463/85612011-169cea80-b676-11ea-96bf-d30b177e33bb.png) | ![Screenshot from 2020-06-24 23-48-09](https://user-images.githubusercontent.com/54709463/85612041-20bee900-b676-11ea-91c9-310e4e0ff73d.png) |
> feat: shares account actions (approve-shares)

- src/app/shares/shares-account-actions/reject-shares/reject-share-dialog/reject-share-dialog.component.html
- src/app/shares/shares-account-actions/reject-shares/reject-share-dialog/reject-share-dialog.component.spec.ts
- src/app/shares/shares-account-actions/reject-shares/reject-share-dialog/reject-share-dialog.component.ts
- src/app/shares/shares-account-actions/reject-shares/reject-shares.component.html
- src/app/shares/shares-account-actions/reject-shares/reject-shares.component.scss
- src/app/shares/shares-account-actions/reject-shares/reject-shares.component.spec.ts
- src/app/shares/shares-account-actions/reject-shares/reject-shares.component.ts
- src/app/shares/shares-account-actions/shares-account-actions.component.html
- src/app/shares/shares-account-actions/shares-account-actions.component.ts
- src/app/shares/shares-account-view/shares-account-view.component.ts
- src/app/shares/shares-account-view/shares-buttons.config.ts
- src/app/shares/shares.module.ts
Developed reject shares page
#909
| Table | Dialog |
| --- | --- |
| ![Screenshot from 2020-06-25 03-18-48](https://user-images.githubusercontent.com/54709463/85632017-27f4ef80-b694-11ea-8ff1-c95b91c75bdd.png) | ![Screenshot from 2020-06-25 03-28-42](https://user-images.githubusercontent.com/54709463/85632028-2cb9a380-b694-11ea-9b74-8dc220b0b97b.png) |
> feat: shares account actions (reject-shares)

- src/app/savings/saving-account-actions/reject-savings-account/reject-savings-account.component.html
- src/app/savings/saving-account-actions/reject-savings-account/reject-savings-account.component.scss
- src/app/savings/saving-account-actions/reject-savings-account/reject-savings-account.component.spec.ts
- src/app/savings/saving-account-actions/reject-savings-account/reject-savings-account.component.ts
- src/app/savings/saving-account-actions/saving-account-actions.component.html
- src/app/savings/saving-account-actions/saving-account-actions.component.ts
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings.module.ts
Developed reject savings page
#911 
> feat: savings account actions (reject)

- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings.service.ts
> feat: savings account actions (delete)

- src/app/savings/saving-account-actions/saving-account-actions.component.html
- src/app/savings/saving-account-actions/saving-account-actions.component.ts
- src/app/savings/saving-account-actions/withdraw-savings-account/withdraw-savings-account.component.html
- src/app/savings/saving-account-actions/withdraw-savings-account/withdraw-savings-account.component.scss
- src/app/savings/saving-account-actions/withdraw-savings-account/withdraw-savings-account.component.spec.ts
- src/app/savings/saving-account-actions/withdraw-savings-account/withdraw-savings-account.component.ts
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings.module.ts
Developed savings withdraw page
#915
> feat: savings account actions (withdraw)

- src/app/system/configure-maker-checker-tasks/configure-maker-checker-tasks.component.html
- src/app/system/configure-maker-checker-tasks/configure-maker-checker-tasks.component.scss
- src/app/system/configure-maker-checker-tasks/configure-maker-checker-tasks.component.spec.ts
- src/app/system/configure-maker-checker-tasks/configure-maker-checker-tasks.component.ts
- src/app/system/configure-maker-checker-tasks/configure-maker-checker-tasks.resolver.ts
- src/app/system/system-routing.module.ts
- src/app/system/system.component.html
- src/app/system/system.module.ts
- src/app/system/system.service.ts
Add feature of displaying all the maker checker configuration, also allows the officer to edit various permissions.
#184
> feat: add view, edit configure maker checker component

- src/app/loans/common-resolvers/loan-action-button.resolver.ts
- src/app/loans/loans-view/loan-account-actions/close-as-rescheduled/close-as-rescheduled.component.html
- src/app/loans/loans-view/loan-account-actions/close-as-rescheduled/close-as-rescheduled.component.spec.ts
- src/app/loans/loans-view/loan-account-actions/close-as-rescheduled/close-as-rescheduled.component.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans-view/loans-view.component.ts
- src/app/loans/loans.module.ts
- Add close as rescheduled action
#848 
> feat: add loan button (close-as-rescheduled)

- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/savings/saving-account-actions/activate-savings-account/activate-savings-account.component.html
- src/app/savings/saving-account-actions/activate-savings-account/activate-savings-account.component.scss
- src/app/savings/saving-account-actions/activate-savings-account/activate-savings-account.component.spec.ts
- src/app/savings/saving-account-actions/activate-savings-account/activate-savings-account.component.ts
- src/app/savings/saving-account-actions/saving-account-actions.component.html
- src/app/savings/saving-account-actions/saving-account-actions.component.ts
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings.module.ts
Developed activate savings page
#918 
> feat: savings account actions (activate)

- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/savings/saving-account-actions/saving-account-actions.component.html
- src/app/savings/saving-account-actions/saving-account-actions.component.ts
- src/app/savings/saving-account-actions/undo-approval-savings-account/undo-approval-savings-account.component.html
- src/app/savings/saving-account-actions/undo-approval-savings-account/undo-approval-savings-account.component.scss
- src/app/savings/saving-account-actions/undo-approval-savings-account/undo-approval-savings-account.component.spec.ts
- src/app/savings/saving-account-actions/undo-approval-savings-account/undo-approval-savings-account.component.ts
- src/app/savings/savings-account-view/savings-account-view.component.html
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings.module.ts
Developed Undo-Approval savings page
#920 
> feat: savings account actions (undo-approval)

- src/app/savings/saving-account-actions/post-interest-as-on-savings-account/post-interest-as-on-savings-account.component.html
- src/app/savings/saving-account-actions/post-interest-as-on-savings-account/post-interest-as-on-savings-account.component.scss
- src/app/savings/saving-account-actions/post-interest-as-on-savings-account/post-interest-as-on-savings-account.component.spec.ts
- src/app/savings/saving-account-actions/post-interest-as-on-savings-account/post-interest-as-on-savings-account.component.ts
- src/app/savings/saving-account-actions/saving-account-actions.component.html
- src/app/savings/saving-account-actions/saving-account-actions.component.ts
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings.module.ts
- src/app/savings/savings.service.ts
Developed post interest as on savings page
#922
> feat: savings account actions (post-interest-as-on)

- src/app/savings/saving-account-actions/saving-account-actions.component.html
- src/app/savings/saving-account-actions/saving-account-actions.component.ts
- src/app/savings/saving-account-actions/savings-account-assign-staff/savings-account-assign-staff.component.html
- src/app/savings/saving-account-actions/savings-account-assign-staff/savings-account-assign-staff.component.scss
- src/app/savings/saving-account-actions/savings-account-assign-staff/savings-account-assign-staff.component.spec.ts
- src/app/savings/saving-account-actions/savings-account-assign-staff/savings-account-assign-staff.component.ts
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings.module.ts
Developed savings assign staff page
#924 
> feat: savings account actions (assign-staff)

- src/app/savings/saving-account-actions/saving-account-actions.component.html
- src/app/savings/saving-account-actions/saving-account-actions.component.ts
- src/app/savings/saving-account-actions/savings-account-unassign-staff/savings-account-unassign-staff.component.html
- src/app/savings/saving-account-actions/savings-account-unassign-staff/savings-account-unassign-staff.component.scss
- src/app/savings/saving-account-actions/savings-account-unassign-staff/savings-account-unassign-staff.component.spec.ts
- src/app/savings/saving-account-actions/savings-account-unassign-staff/savings-account-unassign-staff.component.ts
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings.module.ts
Developed savings unassign staff page
#926 
> feat: savings account actions (unassign-staff)

- src/app/savings/savings-account-view/custom-dialogs/calculate-interest-dialog/calculate-interest-dialog.component.html
- src/app/savings/savings-account-view/custom-dialogs/calculate-interest-dialog/calculate-interest-dialog.component.spec.ts
- src/app/savings/savings-account-view/custom-dialogs/calculate-interest-dialog/calculate-interest-dialog.component.ts
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings.module.ts
calculate savings interest.
#928 
> feat: savings account actions (calculate-interest)

- src/app/savings/savings-account-view/custom-dialogs/calculate-interest-dialog/calculate-interest-dialog.component.ts
- src/app/savings/savings-account-view/custom-dialogs/post-interest-dialog/post-interest-dialog.component.html
- src/app/savings/savings-account-view/custom-dialogs/post-interest-dialog/post-interest-dialog.component.spec.ts
- src/app/savings/savings-account-view/custom-dialogs/post-interest-dialog/post-interest-dialog.component.ts
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings.module.ts
Developed savings post interest
#930 
> feat: savings account actions (post-interest)

- src/app/loans/common-resolvers/loan-action-button.resolver.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans-view/loan-account-actions/loan-reschedule/loan-reschedule.component.html
- src/app/loans/loans-view/loan-account-actions/loan-reschedule/loan-reschedule.component.spec.ts
- src/app/loans/loans-view/loan-account-actions/loan-reschedule/loan-reschedule.component.ts
- src/app/loans/loans.module.ts
- src/app/loans/loans.service.ts
- Add reschedule loan action
#245
|Fields in collapsed form| Fields in expanded form|
| --- | --- |
|![Screenshot from 2020-06-13 22-00-41](https://user-images.githubusercontent.com/36980003/84574149-46b8d380-adc2-11ea-969d-669bf241a226.png) | ![Screenshot from 2020-06-13 22-00-51](https://user-images.githubusercontent.com/36980003/84574165-4e787800-adc2-11ea-86a0-646d506e1370.png) |
> feat: add loan button (reschedule loan)

- src/app/savings/common-resolvers/savings-account-transaction.resolver.ts
- src/app/savings/savings-account-view/custom-dialogs/undo-transaction-dialog/undo-transaction-dialog.component.html
- src/app/savings/savings-account-view/custom-dialogs/undo-transaction-dialog/undo-transaction-dialog.component.spec.ts
- src/app/savings/savings-account-view/custom-dialogs/undo-transaction-dialog/undo-transaction-dialog.component.ts
- src/app/savings/savings-account-view/transactions-tab/transactions-tab.component.html
- src/app/savings/savings-account-view/transactions-tab/transactions-tab.component.scss
- src/app/savings/savings-account-view/transactions-tab/transactions-tab.component.ts
- src/app/savings/savings-account-view/view-transaction/view-transaction.component.html
- src/app/savings/savings-account-view/view-transaction/view-transaction.component.scss
- src/app/savings/savings-account-view/view-transaction/view-transaction.component.spec.ts
- src/app/savings/savings-account-view/view-transaction/view-transaction.component.ts
- src/app/savings/savings-routing.module.ts
- src/app/savings/savings.module.ts
- src/app/savings/savings.service.ts
Developed savings transaction page
#932 
| View | Dialog |
| --- | --- |
| ![Screenshot from 2020-06-27 17-07-39](https://user-images.githubusercontent.com/54709463/85921518-8095d980-b89a-11ea-80ae-4894d320b4ad.png) | ![Screenshot from 2020-06-27 17-07-48](https://user-images.githubusercontent.com/54709463/85921564-ae7b1e00-b89a-11ea-948a-3a8034800913.png) |
> feat: view savings transaction page

- src/app/savings/common-resolvers/savings-account-charge.resolver.ts
- src/app/savings/savings-account-view/charges-tab/charges-tab.component.html
- src/app/savings/savings-account-view/charges-tab/charges-tab.component.scss
- src/app/savings/savings-account-view/custom-dialogs/inactivate-charge-dialog/inactivate-charge-dialog.component.html
- src/app/savings/savings-account-view/custom-dialogs/inactivate-charge-dialog/inactivate-charge-dialog.component.spec.ts
- src/app/savings/savings-account-view/custom-dialogs/inactivate-charge-dialog/inactivate-charge-dialog.component.ts
- src/app/savings/savings-account-view/custom-dialogs/waive-charge-dialog/waive-charge-dialog.component.html
- src/app/savings/savings-account-view/custom-dialogs/waive-charge-dialog/waive-charge-dialog.component.spec.ts
- src/app/savings/savings-account-view/custom-dialogs/waive-charge-dialog/waive-charge-dialog.component.ts
- src/app/savings/savings-account-view/view-charge/view-charge.component.html
- src/app/savings/savings-account-view/view-charge/view-charge.component.scss
- src/app/savings/savings-account-view/view-charge/view-charge.component.spec.ts
- src/app/savings/savings-account-view/view-charge/view-charge.component.ts
- src/app/savings/savings-routing.module.ts
- src/app/savings/savings.module.ts
- src/app/savings/savings.service.ts
- src/app/shared/icons.module.ts
Developed view savings charge page.
#938 
| View Charge |
| --- |
| ![Screenshot from 2020-06-27 22-02-18](https://user-images.githubusercontent.com/54709463/85928556-76d89a00-b8cb-11ea-984e-15cae51eddae.png) |
| Pay | Waive | Inactivate |
| --- | --- | --- |
| ![Screenshot from 2020-06-27 22-02-47](https://user-images.githubusercontent.com/54709463/85928571-996ab300-b8cb-11ea-849a-074413f9ce2c.png) | ![Screenshot from 2020-06-27 22-02-53](https://user-images.githubusercontent.com/54709463/85928578-a5ef0b80-b8cb-11ea-8dda-b34594acef3d.png) | ![Screenshot from 2020-06-27 22-02-59](https://user-images.githubusercontent.com/54709463/85928592-b606eb00-b8cb-11ea-804a-90ba2e98a835.png) |
> feat: savings account view charge

- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/loan-collateral-tab/loan-collateral-tab.component.html
- src/app/loans/loans-view/loan-collateral-tab/loan-collateral-tab.component.scss
- src/app/loans/loans-view/loan-collateral-tab/loan-collateral-tab.component.spec.ts
- src/app/loans/loans-view/loan-collateral-tab/loan-collateral-tab.component.ts
- src/app/loans/loans-view/loans-view.component.html
- src/app/loans/loans.module.ts
- Add loan collateral tab
#936 
> feat: add view loan (loan collateral tab)

- src/app/savings/common-resolvers/savings-account-actions.resolver.ts
- src/app/savings/saving-account-actions/close-savings-account/close-savings-account.component.html
- src/app/savings/saving-account-actions/close-savings-account/close-savings-account.component.scss
- src/app/savings/saving-account-actions/close-savings-account/close-savings-account.component.spec.ts
- src/app/savings/saving-account-actions/close-savings-account/close-savings-account.component.ts
- src/app/savings/saving-account-actions/saving-account-actions.component.html
- src/app/savings/saving-account-actions/saving-account-actions.component.ts
- src/app/savings/saving-account-actions/savings-account-transactions/savings-account-transactions.component.html
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings-routing.module.ts
- src/app/savings/savings.module.ts
Developed Savings close page
#942 
> feat: savings account actions (close)

- src/app/savings/savings-account-view/custom-dialogs/toggle-withhold-tax-dialog/toggle-withhold-tax-dialog.component.html
- src/app/savings/savings-account-view/custom-dialogs/toggle-withhold-tax-dialog/toggle-withhold-tax-dialog.component.spec.ts
- src/app/savings/savings-account-view/custom-dialogs/toggle-withhold-tax-dialog/toggle-withhold-tax-dialog.component.ts
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings.module.ts
- src/app/savings/savings.service.ts
Developed Savings enable/disable withhold tax
#944 
| Disable | Enable |
| --- | --- |
| ![Screenshot from 2020-06-29 00-47-35](https://user-images.githubusercontent.com/54709463/85956486-cdb1a280-b9a3-11ea-8582-6aa2bd243165.png) | ![Screenshot from 2020-06-29 00-47-16](https://user-images.githubusercontent.com/54709463/85956492-d73b0a80-b9a3-11ea-8395-84f61dcc2b81.png) |
> feat; savings account actions (enable/disable-withhold-tax)

- src/app/savings/savings-account-view/charges-tab/charges-tab.component.html
- src/app/savings/savings-account-view/charges-tab/charges-tab.component.ts
- src/app/savings/savings-account-view/view-charge/view-charge.component.html
- src/app/savings/savings-account-view/view-charge/view-charge.component.ts
- src/app/savings/savings.service.ts
Developed savings edit/delete charge
#951 
| Delete | Edit |
| --- | --- |
| ![Screenshot from 2020-06-29 20-03-45](https://user-images.githubusercontent.com/54709463/86019937-e3c36f80-ba44-11ea-9fc7-c3a9ae1a5c01.png) | ![Screenshot from 2020-06-29 20-03-37](https://user-images.githubusercontent.com/54709463/86020025-02296b00-ba45-11ea-9942-63a45cb4fb04.png) |
> feat: savings account charges actions (edit/delete)

- src/app/savings/common-resolvers/savings-account-transaction-template.resolver.ts
- src/app/savings/savings-account-view/transactions/edit-transaction/edit-transaction.component.html
- src/app/savings/savings-account-view/transactions/edit-transaction/edit-transaction.component.scss
- src/app/savings/savings-account-view/transactions/edit-transaction/edit-transaction.component.spec.ts
- src/app/savings/savings-account-view/transactions/edit-transaction/edit-transaction.component.ts
- src/app/savings/savings-account-view/transactions/view-transaction/view-transaction.component.html
- src/app/savings/savings-routing.module.ts
- src/app/savings/savings.module.ts
- src/app/savings/savings.service.ts
Developed savings edit transaction page
#953 
> feat: edit savings account transaction page

- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/clients/clients-view/general-tab/general-tab.component.scss
- src/app/clients/clients-view/general-tab/general-tab.component.ts
- src/app/navigation/loan-account-table/loan-account-table.component.ts
- src/app/navigation/savings-account-table/savings-account-table.component.ts
- src/app/navigation/share-account-table/share-account-table.component.ts
- src/app/pipes/accounts-filter.pipe.ts
- Added filters for recurring and fixed deposit accounts
- Added tables for recurring and fixed deposit accounts in clients view
- Aligned buttons with headings
#955 
> fix: add recurring and fixed account table in clients view section

- src/app/savings/saving-account-actions/apply-annual-fees-savings-account/apply-annual-fees-savings-account.component.html
- src/app/savings/saving-account-actions/apply-annual-fees-savings-account/apply-annual-fees-savings-account.component.scss
- src/app/savings/saving-account-actions/apply-annual-fees-savings-account/apply-annual-fees-savings-account.component.spec.ts
- src/app/savings/saving-account-actions/apply-annual-fees-savings-account/apply-annual-fees-savings-account.component.ts
- src/app/savings/saving-account-actions/saving-account-actions.component.html
- src/app/savings/saving-account-actions/saving-account-actions.component.ts
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings-account-view/transactions/view-transaction/view-transaction.component.html
- src/app/savings/savings-account-view/transactions/view-transaction/view-transaction.component.ts
- src/app/savings/savings.module.ts
Developed apply annual fees component
#957 
> feat: savings account actions (apply-annual-fees)

- src/app/deposits/fixed-deposits/fixed-deposit-account-view/datatable-tabs/datatable-tabs.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/datatable-tabs/datatable-tabs.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/datatable-tabs/datatable-tabs.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/datatable-tabs/multi-row/multi-row.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/datatable-tabs/multi-row/multi-row.component.scss
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/datatable-tabs/multi-row/multi-row.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/datatable-tabs/multi-row/multi-row.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/datatable-tabs/single-row/single-row.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/datatable-tabs/single-row/single-row.component.scss
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/datatable-tabs/single-row/single-row.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/datatable-tabs/single-row/single-row.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/fixed-deposit-account-view.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/fixed-deposit-account-view.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-routing.module.ts
- src/app/deposits/fixed-deposits/fixed-deposits.module.ts
- src/app/savings/common-resolvers/savings-datatable.resolver.ts
Connected view fd page to savings data tables
See: #863, #864
> feat: reuse savings datatables in view fixed deposit page

- src/app/deposits/fixed-deposits/fixed-deposit-account-view/fixed-deposit-account-view.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/fixed-deposit-account-view.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/approve-fixed-deposits-account/approve-fixed-deposits-account.component.html
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/approve-fixed-deposits-account/approve-fixed-deposits-account.component.scss
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/approve-fixed-deposits-account/approve-fixed-deposits-account.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/approve-fixed-deposits-account/approve-fixed-deposits-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-account-actions.component.html
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-account-actions.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-account-actions.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-routing.module.ts
- src/app/deposits/fixed-deposits/fixed-deposits.module.ts
- src/app/deposits/fixed-deposits/fixed-deposits.service.ts
Developed approve fd page.
#962
> feat: fixed deposit account actions (approve)

- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-account-actions.component.html
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/reject-fixed-deposits-account/reject-fixed-deposits-account.component.html
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/reject-fixed-deposits-account/reject-fixed-deposits-account.component.scss
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/reject-fixed-deposits-account/reject-fixed-deposits-account.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/reject-fixed-deposits-account/reject-fixed-deposits-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits.module.ts
Developed savings reject page
#964 
> feat: fixed deposit account actions (reject)

- src/app/deposits/fixed-deposits/fixed-deposit-account-view/fixed-deposit-account-view.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-account-actions.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits.service.ts
> feat: fixed deposit account actions (delete)

- src/app/deposits/fixed-deposits/fixed-deposit-account-view/custom-dialogs/calculate-interest-dialog/calculate-interest-dialog.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/custom-dialogs/calculate-interest-dialog/calculate-interest-dialog.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/custom-dialogs/calculate-interest-dialog/calculate-interest-dialog.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/custom-dialogs/post-interest-dialog/post-interest-dialog.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/custom-dialogs/post-interest-dialog/post-interest-dialog.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/custom-dialogs/post-interest-dialog/post-interest-dialog.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/fixed-deposit-account-view.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits.module.ts
Fixed deposits calculate post interest.
#968 
| Calculate Interest | Post Interest |
| --- | --- |
| ![Screenshot from 2020-07-03 14-53-03](https://user-images.githubusercontent.com/54709463/86455312-0eac0d00-bd3e-11ea-9a2b-8f8d037d44c0.png) | ![Screenshot from 2020-07-03 14-53-12](https://user-images.githubusercontent.com/54709463/86455236-f4722f00-bd3d-11ea-988b-3d9fe167e9da.png) |
> feat: fixed deposit actions (caclulate/post interest)

- src/app/deposits/fixed-deposits/fixed-deposit-account-view/custom-dialogs/toggle-withhold-tax-dialog/toggle-withhold-tax-dialog.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/custom-dialogs/toggle-withhold-tax-dialog/toggle-withhold-tax-dialog.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/custom-dialogs/toggle-withhold-tax-dialog/toggle-withhold-tax-dialog.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/fixed-deposit-account-view.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits.module.ts
Developed fd enable disable withhold tax
#970 
| Disable | Enable |
| --- | --- |
| ![Screenshot from 2020-07-03 15-45-30](https://user-images.githubusercontent.com/54709463/86459346-4322c780-bd44-11ea-9749-22a25b27dcde.png) | ![Screenshot from 2020-07-03 15-45-20](https://user-images.githubusercontent.com/54709463/86459368-4d44c600-bd44-11ea-9bc8-84ac80b72a2a.png) |
> feat: fixed deposits account actions (enable/disable withhold tax)

- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/activate-fixed-deposits-account/activate-fixed-deposits-account.component.html
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/activate-fixed-deposits-account/activate-fixed-deposits-account.component.scss
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/activate-fixed-deposits-account/activate-fixed-deposits-account.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/activate-fixed-deposits-account/activate-fixed-deposits-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-account-actions.component.html
- src/app/deposits/fixed-deposits/fixed-deposits.module.ts
> feat: fixed deposit account actions (activate)

- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-account-actions.component.html
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/undo-approval-fixed-deposits-account/undo-approval-fixed-deposits-account.component.html
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/undo-approval-fixed-deposits-account/undo-approval-fixed-deposits-account.component.scss
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/undo-approval-fixed-deposits-account/undo-approval-fixed-deposits-account.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/undo-approval-fixed-deposits-account/undo-approval-fixed-deposits-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits.module.ts
Developed fd undo approval page
#974 
> feat: fixed deposit account actions (undo-approval)

- src/app/deposits/fixed-deposits/fixed-deposit-account-view/fixed-deposit-account-view.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-account-actions.component.html
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-account-actions.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/withdraw-by-client-fixed-deposits-account/withdraw-by-client-fixed-deposits-account.component.html
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/withdraw-by-client-fixed-deposits-account/withdraw-by-client-fixed-deposits-account.component.scss
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/withdraw-by-client-fixed-deposits-account/withdraw-by-client-fixed-deposits-account.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/withdraw-by-client-fixed-deposits-account/withdraw-by-client-fixed-deposits-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits.module.ts
Developed fd withdraw by client
#976
> feat: fixed deposits actions (withdraw-by-client)

- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/transactions-tab.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/transactions-tab.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/transactions-tab.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/transactions-tab.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-routing.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits.module.ts
- Add Transactions Tab in view recurring deposits account
#980
> feat: add recurring deposit account tab (transactions)

- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/standing-instructions-tab/standing-instructions-tab.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/standing-instructions-tab/standing-instructions-tab.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/standing-instructions-tab/standing-instructions-tab.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/standing-instructions-tab/standing-instructions-tab.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-routing.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits.service.ts
- Add the Standing Instruction Tab in the recurring deposit account view
#982 
> feat: add recurring deposit account tab (standing instruction)

- src/app/deposits/recurring-deposits/recurring-deposits-account-view/charges-tab/charges-tab.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/charges-tab/charges-tab.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/charges-tab/charges-tab.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/charges-tab/charges-tab.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-routing.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits.module.ts
- Add Charges Tab in the view recurring deposit account
#983 
> feat: add recurring deposit account tab (charges)

- src/app/deposits/recurring-deposits/recurring-deposits-account-view/datatable-tabs/datatable-tabs.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/datatable-tabs/datatable-tabs.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/datatable-tabs/datatable-tabs.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/datatable-tabs/multi-row/multi-row.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/datatable-tabs/multi-row/multi-row.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/datatable-tabs/multi-row/multi-row.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/datatable-tabs/multi-row/multi-row.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/datatable-tabs/single-row/single-row.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/datatable-tabs/single-row/single-row.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/datatable-tabs/single-row/single-row.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/datatable-tabs/single-row/single-row.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-routing.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits.module.ts
- src/app/savings/common-resolvers/savings-datatable.resolver.ts
- Add data tables tab in view recurring deposit account
- Add single row and multi-row data tables in view recurring deposit account
#986 
> feat: add recurring deposit account tab (datatables)

- src/app/deposits/fixed-deposits/common-resolvers/fixed-deposit-account-transaction.resolver.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/custom-dialogs/undo-transaction-dialog/undo-transaction-dialog.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/custom-dialogs/undo-transaction-dialog/undo-transaction-dialog.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/custom-dialogs/undo-transaction-dialog/undo-transaction-dialog.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/transactions-tab/transactions-tab.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/transactions-tab/transactions-tab.component.scss
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/transactions/view-transaction/view-transaction.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/transactions/view-transaction/view-transaction.component.scss
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/transactions/view-transaction/view-transaction.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/transactions/view-transaction/view-transaction.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-routing.module.ts
- src/app/deposits/fixed-deposits/fixed-deposits.module.ts
- src/app/deposits/fixed-deposits/fixed-deposits.service.ts
view/undo fd transaction
#988
| View | Dialog |
| --- | --- |
| ![Screenshot from 2020-07-04 15-45-03](https://user-images.githubusercontent.com/54709463/86510578-7df13200-be0e-11ea-8a13-7a1853670f9b.png) | ![Screenshot from 2020-06-27 17-07-48](https://user-images.githubusercontent.com/54709463/85921564-ae7b1e00-b89a-11ea-948a-3a8034800913.png) |
> feat: view fixed deposit account transaction

- src/app/deposits/fixed-deposits/common-resolvers/fixed-deposit-account-actions.resolver.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/activate-fixed-deposits-account/activate-fixed-deposits-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/add-charge-fixed-deposits-account/add-charge-fixed-deposits-account.component.html
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/add-charge-fixed-deposits-account/add-charge-fixed-deposits-account.component.scss
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/add-charge-fixed-deposits-account/add-charge-fixed-deposits-account.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/add-charge-fixed-deposits-account/add-charge-fixed-deposits-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-account-actions.component.html
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-account-actions.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-routing.module.ts
- src/app/deposits/fixed-deposits/fixed-deposits.module.ts
- src/app/deposits/fixed-deposits/fixed-deposits.service.ts
Fixed Deposits add charge
#992
> feat: fixed deposits account actions (add-charge)

- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-account-actions.component.html
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/premature-close-fixed-deposits-account/premature-close-fixed-deposits-account.component.html
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/premature-close-fixed-deposits-account/premature-close-fixed-deposits-account.component.scss
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/premature-close-fixed-deposits-account/premature-close-fixed-deposits-account.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/premature-close-fixed-deposits-account/premature-close-fixed-deposits-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits.module.ts
Developed fd premature close
#994 
> feat: fixed deposit account actions (premature-close)

- src/app/deposits/fixed-deposits/common-resolvers/fixed-deposit-account-actions.resolver.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/close-fixed-deposits-account/close-fixed-deposits-account.component.html
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/close-fixed-deposits-account/close-fixed-deposits-account.component.scss
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/close-fixed-deposits-account/close-fixed-deposits-account.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/close-fixed-deposits-account/close-fixed-deposits-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-account-actions.component.html
- src/app/deposits/fixed-deposits/fixed-deposits.module.ts
- src/app/deposits/fixed-deposits/fixed-deposits.service.ts
> feat: fixed deposit account actions (close)

- src/app/deposits/recurring-deposits/common-resolvers/recurring-deposit-account-actions.resolver.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/activate-recurring-deposits-account/activate-recurring-deposits-account.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/activate-recurring-deposits-account/activate-recurring-deposits-account.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/activate-recurring-deposits-account/activate-recurring-deposits-account.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/activate-recurring-deposits-account/activate-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-routing.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits.service.ts
- Add activate action button in the recurring deposit page
#1000 
> feat: add recurring deposit actions (activate)

- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/fixed-deposit-account-view.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/interest-rate-chart-tab/interest-rate-chart-tab.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/interest-rate-chart-tab/interest-rate-chart-tab.component.scss
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/interest-rate-chart-tab/interest-rate-chart-tab.component.ts
Added incentives functionality, connected action buttons
#1004 
> feat: fd interest rate chart (view-incentives)

- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/clients/clients.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/undo-approval-recurring-deposits-account/undo-approval-recurring-deposits-account.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/undo-approval-recurring-deposits-account/undo-approval-recurring-deposits-account.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/undo-approval-recurring-deposits-account/undo-approval-recurring-deposits-account.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/undo-approval-recurring-deposits-account/undo-approval-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits.module.ts
- Add undo approval action
#1003 
> feat: Add Recurring Deposit Action (Undo Approval)

- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/approve-recurring-deposits-account/approve-recurring-deposits-account.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/approve-recurring-deposits-account/approve-recurring-deposits-account.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/approve-recurring-deposits-account/approve-recurring-deposits-account.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/approve-recurring-deposits-account/approve-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits.module.ts
- Add approve action in the recurring deposit page
#1008
> feat: add recurring deposits action (approve)

- src/app/deposits/fixed-deposits/common-resolvers/fixed-deposit-account-and-template.resolver.ts
- src/app/deposits/fixed-deposits/edit-fixed-deposit-account/edit-fixed-deposit-account.component.html
- src/app/deposits/fixed-deposits/edit-fixed-deposit-account/edit-fixed-deposit-account.component.spec.ts
- src/app/deposits/fixed-deposits/edit-fixed-deposit-account/edit-fixed-deposit-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-stepper/fixed-deposit-account-charges-step/fixed-deposit-account-charges-step.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-stepper/fixed-deposit-account-charges-step/fixed-deposit-account-charges-step.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-stepper/fixed-deposit-account-details-step/fixed-deposit-account-details-step.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-stepper/fixed-deposit-account-preview-step/fixed-deposit-account-preview-step.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-stepper/fixed-deposit-account-settings-step/fixed-deposit-account-settings-step.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-stepper/fixed-deposit-account-settings-step/fixed-deposit-account-settings-step.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-stepper/fixed-deposit-account-terms-step/fixed-deposit-account-terms-step.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/charges-tab/charges-tab.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/fixed-deposit-account-view.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-routing.module.ts
- src/app/deposits/fixed-deposits/fixed-deposits.module.ts
- src/app/deposits/fixed-deposits/fixed-deposits.service.ts
> feat: edit fixed deposits account

- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/reject-recurring-deposits-account/reject-recurring-deposits-account.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/reject-recurring-deposits-account/reject-recurring-deposits-account.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/reject-recurring-deposits-account/reject-recurring-deposits-account.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/reject-recurring-deposits-account/reject-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits.module.ts
- Add recurring deposit reject action
#1012 
> feat: add recurring deposit action (reject)

- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/withdraw-by-client-recurring-deposits-account/withdraw-by-client-recurring-deposits-account.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/withdraw-by-client-recurring-deposits-account/withdraw-by-client-recurring-deposits-account.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/withdraw-by-client-recurring-deposits-account/withdraw-by-client-recurring-deposits-account.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/withdraw-by-client-recurring-deposits-account/withdraw-by-client-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits.module.ts
- Add withdraw by client action in recurring deposit account
#1014 
> feat: add recurring deposit action (withdrawn by client)

- src/app/deposits/recurring-deposits/common-resolvers/recurring-deposit-account-actions.resolver.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/add-charge-recurring-deposits-account/add-charge-recurring-deposits-account.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/add-charge-recurring-deposits-account/add-charge-recurring-deposits-account.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/add-charge-recurring-deposits-account/add-charge-recurring-deposits-account.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/add-charge-recurring-deposits-account/add-charge-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/charges-tab/charges-tab.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/datatable-tabs/multi-row/multi-row.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/datatable-tabs/single-row/single-row.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-routing.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits.module.ts
- Add the add charge action in the recurring deposit account 
#1015
> feat: add recurring deposit action (add charge)

- src/app/deposits/recurring-deposits/recurring-deposits-account-view/custom-dialogs/recurring-deposit-confirmation-dialog/recurring-deposit-confirmation-dialog.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/custom-dialogs/recurring-deposit-confirmation-dialog/recurring-deposit-confirmation-dialog.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/custom-dialogs/recurring-deposit-confirmation-dialog/recurring-deposit-confirmation-dialog.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-buttons.config.ts
- src/app/deposits/recurring-deposits/recurring-deposits.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits.service.ts
- add delete action
- add calculate interest action
- add post interest action
- add enable withhold tax action
- add disable withhold tax action
#1020
|Delete Action|Calculate Interest Action|
|-----------------|---------------------------------|
|![Screenshot from 2020-07-08 01-41-08](https://user-images.githubusercontent.com/36980003/86838100-68edfa80-c0bd-11ea-8ed9-bba9d6aa69d1.png)|![Screenshot from 2020-07-08 01-37-25](https://user-images.githubusercontent.com/36980003/86838146-74d9bc80-c0bd-11ea-95dd-8173fe74cbda.png)|
|Post Interest|Enable Withhold Tax|Disable Withhold Tax|
|----------------|----------------------------|-----------------------------|
|![Screenshot from 2020-07-08 01-37-31](https://user-images.githubusercontent.com/36980003/86838281-989d0280-c0bd-11ea-8ce5-11b8941a5 …
> feat: add recurring deposit action buttons

- src/app/deposits/recurring-deposits/common-resolvers/recurring-deposit-account-and-template.resolver.ts
- src/app/deposits/recurring-deposits/edit-recurring-deposit-account/edit-recurring-deposit-account.component.html
- src/app/deposits/recurring-deposits/edit-recurring-deposit-account/edit-recurring-deposit-account.component.spec.ts
- src/app/deposits/recurring-deposits/edit-recurring-deposit-account/edit-recurring-deposit-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-charges-step/recurring-deposits-account-charges-step.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-details-step/recurring-deposits-account-details-step.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-preview-step/recurring-deposits-account-preview-step.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-settings-step/recurring-deposits-account-settings-step.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-settings-step/recurring-deposits-account-settings-step.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/charges-tab/charges-tab.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-routing.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits.service.ts
- Add edit recurring deposit account
#1017 
> feat: add edit recurring deposit account

- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/premature-close-recurring-deposit-account/premature-close-recurring-deposit-account.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/premature-close-recurring-deposit-account/premature-close-recurring-deposit-account.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/premature-close-recurring-deposit-account/premature-close-recurring-deposit-account.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/premature-close-recurring-deposit-account/premature-close-recurring-deposit-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits.service.ts
- Add premature close action in recurring deposit account
#1021 
> feat: add recurring deposit action (premature-close)

- src/app/groups/common-resolvers/group-data-and-template.resolver.ts
- src/app/groups/groups-routing.module.ts
- src/app/groups/groups-view/add-role/add-role.component.html
- src/app/groups/groups-view/add-role/add-role.component.scss
- src/app/groups/groups-view/add-role/add-role.component.spec.ts
- src/app/groups/groups-view/add-role/add-role.component.ts
- src/app/groups/groups-view/committee-tab/committee-tab.component.html
- src/app/groups/groups-view/committee-tab/committee-tab.component.ts
- src/app/groups/groups-view/custom-dialogs/unassign-role-dialog/unassign-role-dialog.component.html
- src/app/groups/groups-view/custom-dialogs/unassign-role-dialog/unassign-role-dialog.component.spec.ts
- src/app/groups/groups-view/custom-dialogs/unassign-role-dialog/unassign-role-dialog.component.ts
- src/app/groups/groups.module.ts
- src/app/groups/groups.service.ts
group assign and unassign role.
#1026 
| Assign | Unassign |
| --- | --- |
| ![Screenshot from 2020-07-08 13-54-55](https://user-images.githubusercontent.com/54709463/86897507-1f38fa80-c125-11ea-8b25-aa8f53622662.png) | ![Screenshot from 2020-07-08 13-54-08](https://user-images.githubusercontent.com/54709463/86897578-3a0b6f00-c125-11ea-8d5b-faab45396587.png) |
> feat: groups add and unassign role

- src/app/groups/common-resolvers/group-actions.resolver.ts
- src/app/groups/groups-routing.module.ts
- src/app/groups/groups-view/custom-dialogs/unassign-staff-dialog/unassign-staff-dialog.component.html
- src/app/groups/groups-view/custom-dialogs/unassign-staff-dialog/unassign-staff-dialog.component.spec.ts
- src/app/groups/groups-view/custom-dialogs/unassign-staff-dialog/unassign-staff-dialog.component.ts
- src/app/groups/groups-view/group-actions/group-actions.component.html
- src/app/groups/groups-view/group-actions/group-actions.component.spec.ts
- src/app/groups/groups-view/group-actions/group-actions.component.ts
- src/app/groups/groups-view/group-actions/group-assign-staff/group-assign-staff.component.html
- src/app/groups/groups-view/group-actions/group-assign-staff/group-assign-staff.component.scss
- src/app/groups/groups-view/group-actions/group-assign-staff/group-assign-staff.component.spec.ts
- src/app/groups/groups-view/group-actions/group-assign-staff/group-assign-staff.component.ts
- src/app/groups/groups-view/groups-view.component.html
- src/app/groups/groups-view/groups-view.component.ts
- src/app/groups/groups.module.ts
#1028
| Assign | Unassign |
| --- | --- |
| ![Screenshot from 2020-07-08 15-14-36](https://user-images.githubusercontent.com/54709463/86904806-d71ed580-c12e-11ea-823a-56693474b02b.png) | ![Screenshot from 2020-07-08 15-14-51](https://user-images.githubusercontent.com/54709463/86904836-e140d400-c12e-11ea-909e-c8f9c8a5d8ec.png) |
> feat: group actions (assign/unassign staff)

- src/app/groups/common-resolvers/group-actions.resolver.ts
- src/app/groups/groups-view/group-actions/close-group/close-group.component.html
- src/app/groups/groups-view/group-actions/close-group/close-group.component.scss
- src/app/groups/groups-view/group-actions/close-group/close-group.component.spec.ts
- src/app/groups/groups-view/group-actions/close-group/close-group.component.ts
- src/app/groups/groups-view/group-actions/group-actions.component.html
- src/app/groups/groups-view/group-actions/group-actions.component.ts
- src/app/groups/groups-view/groups-view.component.html
- src/app/groups/groups-view/groups-view.component.ts
- src/app/groups/groups.module.ts
- src/app/groups/groups.service.ts
> feat: group actions (close)

- src/app/groups/groups-view/group-actions/activate-group/activate-group.component.html
- src/app/groups/groups-view/group-actions/activate-group/activate-group.component.scss
- src/app/groups/groups-view/group-actions/activate-group/activate-group.component.spec.ts
- src/app/groups/groups-view/group-actions/activate-group/activate-group.component.ts
- src/app/groups/groups-view/group-actions/group-actions.component.html
- src/app/groups/groups-view/group-actions/group-actions.component.ts
- src/app/groups/groups-view/groups-view.component.html
- src/app/groups/groups-view/groups-view.component.ts
- src/app/groups/groups.module.ts
Developed activate group
#1032 
> feat: group actions (activate)

- src/app/groups/groups-view/groups-view.component.html
- src/app/groups/groups-view/groups-view.component.ts
- src/app/groups/groups.service.ts
> feat: group actions (delete)

- src/app/groups/create-group/create-group.component.ts
- src/app/groups/edit-group/edit-group.component.html
- src/app/groups/edit-group/edit-group.component.scss
- src/app/groups/edit-group/edit-group.component.spec.ts
- src/app/groups/edit-group/edit-group.component.ts
- src/app/groups/groups-routing.module.ts
- src/app/groups/groups-view/groups-view.component.html
- src/app/groups/groups-view/groups-view.component.ts
- src/app/groups/groups.module.ts
- src/app/groups/groups.service.ts
> feat: add edit group page

- src/app/deposits/recurring-deposits/common-resolvers/recurring-deposit-account-actions.resolver.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/close-recurring-deposits-account/close-recurring-deposits-account.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/close-recurring-deposits-account/close-recurring-deposits-account.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/close-recurring-deposits-account/close-recurring-deposits-account.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/close-recurring-deposits-account/close-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits.service.ts
- Add close action in the recurring deposit account
#1019
|Collapsed Form|Expanded Form|
|---------------------|---------------------|
|![Screenshot from 2020-07-08 21-19-17](https://user-images.githubusercontent.com/36980003/86941657-cf2c5900-c161-11ea-9e3b-5a9d04481ff8.png)|![Screenshot from 2020-07-08 21-19-23](https://user-images.githubusercontent.com/36980003/86941670-d3f10d00-c161-11ea-920e-e215dc808216.png)|
> feat: add recurring deposits action (close)

- src/app/deposits/recurring-deposits/common-resolvers/recurring-deposit-account-actions.resolver.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/deposit-recurring-deposits-account/deposit-recurring-deposits-account.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/deposit-recurring-deposits-account/deposit-recurring-deposits-account.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/deposit-recurring-deposits-account/deposit-recurring-deposits-account.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/deposit-recurring-deposits-account/deposit-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits.service.ts
- Add deposit action in the recurring deposit account
#1025
> feat: add recurring deposit action (deposit)

- src/app/deposits/recurring-deposits/recurring-deposits-account-view/charges-tab/charges-tab.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/charges-tab/charges-tab.component.ts
- Add edit charge
- Add delete charge
- Add waive charge
- Add pay charge
- Removed option to toggle between active and inactive charges(as not present in the community app)
#1040 
|Edit Charge|Delete Charge|
|---------------|---------------------|
|![Screenshot from 2020-07-08 23-18-56](https://user-images.githubusercontent.com/36980003/86955498-4fa88500-c175-11ea-9051-d27ea84fdca0.png)|![Screenshot from 2020-07-08 23-19-01](https://user-images.githubusercontent.com/36980003/86955526-5b944700-c175-11ea-93aa-c71af09a787c.png)|
|Pay Charge|Waive Charge|
|---------------|---------------------|
|![Screenshot from 2020-07-08 23-26-45](https://user-images.githubusercontent.com/36980003/86955656-8ed6d600-c175-11ea-8589-b67e6cccebbe.png)|![Screenshot from 2020-07-08 …
> feat: add recurring deposit account (charges tab action)

- src/app/deposits/recurring-deposits/common-resolvers/recurring-deposit-account-transaction-template.resolver.ts
- src/app/deposits/recurring-deposits/common-resolvers/recurring-deposit-account-transaction.resolver.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/charges-tab/charges-tab.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/edit-transaction/edit-transaction.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/edit-transaction/edit-transaction.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/edit-transaction/edit-transaction.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/edit-transaction/edit-transaction.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/transactions-tab.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/transactions-tab.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/view-transaction/view-transaction.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/view-transaction/view-transaction.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/view-transaction/view-transaction.component.spec.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/view-transaction/view-transaction.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-routing.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits.module.ts
- src/app/deposits/recurring-deposits/recurring-deposits.service.ts
- Add view transactions 
- Add edit transactions
- Add undo transactions
#1042 
|View Transaction|Edit Transaction|Undo Transaction|
|-----------------------|---------------------|------------------------|
|![Selection_001](https://user-images.githubusercontent.com/36980003/86964945-70c4a200-c184-11ea-8a2a-8094ba232d7b.png)|![Selection_002](https://user-images.githubusercontent.com/36980003/86964958-74582900-c184-11ea-8a05-e6a9abad1d7a.png)|![Selection_003](https://user-images.githubusercontent.com/36980003/86964967-77531980-c184-11ea-8e09-45f472842128.png)|
> feat: add recurring deposit account (transactions tab action)

- src/app/groups/common-resolvers/group-actions.resolver.ts
- src/app/groups/groups-view/group-actions/attach-group-meeting/attach-group-meeting.component.html
- src/app/groups/groups-view/group-actions/attach-group-meeting/attach-group-meeting.component.scss
- src/app/groups/groups-view/group-actions/attach-group-meeting/attach-group-meeting.component.spec.ts
- src/app/groups/groups-view/group-actions/attach-group-meeting/attach-group-meeting.component.ts
- src/app/groups/groups-view/group-actions/group-actions.component.html
- src/app/groups/groups-view/group-actions/group-actions.component.ts
- src/app/groups/groups-view/groups-view.component.html
- src/app/groups/groups-view/groups-view.component.ts
- src/app/groups/groups.module.ts
- src/app/groups/groups.service.ts
Developed groups attach meeting
#1044 
> feat: group actions (attach-meeting)

- src/app/groups/common-resolvers/group-actions.resolver.ts
- src/app/groups/groups-view/group-actions/group-actions.component.html
- src/app/groups/groups-view/group-actions/group-actions.component.ts
- src/app/groups/groups-view/group-actions/group-attendance/group-attendance.component.html
- src/app/groups/groups-view/group-actions/group-attendance/group-attendance.component.scss
- src/app/groups/groups-view/group-actions/group-attendance/group-attendance.component.spec.ts
- src/app/groups/groups-view/group-actions/group-attendance/group-attendance.component.ts
- src/app/groups/groups-view/groups-view.component.html
- src/app/groups/groups-view/groups-view.component.ts
- src/app/groups/groups.module.ts
- src/app/groups/groups.service.ts
> feat: group actions (attendance)

- src/app/clients/clients.service.ts
- src/app/groups/common-resolvers/group-actions.resolver.ts
- src/app/groups/groups-view/group-actions/group-actions.component.html
- src/app/groups/groups-view/group-actions/group-actions.component.ts
- src/app/groups/groups-view/group-actions/group-attendance/group-attendance.component.ts
- src/app/groups/groups-view/group-actions/manage-group-members/manage-group-members.component.html
- src/app/groups/groups-view/group-actions/manage-group-members/manage-group-members.component.scss
- src/app/groups/groups-view/group-actions/manage-group-members/manage-group-members.component.spec.ts
- src/app/groups/groups-view/group-actions/manage-group-members/manage-group-members.component.ts
- src/app/groups/groups-view/groups-view.component.html
- src/app/groups/groups-view/groups-view.component.ts
- src/app/groups/groups.module.ts
> feat: group actions (manage-members)

- src/app/groups/common-resolvers/group-actions.resolver.ts
- src/app/groups/groups-view/group-actions/edit-group-meeting/edit-group-meeting.component.html
- src/app/groups/groups-view/group-actions/edit-group-meeting/edit-group-meeting.component.scss
- src/app/groups/groups-view/group-actions/edit-group-meeting/edit-group-meeting.component.spec.ts
- src/app/groups/groups-view/group-actions/edit-group-meeting/edit-group-meeting.component.ts
- src/app/groups/groups-view/group-actions/group-actions.component.html
- src/app/groups/groups-view/group-actions/group-actions.component.ts
- src/app/groups/groups-view/groups-view.component.html
- src/app/groups/groups-view/groups-view.component.ts
- src/app/groups/groups.module.ts
- src/app/groups/groups.service.ts
Developed group edit meeting
#1051 
> feat: group actions (edit-meeting)

- src/app/groups/common-resolvers/group-actions.resolver.ts
- src/app/groups/groups-view/group-actions/edit-group-meeting-schedule/edit-group-meeting-schedule.component.html
- src/app/groups/groups-view/group-actions/edit-group-meeting-schedule/edit-group-meeting-schedule.component.scss
- src/app/groups/groups-view/group-actions/edit-group-meeting-schedule/edit-group-meeting-schedule.component.spec.ts
- src/app/groups/groups-view/group-actions/edit-group-meeting-schedule/edit-group-meeting-schedule.component.ts
- src/app/groups/groups-view/group-actions/edit-group-meeting/edit-group-meeting.component.html
- src/app/groups/groups-view/group-actions/edit-group-meeting/edit-group-meeting.component.ts
- src/app/groups/groups-view/group-actions/group-actions.component.html
- src/app/groups/groups-view/group-actions/group-actions.component.ts
- src/app/groups/groups-view/groups-view.component.ts
- src/app/groups/groups.module.ts
Developed groups edit meeting schedule
#1053 
> feat: group actions (edit-meeting-schedule)

- src/app/groups/common-resolvers/group-actions.resolver.ts
- src/app/groups/groups-view/group-actions/group-actions.component.html
- src/app/groups/groups-view/group-actions/group-actions.component.ts
- src/app/groups/groups-view/group-actions/group-transfer-clients/group-transfer-clients.component.html
- src/app/groups/groups-view/group-actions/group-transfer-clients/group-transfer-clients.component.scss
- src/app/groups/groups-view/group-actions/group-transfer-clients/group-transfer-clients.component.spec.ts
- src/app/groups/groups-view/group-actions/group-transfer-clients/group-transfer-clients.component.ts
- src/app/groups/groups-view/groups-view.component.html
- src/app/groups/groups-view/groups-view.component.ts
- src/app/groups/groups.module.ts
- src/app/groups/groups.service.ts
groups transfer clients
#1055 
> feat: group actions (transfer-clients)

- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/loans/common-resolvers/loan-action-button.resolver.ts
- src/app/loans/create-loans-account/create-loans-account.component.ts
- src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.html
- src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.ts
- src/app/loans/loans-view/loan-account-actions/prepay-loan/prepay-loan.component.ts
- src/app/loans/loans-view/loan-account-actions/recovery-repayment/recovery-repayment.component.html
- src/app/loans/loans-view/loan-account-actions/recovery-repayment/recovery-repayment.component.scss
- src/app/loans/loans-view/loan-account-actions/recovery-repayment/recovery-repayment.component.spec.ts
- src/app/loans/loans-view/loan-account-actions/recovery-repayment/recovery-repayment.component.ts
- src/app/loans/loans.module.ts
- Add Recovery Repayment action button
- Refined Prepay Loan and Repayment Action 
#1057 
> feat: add loan button (recovery-repayment)

- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- src/app/organization/tellers/cashiers/cashiers.component.html
- src/app/organization/tellers/cashiers/cashiers.component.ts
- src/app/organization/tellers/transactions/transactions.component.html
- src/app/organization/tellers/transactions/transactions.component.scss
- src/app/organization/tellers/transactions/transactions.component.spec.ts
- src/app/organization/tellers/transactions/transactions.component.ts
- src/app/shared/icons.module.ts
Developed transactions list page in TCM
#760 
> feat: cashier transactions list page

- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- src/app/organization/tellers/settle-cash/settle-cash.component.html
- src/app/organization/tellers/settle-cash/settle-cash.component.spec.ts
- src/app/organization/tellers/settle-cash/settle-cash.component.ts
- src/app/organization/tellers/teller-transaction-template.resolver.ts
Settle Cash component added.
#759 
> feat: add settle cash component

- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- src/app/organization/tellers/allocate-cash/allocate-cash.component.html
- src/app/organization/tellers/allocate-cash/allocate-cash.component.spec.ts
- src/app/organization/tellers/allocate-cash/allocate-cash.component.ts
Allocate Cash component created.
#758 
> feat: add allocate cash component

- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
- src/app/organization/tellers/edit-cashier/edit-cashier.component.html
- src/app/organization/tellers/edit-cashier/edit-cashier.component.spec.ts
- src/app/organization/tellers/edit-cashier/edit-cashier.component.ts
- src/app/organization/tellers/edit-cashier/edit-cashier.resolver.ts
- src/app/organization/tellers/view-cashier/view-cashier.component.html
Edit Cashier component created.
#762 
> feat: add edit cashier component

- src/app/organization/holidays/edit-holiday/edit-holiday.component.html
- src/app/organization/holidays/edit-holiday/edit-holiday.component.scss
- src/app/organization/holidays/edit-holiday/edit-holiday.component.spec.ts
- src/app/organization/holidays/edit-holiday/edit-holiday.component.ts
- src/app/organization/holidays/holiday-template.resolver.ts
- src/app/organization/holidays/holidays.component.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
Edit Holidays component created.
#750 
> feat: add edit holiday component

- src/app/loans/common-resolvers/loan-action-button.resolver.ts
- src/app/loans/loans-view/loan-account-actions/assign-loan-officer/assign-loan-officer.component.ts
- src/app/loans/loans-view/loan-account-actions/disburse/disburse.component.html
- src/app/loans/loans-view/loan-account-actions/disburse/disburse.component.scss
- src/app/loans/loans-view/loan-account-actions/disburse/disburse.component.spec.ts
- src/app/loans/loans-view/loan-account-actions/disburse/disburse.component.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans-view/loan-account-actions/undo-approval/undo-approval.component.ts
- src/app/loans/loans.module.ts
- Add loans disburse option
#856 
> feat: add loan action (disburse)

- src/app/loans/loans-view/loan-account-actions/disburse/disburse.component.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans-view/loan-account-actions/withdrawn-by-client/withdrawn-by-client.component.html
- src/app/loans/loans-view/loan-account-actions/withdrawn-by-client/withdrawn-by-client.component.spec.ts
- src/app/loans/loans-view/loan-account-actions/withdrawn-by-client/withdrawn-by-client.component.ts
- src/app/loans/loans.module.ts
- Add withdrawn by client action
#859 
> feat: add loan action (withdrawn by client)

- src/app/clients/clients-view/client-actions/client-actions.component.html
- src/app/clients/clients-view/client-actions/client-actions.component.ts
- src/app/clients/clients-view/client-actions/close-client/close-client.component.html
- src/app/clients/clients-view/client-actions/close-client/close-client.component.scss
- src/app/clients/clients-view/client-actions/close-client/close-client.component.spec.ts
- src/app/clients/clients-view/client-actions/close-client/close-client.component.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
- src/app/clients/common-resolvers/client-actions.resolver.ts
> feat: client actions (close)

- src/app/clients/clients-view/client-actions/client-actions.component.html
- src/app/clients/clients-view/client-actions/client-actions.component.ts
- src/app/clients/clients-view/client-actions/reject-client/reject-client.component.html
- src/app/clients/clients-view/client-actions/reject-client/reject-client.component.scss
- src/app/clients/clients-view/client-actions/reject-client/reject-client.component.spec.ts
- src/app/clients/clients-view/client-actions/reject-client/reject-client.component.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients.module.ts
- src/app/clients/common-resolvers/client-actions.resolver.ts
> feat: client actions (reject)

- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients.service.ts
> feat: client actions (delete)

- src/app/clients/clients-view/client-actions/activate-client/activate-client.component.html
- src/app/clients/clients-view/client-actions/activate-client/activate-client.component.scss
- src/app/clients/clients-view/client-actions/activate-client/activate-client.component.spec.ts
- src/app/clients/clients-view/client-actions/activate-client/activate-client.component.ts
- src/app/clients/clients-view/client-actions/client-actions.component.html
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients.module.ts
> feat: client actions (activate)

- src/app/clients/clients-view/client-actions/client-actions.component.html
- src/app/clients/clients-view/client-actions/client-actions.component.ts
- src/app/clients/clients-view/client-actions/withdraw-client/withdraw-client.component.html
- src/app/clients/clients-view/client-actions/withdraw-client/withdraw-client.component.scss
- src/app/clients/clients-view/client-actions/withdraw-client/withdraw-client.component.spec.ts
- src/app/clients/clients-view/client-actions/withdraw-client/withdraw-client.component.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients.module.ts
- src/app/clients/common-resolvers/client-actions.resolver.ts
> feat: client actions (withdraw)

- src/app/clients/clients-routing.module.ts
- src/app/clients/clients-view/client-actions/view-survey/take-survey/take-survey.component.html
- src/app/clients/clients-view/client-actions/view-survey/take-survey/take-survey.component.scss
- src/app/clients/clients-view/client-actions/view-survey/take-survey/take-survey.component.spec.ts
- src/app/clients/clients-view/client-actions/view-survey/take-survey/take-survey.component.ts
- src/app/clients/clients-view/client-actions/view-survey/view-survey.component.html
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
- src/app/clients/common-resolvers/take-survey.resolver.ts
Added the feature to take a survey page for clients.
#269 
> feat: add client take survey page

- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
- src/app/products/recurring-deposit-products/recurring-deposit-product.resolver.ts
- src/app/products/recurring-deposit-products/recurring-deposit-products-template.resolver.ts
- src/app/products/recurring-deposit-products/recurring-deposit-products.component.html
- src/app/products/recurring-deposit-products/view-recurring-deposit-product/view-recurring-deposit-product.component.html
- src/app/products/recurring-deposit-products/view-recurring-deposit-product/view-recurring-deposit-product.component.scss
- src/app/products/recurring-deposit-products/view-recurring-deposit-product/view-recurring-deposit-product.component.spec.ts
- src/app/products/recurring-deposit-products/view-recurring-deposit-product/view-recurring-deposit-product.component.ts
- Add View Recurring Deposit Product Page
#467 
**Edit 1:**
> feat: add view recurring deposit product page

- src/app/clients/clients-view/client-actions/client-actions.component.html
- src/app/clients/clients-view/client-actions/client-actions.component.ts
- src/app/clients/clients-view/client-actions/update-client-savings-account/update-client-savings-account.component.html
- src/app/clients/clients-view/client-actions/update-client-savings-account/update-client-savings-account.component.scss
- src/app/clients/clients-view/client-actions/update-client-savings-account/update-client-savings-account.component.spec.ts
- src/app/clients/clients-view/client-actions/update-client-savings-account/update-client-savings-account.component.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients.module.ts
- src/app/clients/common-resolvers/client-actions.resolver.ts
> feat: client actions (update-savings)

- src/app/clients/clients-view/client-actions/client-actions.component.html
- src/app/clients/clients-view/client-actions/client-actions.component.ts
- src/app/clients/clients-view/client-actions/transfer-client/transfer-client.component.html
- src/app/clients/clients-view/client-actions/transfer-client/transfer-client.component.scss
- src/app/clients/clients-view/client-actions/transfer-client/transfer-client.component.spec.ts
- src/app/clients/clients-view/client-actions/transfer-client/transfer-client.component.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
- src/app/clients/common-resolvers/client-actions.resolver.ts
> feat: client actions (transfer)

- src/app/clients/clients-view/client-actions/client-actions.component.html
- src/app/clients/clients-view/client-actions/client-actions.component.ts
- src/app/clients/clients-view/client-actions/undo-client-transfer/undo-client-transfer.component.html
- src/app/clients/clients-view/client-actions/undo-client-transfer/undo-client-transfer.component.scss
- src/app/clients/clients-view/client-actions/undo-client-transfer/undo-client-transfer.component.spec.ts
- src/app/clients/clients-view/client-actions/undo-client-transfer/undo-client-transfer.component.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
- src/app/clients/common-resolvers/client-actions.resolver.ts
> feat: client actions (undo-transfer)

- src/app/centers/centers-routing.module.ts
- src/app/centers/centers-view/center-actions/activate-center/activate-center.component.html
- src/app/centers/centers-view/center-actions/activate-center/activate-center.component.scss
- src/app/centers/centers-view/center-actions/activate-center/activate-center.component.spec.ts
- src/app/centers/centers-view/center-actions/activate-center/activate-center.component.ts
- src/app/centers/centers-view/center-actions/center-actions.component.html
- src/app/centers/centers-view/center-actions/center-actions.component.spec.ts
- src/app/centers/centers-view/center-actions/center-actions.component.ts
- src/app/centers/centers-view/centers-view.component.html
- src/app/centers/centers-view/centers-view.component.ts
- src/app/centers/centers.component.html
- src/app/centers/centers.module.ts
- src/app/centers/centers.service.ts
- src/app/groups/groups.component.html
Add activate action in centers module
#1084 
> feat: add centers action (activate)

- src/app/clients/clients-view/client-actions/client-actions.component.html
- src/app/clients/clients-view/client-actions/reject-client-transfer/reject-client-transfer.component.html
- src/app/clients/clients-view/client-actions/reject-client-transfer/reject-client-transfer.component.scss
- src/app/clients/clients-view/client-actions/reject-client-transfer/reject-client-transfer.component.spec.ts
- src/app/clients/clients-view/client-actions/reject-client-transfer/reject-client-transfer.component.ts
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients.module.ts
> feat: client actions (reject-transfer)

- src/app/clients/clients-view/client-actions/accept-client-transfer/accept-client-transfer.component.html
- src/app/clients/clients-view/client-actions/accept-client-transfer/accept-client-transfer.component.scss
- src/app/clients/clients-view/client-actions/accept-client-transfer/accept-client-transfer.component.spec.ts
- src/app/clients/clients-view/client-actions/accept-client-transfer/accept-client-transfer.component.ts
- src/app/clients/clients-view/client-actions/client-actions.component.html
- src/app/clients/clients.module.ts
> feat: client actions (accept-transfer)

- src/app/centers/centers-routing.module.ts
- src/app/centers/centers-view/center-actions/center-actions.component.html
- src/app/centers/centers-view/center-actions/center-actions.component.ts
- src/app/centers/centers-view/center-actions/center-assign-staff/center-assign-staff.component.html
- src/app/centers/centers-view/center-actions/center-assign-staff/center-assign-staff.component.scss
- src/app/centers/centers-view/center-actions/center-assign-staff/center-assign-staff.component.spec.ts
- src/app/centers/centers-view/center-actions/center-assign-staff/center-assign-staff.component.ts
- src/app/centers/centers-view/centers-view.component.html
- src/app/centers/centers-view/centers-view.component.ts
- src/app/centers/centers.module.ts
- src/app/centers/centers.service.ts
- src/app/centers/common-resolvers/center-actions.resolver.ts
- src/app/shared/confirmation-dialog/confirmation-dialog.component.html
- src/app/shared/confirmation-dialog/confirmation-dialog.component.spec.ts
- src/app/shared/confirmation-dialog/confirmation-dialog.component.ts
- src/app/shared/shared.module.ts
- Add assign and unassign staff action in the centers module
#1090 
|Assign Staff|Unassign Staff|
|--|--|
|![screencapture-localhost-4200-centers-13-actions-Assign-Staff-2020-07-14-11_17_00](https://user-images.githubusercontent.com/36980003/87389708-dff72780-c5c4-11ea-9331-9a833ea6edf3.png)|![screencapture-localhost-4200-centers-13-general-2020-07-14-11_17_26](https://user-images.githubusercontent.com/36980003/87389711-e1285480-c5c4-11ea-8128-21d73f8ada77.png)|
> feat: add centers action (assign and unassign staff)

- src/app/centers/centers-view/center-actions/center-actions.component.html
- src/app/centers/centers-view/center-actions/center-actions.component.ts
- src/app/centers/centers-view/center-actions/close-center/close-center.component.html
- src/app/centers/centers-view/center-actions/close-center/close-center.component.scss
- src/app/centers/centers-view/center-actions/close-center/close-center.component.spec.ts
- src/app/centers/centers-view/center-actions/close-center/close-center.component.ts
- src/app/centers/centers-view/centers-view.component.html
- src/app/centers/centers-view/centers-view.component.ts
- src/app/centers/centers.module.ts
- src/app/centers/centers.service.ts
- Add close action in centers module
- Add delete centers dialog box
#1092
|Close Center Action|Delete Center|
|-------------|---------------|
|![screencapture-localhost-4200-centers-20-actions-Close-2020-07-14-15_39_37](https://user-images.githubusercontent.com/36980003/87415000-2dd25680-c5ea-11ea-93ac-b8de777ce0af.png)|![screencapture-localhost-4200-centers-20-general-2020-07-14-15_40_01](https://user-images.githubusercontent.com/36980003/87415013-3034b080-c5ea-11ea-83cc-1b3d82b82f52.png)|
> feat: add center actions (close and delete)

- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans-view/loan-account-actions/undo-disbursal/undo-disbursal.component.html
- src/app/loans/loans-view/loan-account-actions/undo-disbursal/undo-disbursal.component.spec.ts
- src/app/loans/loans-view/loan-account-actions/undo-disbursal/undo-disbursal.component.ts
- src/app/loans/loans.module.ts
Added undo disbursal component, designed the UI and connected it to the API.
#827 
> feat: add loan button (undo disbursal)

- src/app/centers/centers-view/center-actions/center-actions.component.html
- src/app/centers/centers-view/center-actions/center-actions.component.ts
- src/app/centers/centers-view/center-actions/center-attendance/center-attendance.component.html
- src/app/centers/centers-view/center-actions/center-attendance/center-attendance.component.scss
- src/app/centers/centers-view/center-actions/center-attendance/center-attendance.component.spec.ts
- src/app/centers/centers-view/center-actions/center-attendance/center-attendance.component.ts
- src/app/centers/centers-view/centers-view.component.html
- src/app/centers/centers-view/centers-view.component.ts
- src/app/centers/centers.module.ts
- src/app/centers/centers.service.ts
- src/app/centers/common-resolvers/center-actions.resolver.ts
- Add Centers Attendance Action
#1094 
> feat: add centers action (Attendance)

- src/app/centers/centers-view/center-actions/attach-center-meeting/attach-center-meeting.component.html
- src/app/centers/centers-view/center-actions/attach-center-meeting/attach-center-meeting.component.scss
- src/app/centers/centers-view/center-actions/attach-center-meeting/attach-center-meeting.component.spec.ts
- src/app/centers/centers-view/center-actions/attach-center-meeting/attach-center-meeting.component.ts
- src/app/centers/centers-view/center-actions/center-actions.component.html
- src/app/centers/centers-view/center-actions/center-actions.component.ts
- src/app/centers/centers-view/centers-view.component.html
- src/app/centers/centers-view/centers-view.component.scss
- src/app/centers/centers-view/centers-view.component.ts
- src/app/centers/centers.module.ts
- src/app/centers/centers.service.ts
- src/app/centers/common-resolvers/center-actions.resolver.ts
- Add Attach Meeting Action in Centers Module
#1096 
> feat: add centers action (attach meeting)

- src/app/centers/centers-view/center-actions/center-actions.component.html
- src/app/centers/centers-view/center-actions/center-actions.component.ts
- src/app/centers/centers-view/center-actions/edit-center-meeting-schedule/edit-center-meeting-schedule.component.html
- src/app/centers/centers-view/center-actions/edit-center-meeting-schedule/edit-center-meeting-schedule.component.scss
- src/app/centers/centers-view/center-actions/edit-center-meeting-schedule/edit-center-meeting-schedule.component.spec.ts
- src/app/centers/centers-view/center-actions/edit-center-meeting-schedule/edit-center-meeting-schedule.component.ts
- src/app/centers/centers-view/center-actions/edit-center-meeting/edit-center-meeting.component.html
- src/app/centers/centers-view/center-actions/edit-center-meeting/edit-center-meeting.component.scss
- src/app/centers/centers-view/center-actions/edit-center-meeting/edit-center-meeting.component.spec.ts
- src/app/centers/centers-view/center-actions/edit-center-meeting/edit-center-meeting.component.ts
- src/app/centers/centers-view/centers-view.component.html
- src/app/centers/centers-view/centers-view.component.ts
- src/app/centers/centers.module.ts
- src/app/centers/centers.service.ts
- src/app/centers/common-resolvers/center-actions.resolver.ts
- Add Centers edit meeting action
- Add Centers edit future schedule action 
#1098
|Edit Meeting|Edit Future Schedule|
|---|---|
|![screencapture-localhost-4200-centers-20-actions-Edit-Meeting-2020-07-14-23_06_14](https://user-images.githubusercontent.com/36980003/87460924-4151e180-c62b-11ea-98ab-e1ea6ecb9bed.png)|![screencapture-localhost-4200-centers-20-actions-Edit-Meeting-Schedule-2020-07-14-23_06_26](https://user-images.githubusercontent.com/36980003/87460931-43b43b80-c62b-11ea-8aa4-3afb560ab233.png)|
> feat: add centers action (edit-meeting)

- src/app/clients/clients-view/client-actions/client-actions.component.html
- src/app/clients/clients-view/client-actions/client-actions.component.ts
- src/app/clients/clients-view/client-actions/close-client/close-client.component.html
- src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.html
- src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.scss
- src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.spec.ts
- src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.ts
- src/app/clients/clients-view/client-actions/reject-client/reject-client.component.html
- src/app/clients/clients-view/client-actions/withdraw-client/withdraw-client.component.html
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients.module.ts
> feat: client actions (reactivate)

- src/app/clients/clients-view/client-actions/client-actions.component.html
- src/app/clients/clients-view/client-actions/client-actions.component.ts
- src/app/clients/clients-view/client-actions/undo-client-rejection/undo-client-rejection.component.html
- src/app/clients/clients-view/client-actions/undo-client-rejection/undo-client-rejection.component.scss
- src/app/clients/clients-view/client-actions/undo-client-rejection/undo-client-rejection.component.spec.ts
- src/app/clients/clients-view/client-actions/undo-client-rejection/undo-client-rejection.component.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients.module.ts
> feat: client actions (undo-rejection)

- src/app/clients/clients-view/client-actions/add-client-charge/add-client-charge.component.html
- src/app/clients/clients-view/client-actions/add-client-charge/add-client-charge.component.scss
- src/app/clients/clients-view/client-actions/add-client-charge/add-client-charge.component.spec.ts
- src/app/clients/clients-view/client-actions/add-client-charge/add-client-charge.component.ts
- src/app/clients/clients-view/client-actions/client-actions.component.html
- src/app/clients/clients-view/client-actions/client-actions.component.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
- src/app/clients/common-resolvers/client-actions.resolver.ts
> feat: client actions (add-charge)

- src/app/centers/centers-view/center-actions/center-actions.component.html
- src/app/centers/centers-view/center-actions/center-actions.component.ts
- src/app/centers/centers-view/center-actions/manage-groups/manage-groups.component.html
- src/app/centers/centers-view/center-actions/manage-groups/manage-groups.component.scss
- src/app/centers/centers-view/center-actions/manage-groups/manage-groups.component.spec.ts
- src/app/centers/centers-view/center-actions/manage-groups/manage-groups.component.ts
- src/app/centers/centers-view/centers-view.component.html
- src/app/centers/centers-view/centers-view.component.ts
- src/app/centers/centers.module.ts
- src/app/centers/centers.service.ts
- src/app/centers/common-resolvers/center-actions.resolver.ts
- src/app/groups/groups.service.ts
- Add manage groups action in center module
#1106 
> feat: add centers action (manage groups)

- src/app/clients/clients-routing.module.ts
- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/clients/clients-view/general-tab/general-tab.component.scss
- src/app/clients/clients-view/general-tab/general-tab.component.ts
- src/app/clients/clients-view/view-charge/view-charge.component.html
- src/app/clients/clients-view/view-charge/view-charge.component.scss
- src/app/clients/clients-view/view-charge/view-charge.component.spec.ts
- src/app/clients/clients-view/view-charge/view-charge.component.ts
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
- src/app/clients/common-resolvers/client-charge-view.resolver.ts
Added component to view selected client charge with delete and waive flag options.
#682 
Checklist
> feat: add view client charges component

- .travis.yml
update .travis.yml file for configuration-wizard branch
#1109 
> chore: update travis for configuration-wizard branch

- src/app/clients/clients-routing.module.ts
- src/app/clients/clients-view/client-pay-charges/client-pay-charges.component.html
- src/app/clients/clients-view/client-pay-charges/client-pay-charges.component.scss
- src/app/clients/clients-view/client-pay-charges/client-pay-charges.component.spec.ts
- src/app/clients/clients-view/client-pay-charges/client-pay-charges.component.ts
- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
- src/app/clients/common-resolvers/client-transaction-pay.resolver.ts
Description
Added Charge payment component for clients.
Related issues and discussion
#689 
Screenshots, if any
Checklist
> feat: add client charge payment component

- src/app/app.module.ts
- src/app/configuration-wizard/configuration-wizard.component.html
- src/app/configuration-wizard/configuration-wizard.component.spec.ts
- src/app/configuration-wizard/configuration-wizard.component.ts
- src/app/configuration-wizard/configuration-wizard.module.ts
- src/app/configuration-wizard/configuration-wizard.service.spec.ts
- src/app/configuration-wizard/configuration-wizard.service.ts
- src/app/configuration-wizard/continue-setup-dialog/continue-setup-dialog.component.html
- src/app/configuration-wizard/continue-setup-dialog/continue-setup-dialog.component.spec.ts
- src/app/configuration-wizard/continue-setup-dialog/continue-setup-dialog.component.ts
- src/app/configuration-wizard/next-step-dialog/next-step-dialog.component.html
- src/app/configuration-wizard/next-step-dialog/next-step-dialog.component.spec.ts
- src/app/configuration-wizard/next-step-dialog/next-step-dialog.component.ts
- src/app/configuration-wizard/popover/popover-arrow.directive.ts
- src/app/configuration-wizard/popover/popover-close.directive.ts
- src/app/configuration-wizard/popover/popover-config.ts
- src/app/configuration-wizard/popover/popover-ref.ts
- src/app/configuration-wizard/popover/popover.component.html
- src/app/configuration-wizard/popover/popover.component.scss
- src/app/configuration-wizard/popover/popover.component.spec.ts
- src/app/configuration-wizard/popover/popover.component.ts
- src/app/configuration-wizard/popover/popover.service.ts
- src/assets/styles/_width-height.scss
- add configuration wizard module
- add popover component
- add step dialog components
- add configuration wizard service  
#800 
> feat: add popover component and configuration wizard module

- src/app/clients/clients-view/custom-dialogs/upload-document-dialog/upload-document-dialog.component.html
- src/app/clients/clients-view/custom-dialogs/upload-document-dialog/upload-document-dialog.component.ts
- src/app/shared/file-upload/file-upload.component.html
- src/app/shared/file-upload/file-upload.component.ts
- src/app/shared/icons.module.ts
Fixes file upload component
#1116 
> fix: file upload component

- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients-view/custom-dialogs/delete-signature-dialog/delete-signature-dialog.component.html
- src/app/clients/clients-view/custom-dialogs/delete-signature-dialog/delete-signature-dialog.component.spec.ts
- src/app/clients/clients-view/custom-dialogs/delete-signature-dialog/delete-signature-dialog.component.ts
- src/app/clients/clients-view/custom-dialogs/upload-signature-dialog/upload-signature-dialog.component.html
- src/app/clients/clients-view/custom-dialogs/upload-signature-dialog/upload-signature-dialog.component.spec.ts
- src/app/clients/clients-view/custom-dialogs/upload-signature-dialog/upload-signature-dialog.component.ts
- src/app/clients/clients-view/custom-dialogs/view-signature-dialog/view-signature-dialog.component.html
- src/app/clients/clients-view/custom-dialogs/view-signature-dialog/view-signature-dialog.component.spec.ts
- src/app/clients/clients-view/custom-dialogs/view-signature-dialog/view-signature-dialog.component.ts
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
Upload/View/Delete signature
#1119 
| Upload | View | Delete |
| --- | --- | --- |
| ![Screenshot from 2020-07-16 16-37-31](https://user-images.githubusercontent.com/54709463/87665902-4fb41080-c785-11ea-9a31-4195a6885ceb.png) | ![Screenshot from 2020-07-16 16-38-05](https://user-images.githubusercontent.com/54709463/87666062-97d33300-c785-11ea-9a4d-f5266c1395f8.png) | ![Screenshot from 2020-07-16 16-37-52](https://user-images.githubusercontent.com/54709463/87665949-665a6780-c785-11ea-9c44-dcfb32a2f590.png) |
> feat: client signature actions

- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients-view/custom-dialogs/upload-image-dialog/upload-image-dialog.component.html
- src/app/clients/clients-view/custom-dialogs/upload-image-dialog/upload-image-dialog.component.spec.ts
- src/app/clients/clients-view/custom-dialogs/upload-image-dialog/upload-image-dialog.component.ts
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
Upload and delete client image
#1121 
| Upload | Delete |
| --- | --- |
| ![Screenshot from 2020-07-17 11-44-49](https://user-images.githubusercontent.com/54709463/87755915-8a6d8580-c825-11ea-8e86-c9ad60128e13.png) | ![Screenshot from 2020-07-17 11-44-31](https://user-images.githubusercontent.com/54709463/87755932-96594780-c825-11ea-96e2-356655afe363.png) |
> feat: upload and delete client image

- src/app/loans/common-resolvers/loans-account-and-template.resolver.ts
- src/app/loans/edit-loans-account/edit-loans-account.component.html
- src/app/loans/edit-loans-account/edit-loans-account.component.spec.ts
- src/app/loans/edit-loans-account/edit-loans-account.component.ts
- src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.ts
- src/app/loans/loans-account-stepper/loans-account-preview-step/loans-account-preview-step.component.html
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/loans-view.component.ts
- src/app/loans/loans.module.ts
- src/app/loans/loans.service.ts
- Edit Loans Account 
- Minor Fixes in the loans account stepper
#220
|Details|Terms|
|--------|----------|
|![screencapture-localhost-4200-clients-1-loans-66-edit-loans-account-2020-07-18-12_17_02](https://user-images.githubusercontent.com/36980003/87849314-389c2c80-c905-11ea-9204-ea2c8f2e6c3c.png)|![screencapture-localhost-4200-clients-1-loans-66-edit-loans-account-2020-07-18-12_17_15](https://user-images.githubusercontent.com/36980003/87849318-3df97700-c905-11ea-9c67-055517804f95.png)|
|Charges Page|Preview|
|----------|----------|
|![screencapture-localhost-4200-clients-1-loans-66-edit-loans-account-2020-07-18-12_17_30](https://user-images.githubusercontent.com/36980003/87849343-7e58f500-c905-11ea-8d16-f872c432e5a4.png)|![screencapture-localhost-4200-clients-1-loans-66-edit-loans-accou …
> feat: add edit loan accounts

- src/app/system/codes/codes.component.html
- src/app/system/codes/codes.component.ts
- src/app/system/codes/create-code/create-code.component.html
- src/app/system/codes/create-code/create-code.component.ts
- src/app/system/configure-maker-checker-tasks/configure-maker-checker-tasks.component.html
- src/app/system/configure-maker-checker-tasks/configure-maker-checker-tasks.component.ts
- src/app/system/global-configurations/global-configurations.component.html
- src/app/system/global-configurations/global-configurations.component.ts
- src/app/system/manage-data-tables/create-data-table/create-data-table.component.html
- src/app/system/manage-data-tables/create-data-table/create-data-table.component.ts
- src/app/system/manage-data-tables/manage-data-tables.component.html
- src/app/system/manage-data-tables/manage-data-tables.component.ts
- src/app/system/manage-reports/manage-reports.component.html
- src/app/system/manage-reports/manage-reports.component.ts
- src/app/system/manage-scheduler-jobs/manage-scheduler-jobs.component.html
- src/app/system/manage-scheduler-jobs/manage-scheduler-jobs.component.ts
- src/app/system/roles-and-permissions/roles-and-permissions.component.html
- src/app/system/roles-and-permissions/roles-and-permissions.component.ts
- src/app/system/system.component.html
- src/app/system/system.component.ts
- src/app/users/create-user/create-user.component.html
- src/app/users/create-user/create-user.component.ts
- src/app/users/users.component.html
- src/app/users/users.component.ts
> feat: add system tour

- src/app/accounting/accounting.component.html
- src/app/accounting/accounting.component.ts
- src/app/accounting/chart-of-accounts/chart-of-accounts.component.html
- src/app/accounting/chart-of-accounts/chart-of-accounts.component.ts
- src/app/accounting/chart-of-accounts/create-gl-account/create-gl-account.component.html
- src/app/accounting/chart-of-accounts/create-gl-account/create-gl-account.component.ts
- src/app/accounting/closing-entries/closing-entries.component.html
- src/app/accounting/closing-entries/closing-entries.component.ts
- src/app/accounting/create-journal-entry/create-journal-entry.component.html
- src/app/accounting/create-journal-entry/create-journal-entry.component.ts
- src/app/accounting/financial-activity-mappings/financial-activity-mappings.component.html
- src/app/accounting/financial-activity-mappings/financial-activity-mappings.component.ts
- src/app/accounting/migrate-opening-balances/migrate-opening-balances.component.html
- src/app/accounting/migrate-opening-balances/migrate-opening-balances.component.ts
add accounting tour (configuration wizard).
#1134 
> feat: add accounting tour.

- src/app/account-transfers/account-transfers-routing.module.ts
- src/app/account-transfers/account-transfers.module.ts
- src/app/account-transfers/account-transfers.service.ts
- src/app/account-transfers/common-resolvers/view-standing-instructions.resolver.ts
- src/app/account-transfers/view-standing-instructions/view-standing-instructions.component.html
- src/app/account-transfers/view-standing-instructions/view-standing-instructions.component.scss
- src/app/account-transfers/view-standing-instructions/view-standing-instructions.component.spec.ts
- src/app/account-transfers/view-standing-instructions/view-standing-instructions.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/standing-instructions-tab/standing-instructions-tab.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-routing.module.ts
- Add view standing instruction details
#1136 
> feat: add view standing instruction details

- src/app/clients/clients-view/client-actions/client-actions.component.html
- src/app/clients/clients-view/client-actions/client-actions.component.ts
- src/app/clients/clients-view/client-actions/client-screen-reports/client-screen-reports.component.html
- src/app/clients/clients-view/client-actions/client-screen-reports/client-screen-reports.component.scss
- src/app/clients/clients-view/client-actions/client-screen-reports/client-screen-reports.component.spec.ts
- src/app/clients/clients-view/client-actions/client-screen-reports/client-screen-reports.component.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
- src/app/clients/common-resolvers/client-actions.resolver.ts
Developed view and print CSR.
#1140 
| Generate  | Print |
| --- | --- |
| ![Screenshot from 2020-07-19 13-36-27](https://user-images.githubusercontent.com/54709463/87870471-0272b180-c9c6-11ea-87d4-270b62597f1d.png) | ![Screenshot from 2020-07-19 13-36-46](https://user-images.githubusercontent.com/54709463/87870476-0ef70a00-c9c6-11ea-932b-be7ec5d41749.png) |
> feat: client actions (screen-reports)

- src/app/loans/common-resolvers/loan-action-button.resolver.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans-view/loan-account-actions/loan-screen-reports/loan-screen-reports.component.html
- src/app/loans/loans-view/loan-account-actions/loan-screen-reports/loan-screen-reports.component.scss
- src/app/loans/loans-view/loan-account-actions/loan-screen-reports/loan-screen-reports.component.spec.ts
- src/app/loans/loans-view/loan-account-actions/loan-screen-reports/loan-screen-reports.component.ts
- src/app/loans/loans.module.ts
- src/app/loans/loans.service.ts
- Add loan screen reports
#850
> feat: add loan actions (loan-screen-reports)

- src/app/products/charges/charges.component.html
- src/app/products/charges/charges.component.ts
- src/app/products/fixed-deposit-products/fixed-deposit-products.component.html
- src/app/products/fixed-deposit-products/fixed-deposit-products.component.ts
- src/app/products/loan-products/loan-products.component.html
- src/app/products/loan-products/loan-products.component.ts
- src/app/products/products-routing.module.ts
- src/app/products/products.component.html
- src/app/products/products.component.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
- src/app/products/recurring-deposit-products/recurring-deposit-product.resolver.ts
- src/app/products/recurring-deposit-products/recurring-deposit-products-template.resolver.ts
- src/app/products/recurring-deposit-products/recurring-deposit-products.component.html
- src/app/products/recurring-deposit-products/recurring-deposit-products.component.ts
- src/app/products/recurring-deposit-products/view-recurring-deposit-product/view-recurring-deposit-product.component.html
- src/app/products/recurring-deposit-products/view-recurring-deposit-product/view-recurring-deposit-product.component.scss
- src/app/products/recurring-deposit-products/view-recurring-deposit-product/view-recurring-deposit-product.component.spec.ts
- src/app/products/recurring-deposit-products/view-recurring-deposit-product/view-recurring-deposit-product.component.ts
- src/app/products/saving-products/saving-products.component.html
- src/app/products/saving-products/saving-products.component.ts
- src/app/products/share-products/share-products.component.html
- src/app/products/share-products/share-products.component.ts
add products in the configuration wizard.
#1144 1144
> feat: add products tour

- src/app/clients/clients-routing.module.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
- src/app/clients/common-resolvers/client-and-template.resolver.ts
- src/app/clients/edit-client/edit-client.component.html
- src/app/clients/edit-client/edit-client.component.scss
- src/app/clients/edit-client/edit-client.component.spec.ts
- src/app/clients/edit-client/edit-client.component.ts
> feat: add edit client page

- src/app/loans/common-resolvers/loan-action-button.resolver.ts
- src/app/loans/loans-view/loan-account-actions/approve-loan/approve-loan.component.html
- src/app/loans/loans-view/loan-account-actions/approve-loan/approve-loan.component.scss
- src/app/loans/loans-view/loan-account-actions/approve-loan/approve-loan.component.spec.ts
- src/app/loans/loans-view/loan-account-actions/approve-loan/approve-loan.component.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans.module.ts
- src/app/loans/loans.service.ts
- Add approve loan action
#829 
> feat: add loan action button (approve)

- src/app/account-transfers/account-transfers-routing.module.ts
- src/app/account-transfers/account-transfers.module.ts
- src/app/account-transfers/account-transfers.service.ts
- src/app/account-transfers/common-resolvers/make-account-transfer-template.resolver.ts
- src/app/account-transfers/make-account-transers/make-account-transers.component.html
- src/app/account-transfers/make-account-transers/make-account-transers.component.scss
- src/app/account-transfers/make-account-transers/make-account-transers.component.spec.ts
- src/app/account-transfers/make-account-transers/make-account-transers.component.ts
- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/clients/clients-view/general-tab/general-tab.component.ts
- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/loan-account-actions/create-guarantor/create-guarantor.component.ts
- src/app/loans/loans-view/loans-view.component.ts
- src/app/products/recurring-deposit-products/view-recurring-deposit-product/view-recurring-deposit-product.component.scss
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings-routing.module.ts
- Add make account transfers module
- Lazy loaded standing instructions module with loans and savings module
#251, #1060
> feat: add make account transfer (transfer-funds)

- src/app/account-transfers/account-transfers-routing.module.ts
- src/app/account-transfers/account-transfers.module.ts
- src/app/account-transfers/account-transfers.service.ts
- src/app/account-transfers/list-standing-instructions/list-standing-instructions.component.html
- src/app/account-transfers/list-standing-instructions/list-standing-instructions.component.scss
- src/app/account-transfers/list-standing-instructions/list-standing-instructions.component.spec.ts
- src/app/account-transfers/list-standing-instructions/list-standing-instructions.component.ts
- src/app/clients/clients-routing.module.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/standing-instructions-tab/standing-instructions-tab.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/standing-instructions-tab/standing-instructions-tab.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/standing-instructions-tab/standing-instructions-tab.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/standing-instructions-tab/standing-instructions-tab.component.ts
- src/app/loans/loans-view/standing-instructions-tab/standing-instructions-tab.component.html
- src/app/loans/loans-view/standing-instructions-tab/standing-instructions-tab.component.ts
- src/app/savings/savings-account-view/standing-instructions-tab/standing-instructions-tab.component.html
- src/app/savings/savings-account-view/standing-instructions-tab/standing-instructions-tab.component.ts
- Add list view standing instructions
- Add delete standing instructions
- Linked delete standing instructions in all the required modules
#267 
> feat: add list view standing instructions

- src/app/clients/client-stepper/client-address-step/client-address-step.component.html
- src/app/clients/client-stepper/client-address-step/client-address-step.component.scss
- src/app/clients/client-stepper/client-address-step/client-address-step.component.spec.ts
- src/app/clients/client-stepper/client-address-step/client-address-step.component.ts
- src/app/clients/client-stepper/client-family-members-step/client-family-member-dialog/client-family-member-dialog.component.html
- src/app/clients/client-stepper/client-family-members-step/client-family-member-dialog/client-family-member-dialog.component.spec.ts
- src/app/clients/client-stepper/client-family-members-step/client-family-member-dialog/client-family-member-dialog.component.ts
- src/app/clients/client-stepper/client-family-members-step/client-family-members-step.component.html
- src/app/clients/client-stepper/client-family-members-step/client-family-members-step.component.scss
- src/app/clients/client-stepper/client-family-members-step/client-family-members-step.component.spec.ts
- src/app/clients/client-stepper/client-family-members-step/client-family-members-step.component.ts
- src/app/clients/client-stepper/client-general-step/client-general-step.component.html
- src/app/clients/client-stepper/client-general-step/client-general-step.component.scss
- src/app/clients/client-stepper/client-general-step/client-general-step.component.spec.ts
- src/app/clients/client-stepper/client-general-step/client-general-step.component.ts
- src/app/clients/client-stepper/client-preview-step/client-preview-step.component.html
- src/app/clients/client-stepper/client-preview-step/client-preview-step.component.scss
- src/app/clients/client-stepper/client-preview-step/client-preview-step.component.spec.ts
- src/app/clients/client-stepper/client-preview-step/client-preview-step.component.ts
- src/app/clients/clients-routing.module.ts
- src/app/clients/clients.component.html
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
- src/app/clients/create-client/create-client.component.html
- src/app/clients/create-client/create-client.component.spec.ts
- src/app/clients/create-client/create-client.component.ts
Developed create client page
#215
| General | Family Members | Address | Preview |
| --- | --- | --- | --- |
| ![Screenshot from 2020-07-24 15-46-23](https://user-images.githubusercontent.com/54709463/88382368-f2900e80-cdc5-11ea-8919-765ea151c408.png) | ![Screenshot from 2020-07-24 15-46-34](https://user-images.githubusercontent.com/54709463/88382399-fe7bd080-cdc5-11ea-97f2-fb8e89c3496d.png) | ![Screenshot from 2020-07-24 15-46-45](https://user-images.githubusercontent.com/54709463/88382425-0a679280-cdc6-11ea-8961-5a71dc4cf98a.png) | ![Screenshot from 2020-07-24 15-46-57](https://user-images.githubusercontent.com/54709463/88382442-15222780-cdc6-11ea-9b7b-aa5b42594aca.png) |
> feat: add create client page

- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.scss
Fixed client header buttons
#1154 
> fix: clients header buttons

- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients-view/custom-dialogs/capture-image-dialog/capture-image-dialog.component.html
- src/app/clients/clients-view/custom-dialogs/capture-image-dialog/capture-image-dialog.component.scss
- src/app/clients/clients-view/custom-dialogs/capture-image-dialog/capture-image-dialog.component.spec.ts
- src/app/clients/clients-view/custom-dialogs/capture-image-dialog/capture-image-dialog.component.ts
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
Developed custom image capture dialog component
#1129 
> feat: add image capture dialog

- src/app/account-transfers/account-transfers-routing.module.ts
- src/app/account-transfers/account-transfers.module.ts
- src/app/account-transfers/account-transfers.service.ts
- src/app/account-transfers/common-resolvers/list-transactions.resolver.ts
- src/app/account-transfers/edit-standing-instructions/edit-standing-instructions.component.ts
- src/app/account-transfers/list-standing-instructions/list-standing-instructions.component.html
- src/app/account-transfers/list-standing-instructions/list-standing-instructions.component.scss
- src/app/account-transfers/list-standing-instructions/list-standing-instructions.component.ts
- src/app/account-transfers/list-transactions/list-transactions.component.html
- src/app/account-transfers/list-transactions/list-transactions.component.scss
- src/app/account-transfers/list-transactions/list-transactions.component.spec.ts
- src/app/account-transfers/list-transactions/list-transactions.component.ts
- src/app/account-transfers/view-standing-instructions/view-standing-instructions.component.html
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- Add view transactions history page
#1156 
> feat: add view transactions history

- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
- src/app/products/recurring-deposit-products/edit-recurring-deposit-product/edit-recurring-deposit-product.component.html
- src/app/products/recurring-deposit-products/edit-recurring-deposit-product/edit-recurring-deposit-product.component.spec.ts
- src/app/products/recurring-deposit-products/edit-recurring-deposit-product/edit-recurring-deposit-product.component.ts
- src/app/products/recurring-deposit-products/edit-recurring-deposit-product/recurring-deposit-product-and-template.resolver.ts
- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-accounting-step/recurring-deposit-product-accounting-step.component.ts
- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-charges-step/recurring-deposit-product-charges-step.component.ts
- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-currency-step/recurring-deposit-product-currency-step.component.ts
- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-details-step/recurring-deposit-product-details-step.component.html
- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-details-step/recurring-deposit-product-details-step.component.ts
- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-interest-rate-chart-step/recurring-deposit-product-interest-rate-chart-step.component.ts
- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-settings-step/recurring-deposit-product-settings-step.component.ts
- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-terms-step/recurring-deposit-product-terms-step.component.ts
- src/app/products/recurring-deposit-products/recurring-deposit-products.component.html
- src/app/products/recurring-deposit-products/view-recurring-deposit-product/view-recurring-deposit-product.component.html
- Add edit recurring deposit product
#468 
|Details | Currency|Terms|
|-------|------------|---------|
|![screencapture-localhost-4200-products-recurring-deposit-products-36-edit-2020-08-01-11_43_14](https://user-images.githubusercontent.com/36980003/89095850-3fd83580-d3ef-11ea-9aee-901fffa568a7.png)|![screencapture-localhost-4200-products-recurring-deposit-products-36-edit-2020-08-01-11_43_22](https://user-images.githubusercontent.com/36980003/89095853-42d32600-d3ef-11ea-9cef-c6874da4569b.png)|![screencapture-localhost-4200-products-recurring-deposit-products-36-edit-2020-08-01-11_43_31](https://user-images.githubusercontent.com/36980003/89095857-4b2b6100-d3ef-11ea-96a4-b57580e2352c.png)|
|Settings|Interest Rate Charts|Charges|
|--------------|--------------|--------------| …
> feat: add edit recurring deposit product

- src/app/organization/organization.service.ts
- src/app/organization/sms-campaigns/view-campaign/view-campaign.component.html
- src/app/organization/sms-campaigns/view-campaign/view-campaign.component.ts
Developed activate/close/delete/reactivate actions
#1163 
| Close | Reactivate | Activate | Delete |
| --- | --- | --- | --- |
| ![Screenshot from 2020-08-01 18-22-43](https://user-images.githubusercontent.com/54709463/89102174-2ef5e700-d424-11ea-858f-ece4bd2f27d5.png) | ![Screenshot from 2020-08-01 18-23-30](https://user-images.githubusercontent.com/54709463/89102181-492fc500-d424-11ea-85c8-4954d2a9dfc0.png) | ![Screenshot from 2020-08-01 18-23-01](https://user-images.githubusercontent.com/54709463/89102188-58167780-d424-11ea-9c1c-731305dc4b48.png) | ![Screenshot from 2020-08-01 18-23-19](https://user-images.githubusercontent.com/54709463/89102195-6369a300-d424-11ea-955d-020a0e8e3713.png) |
> feat: multiple sms campaign actions

- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
- src/app/products/share-products/create-dividend/create-dividend.component.html
- src/app/products/share-products/create-dividend/create-dividend.component.scss
- src/app/products/share-products/create-dividend/create-dividend.component.spec.ts
- src/app/products/share-products/create-dividend/create-dividend.component.ts
- src/app/products/share-products/dividends-share-product/dividends.component.html
Create Dividend component added.
#770 
> feat: add create dividend component

- src/app/organization/entity-data-table-checks/create-enity-data-table-checks/create-enity-data-table-checks.component.html
- src/app/organization/entity-data-table-checks/create-enity-data-table-checks/create-enity-data-table-checks.component.scss
- src/app/organization/entity-data-table-checks/create-enity-data-table-checks/create-enity-data-table-checks.component.spec.ts
- src/app/organization/entity-data-table-checks/create-enity-data-table-checks/create-enity-data-table-checks.component.ts
- src/app/organization/entity-data-table-checks/enitity-data-table-checks-template.resolver.ts
- src/app/organization/entity-data-table-checks/entity-data-table-checks.component.html
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
Added Create Entity Data Table Checks component.
#751 
> feat: add create entity data table checks

- src/app/clients/clients.component.html
- src/app/clients/clients.component.ts
- src/app/clients/clients.datasource.ts
Client search using client name and filter the active and inactive accounts from the check bob completed.
#445 
> fix: clients view search field

- src/app/organization/bulk-loan-reassignmnet/bulk-loan-reassignmnet.component.html
- src/app/organization/bulk-loan-reassignmnet/bulk-loan-reassignmnet.component.scss
- src/app/organization/bulk-loan-reassignmnet/bulk-loan-reassignmnet.component.spec.ts
- src/app/organization/bulk-loan-reassignmnet/bulk-loan-reassignmnet.component.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.component.html
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
Component for Bulk Loan Reassignment created.
#754 
> feat: add bulk loan reassignment component

- src/app/organization/loan-provisioning-criteria/common-resolvers/loan-provisioning-criteria-template.resolver.ts
- src/app/organization/loan-provisioning-criteria/common-resolvers/loan-provisioning-criteria.resolver.ts
- src/app/organization/loan-provisioning-criteria/common-resolvers/loan-provisioning-criterias.resolver.ts
- src/app/organization/loan-provisioning-criteria/create-loan-provisioning-criteria/create-loan-provisioning-criteria.component.html
- src/app/organization/loan-provisioning-criteria/create-loan-provisioning-criteria/create-loan-provisioning-criteria.component.spec.ts
- src/app/organization/loan-provisioning-criteria/create-loan-provisioning-criteria/create-loan-provisioning-criteria.component.ts
- src/app/organization/loan-provisioning-criteria/loan-provisioning-criteria.component.html
- src/app/organization/loan-provisioning-criteria/view-loan-provisioning-criteria/view-loan-provisioning-criteria.component.html
- src/app/organization/loan-provisioning-criteria/view-loan-provisioning-criteria/view-loan-provisioning-criteria.component.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
Developed create loan provisioning criteria
#570 
> feat: add create loan provisioning criteria

- src/app/organization/loan-provisioning-criteria/common-resolvers/loan-provisioning-criteria-and-template.resolver.ts
- src/app/organization/loan-provisioning-criteria/edit-loan-provisioning-criteria/edit-loan-provisioning-criteria.component.html
- src/app/organization/loan-provisioning-criteria/edit-loan-provisioning-criteria/edit-loan-provisioning-criteria.component.spec.ts
- src/app/organization/loan-provisioning-criteria/edit-loan-provisioning-criteria/edit-loan-provisioning-criteria.component.ts
- src/app/organization/loan-provisioning-criteria/view-loan-provisioning-criteria/view-loan-provisioning-criteria.component.html
- src/app/organization/loan-provisioning-criteria/view-loan-provisioning-criteria/view-loan-provisioning-criteria.component.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
Developed edit provisioning criteria page
#644 
> feat: add edit provisioning criteria 

- src/app/app.module.ts
- src/app/core/shell/sidenav/sidenav.component.html
- src/app/notifications/notifications-page/notifications-page.component.html
- src/app/notifications/notifications-page/notifications-page.component.spec.ts
- src/app/notifications/notifications-page/notifications-page.component.ts
- src/app/notifications/notifications-routing.module.ts
- src/app/notifications/notifications.module.ts
- src/app/notifications/notifications.resolver.ts
- src/app/notifications/notifications.service.spec.ts
- src/app/notifications/notifications.service.ts
Developed notifications view page
#1169 
> feat: add view notifications page

- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-preview-step/fixed-deposit-product-preview-step.component.html
- src/app/products/fixed-deposit-products/fixed-deposit-product.resolver.ts
- src/app/products/fixed-deposit-products/fixed-deposit-products.component.html
- src/app/products/fixed-deposit-products/view-fixed-deposit-product/view-fixed-deposit-product.component.html
- src/app/products/fixed-deposit-products/view-fixed-deposit-product/view-fixed-deposit-product.component.scss
- src/app/products/fixed-deposit-products/view-fixed-deposit-product/view-fixed-deposit-product.component.spec.ts
- src/app/products/fixed-deposit-products/view-fixed-deposit-product/view-fixed-deposit-product.component.ts
- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
add view fixed deposit product component.
#465 
> feat: add view fixed deposit product component

- src/app/core/core.module.ts
- src/app/core/shell/toolbar/toolbar.component.html
- src/app/notifications/notifications-page/notifications-page.component.html
- src/app/notifications/notifications-page/notifications-page.component.scss
- src/app/notifications/notifications-page/notifications-page.component.ts
- src/app/notifications/notifications-tray/notifications-tray.component.html
- src/app/notifications/notifications-tray/notifications-tray.component.scss
- src/app/notifications/notifications-tray/notifications-tray.component.spec.ts
- src/app/notifications/notifications-tray/notifications-tray.component.ts
- src/app/notifications/notifications.module.ts
- src/app/notifications/notifications.service.ts
- src/app/shared/material.module.ts
Developed notifications tray component
#1171 
> feat: add notifications tray component

- src/app/products/manage-tax-groups/create-tax-group/create-tax-group.component.html
- src/app/products/manage-tax-groups/create-tax-group/create-tax-group.component.scss
- src/app/products/manage-tax-groups/create-tax-group/create-tax-group.component.spec.ts
- src/app/products/manage-tax-groups/create-tax-group/create-tax-group.component.ts
- src/app/products/manage-tax-groups/create-tax-group/manage-tax-group-template.resolver.ts
- src/app/products/manage-tax-groups/edit-tax-group/edit-tax-group.component.html
- src/app/products/manage-tax-groups/edit-tax-group/edit-tax-group.component.scss
- src/app/products/manage-tax-groups/edit-tax-group/edit-tax-group.component.spec.ts
- src/app/products/manage-tax-groups/edit-tax-group/edit-tax-group.component.ts
- src/app/products/manage-tax-groups/edit-tax-group/edit-tax-group.resolver.ts
- src/app/products/manage-tax-groups/manage-tax-groups.component.html
- src/app/products/manage-tax-groups/tax-group.resolver.ts
- src/app/products/manage-tax-groups/view-tax-group/view-tax-group.component.html
- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
- Add create tax groups
- Add edit tax groups 
#589 #600
|Create Tax Group| Add/Edit Tax Component| Delete Tax Component|
|---------------------|------------------------------|---------------------|
|![screencapture-localhost-4200-products-tax-configurations-tax-groups-create-2020-08-04-13_50_38](https://user-images.githubusercontent.com/36980003/89292715-6bbb1b80-d67a-11ea-93be-4be91cd2ba49.png)|![screencapture-localhost-4200-products-tax-configurations-tax-groups-create-2020-08-04-13_50_49](https://user-images.githubusercontent.com/36980003/89292727-707fcf80-d67a-11ea-90c1-bc544efc1f38.png)|![screencapture-localhost-4200-products-tax-configurations-tax-groups-create-2020-08-04-13_50_58](https://user-images.githubusercontent.com/36980003/89292735-75448380-d67a-11ea-84d7-2bd6be7a5f15.png)| …
> feat: add create, add tax groups

- src/app/products/manage-tax-groups/create-tax-group/create-tax-group.component.ts
- src/app/products/products-mix/create-product-mix/create-product-mix.component.html
- src/app/products/products-mix/create-product-mix/create-product-mix.component.scss
- src/app/products/products-mix/create-product-mix/create-product-mix.component.spec.ts
- src/app/products/products-mix/create-product-mix/create-product-mix.component.ts
- src/app/products/products-mix/edit-product-mix/edit-product-mix.component.html
- src/app/products/products-mix/edit-product-mix/edit-product-mix.component.scss
- src/app/products/products-mix/edit-product-mix/edit-product-mix.component.spec.ts
- src/app/products/products-mix/edit-product-mix/edit-product-mix.component.ts
- src/app/products/products-mix/products-mix-template.resolver.ts
- src/app/products/products-mix/products-mix.component.html
- src/app/products/products-mix/view-product-mix/view-product-mix.component.html
- src/app/products/products-mix/view-product-mix/view-product-mix.component.ts
- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
- Add create product mix component
- Add edit product mix component
- Add delete product mix component
#196 
|Create Product Mix |Edit Product Mix|Delete|
|-----------------|------------------|---------------------------|
|![screencapture-localhost-4200-products-products-mix-create-2020-08-05-11_14_57](https://user-images.githubusercontent.com/36980003/89380257-d6b93080-d714-11ea-8550-505be291c7c1.png)|![screencapture-localhost-4200-products-products-mix-1-edit-2020-08-05-11_15_22](https://user-images.githubusercontent.com/36980003/89380345-f6e8ef80-d714-11ea-964a-3bbaf10d0efb.png)|![screencapture-localhost-4200-products-products-mix-1-2020-08-05-11_15_36](https://user-images.githubusercontent.com/36980003/89380277-df116b80-d714-11ea-8bcf-c38534e23f93.png)|
Please make sure these boxes …
> feat: add product mix component functionality

- src/app/products/charges/charges-template-and-resolver.ts
- src/app/products/charges/charges-template.resolver.ts
- src/app/products/charges/charges.component.html
- src/app/products/charges/create-charge/create-charge.component.html
- src/app/products/charges/create-charge/create-charge.component.scss
- src/app/products/charges/create-charge/create-charge.component.spec.ts
- src/app/products/charges/create-charge/create-charge.component.ts
- src/app/products/charges/edit-charge/edit-charge.component.html
- src/app/products/charges/view-charge/view-charge.component.html
- src/app/products/products-mix/create-product-mix/create-product-mix.component.html
- src/app/products/products-mix/edit-product-mix/edit-product-mix.component.html
- src/app/products/products-mix/products-mix.component.html
- src/app/products/products-mix/view-product-mix/view-product-mix.component.html
- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
- Add create charge component. Further details and discussions on the PR can be found at #553
- Add permissions wherever required
#191
> feat: add create charge component

- src/app/products/fixed-deposit-products/edit-fixed-deposit-product/edit-fixed-deposit-product.component.html
- src/app/products/fixed-deposit-products/edit-fixed-deposit-product/edit-fixed-deposit-product.component.spec.ts
- src/app/products/fixed-deposit-products/edit-fixed-deposit-product/edit-fixed-deposit-product.component.ts
- src/app/products/fixed-deposit-products/edit-fixed-deposit-product/fixed-deposit-product-and-template.resolver.ts
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-accounting-step/fixed-deposit-product-accounting-step.component.ts
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-charges-step/fixed-deposit-product-charges-step.component.ts
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-currency-step/fixed-deposit-product-currency-step.component.ts
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-details-step/fixed-deposit-product-details-step.component.html
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-details-step/fixed-deposit-product-details-step.component.ts
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-interest-rate-chart-step/fixed-deposit-product-interest-rate-chart-step.component.ts
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-settings-step/fixed-deposit-product-settings-step.component.ts
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-terms-step/fixed-deposit-product-terms-step.component.ts
- src/app/products/fixed-deposit-products/view-fixed-deposit-product/view-fixed-deposit-product.component.html
- src/app/products/products-routing.module.ts
- src/app/products/products.module.ts
- src/app/products/products.service.ts
- Add edit fixed deposits product
#466
> feat: add edit fixed deposits product

- src/app/organization/fund-mapping/advance-search-template.resolver.ts
- src/app/organization/fund-mapping/fund-mapping.component.html
- src/app/organization/fund-mapping/fund-mapping.component.scss
- src/app/organization/fund-mapping/fund-mapping.component.spec.ts
- src/app/organization/fund-mapping/fund-mapping.component.ts
- src/app/organization/organization-routing.module.ts
- src/app/organization/organization.component.html
- src/app/organization/organization.module.ts
- src/app/organization/organization.service.ts
Developed fund mapping component
#1179 
> feat: loans advanced search (fund-mapping) component

- package-lock.json
- package.json
CKEditor5 angular v1.2.3
CKEDitor5 classic build v21.0.0
#1181 
> build: CKEditor5

- src/app/templates/common-resolvers/create-template.resolver.ts
- src/app/templates/create-template/create-template.component.html
- src/app/templates/create-template/create-template.component.scss
- src/app/templates/create-template/create-template.component.spec.ts
- src/app/templates/create-template/create-template.component.ts
- src/app/templates/templates-routing.module.ts
- src/app/templates/templates.component.html
- src/app/templates/templates.module.ts
- src/app/templates/templates.service.ts
Developed create template page
#1184 
> feat: add create template component

- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-interest-rate-chart-step/recurring-deposits-account-interest-rate-chart-step.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-interest-rate-chart-step/recurring-deposits-account-interest-rate-chart-step.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-interest-rate-chart-step/recurring-deposits-account-interest-rate-chart-step.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-preview-step/recurring-deposits-account-preview-step.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-preview-step/recurring-deposits-account-preview-step.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-preview-step/recurring-deposits-account-preview-step.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/interest-rate-chart-tab/interest-rate-chart-tab.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/interest-rate-chart-tab/interest-rate-chart-tab.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/interest-rate-chart-tab/interest-rate-chart-tab.component.ts
- Add view and hide incentives in recurring deposits account
#1186 
> feat: add view incentives (recurring deposits account)

- src/app/core/core.module.ts
- src/app/core/shell/toolbar/toolbar.component.html
- src/app/core/shell/toolbar/toolbar.component.ts
- src/app/search/search-page/search-page.component.html
- src/app/search/search-page/search-page.component.scss
- src/app/search/search-page/search-page.component.spec.ts
- src/app/search/search-page/search-page.component.ts
- src/app/search/search-routing.module.ts
- src/app/search/search-tool/search-tool.component.html
- src/app/search/search-tool/search-tool.component.scss
- src/app/search/search-tool/search-tool.component.spec.ts
- src/app/search/search-tool/search-tool.component.ts
- src/app/search/search.module.ts
- src/app/search/search.resolver.ts
- src/app/search/search.service.spec.ts
- src/app/search/search.service.ts
Developed master search tool and page
#1189 
| Tool | Results Page |
| --- | --- |
| ![Screenshot from 2020-08-10 16-37-42](https://user-images.githubusercontent.com/54709463/89776634-ea570380-db27-11ea-9928-fd79e0747fc8.png) | ![Screenshot from 2020-08-10 16-40-56](https://user-images.githubusercontent.com/54709463/89776852-4de13100-db28-11ea-8183-1541e948a1fe.png) |
> feat: master search tool and page

- src/app/centers/centers-view/center-actions/center-actions.component.html
- src/app/centers/centers-view/center-actions/center-actions.component.ts
- src/app/centers/centers-view/center-actions/staff-assignment-history/staff-assignment-history.component.html
- src/app/centers/centers-view/center-actions/staff-assignment-history/staff-assignment-history.component.scss
- src/app/centers/centers-view/center-actions/staff-assignment-history/staff-assignment-history.component.spec.ts
- src/app/centers/centers-view/center-actions/staff-assignment-history/staff-assignment-history.component.ts
- src/app/centers/centers-view/centers-view.component.html
- src/app/centers/centers-view/centers-view.component.ts
- src/app/centers/centers.module.ts
- src/app/centers/centers.service.ts
- src/app/centers/common-resolvers/center-actions.resolver.ts
- Add view staff assignment history action using reports
#1193 
> feat: add centers action (staff assignment history)

- src/app/groups/common-resolvers/group-actions.resolver.ts
- src/app/groups/edit-group/edit-group.component.ts
- src/app/groups/groups-view/add-role/add-role.component.html
- src/app/groups/groups-view/add-role/add-role.component.ts
- src/app/groups/groups-view/group-actions/activate-group/activate-group.component.ts
- src/app/groups/groups-view/group-actions/attach-group-meeting/attach-group-meeting.component.html
- src/app/groups/groups-view/group-actions/close-group/close-group.component.html
- src/app/groups/groups-view/group-actions/close-group/close-group.component.ts
- src/app/groups/groups-view/group-actions/edit-group-meeting-schedule/edit-group-meeting-schedule.component.html
- src/app/groups/groups-view/group-actions/edit-group-meeting/edit-group-meeting.component.html
- src/app/groups/groups-view/group-actions/group-actions.component.ts
- src/app/groups/groups-view/group-actions/group-assign-staff/group-assign-staff.component.ts
- src/app/groups/groups-view/group-actions/group-attendance/group-attendance.component.html
- src/app/groups/groups-view/group-actions/group-transfer-clients/group-transfer-clients.component.html
- src/app/groups/groups-view/group-actions/group-transfer-clients/group-transfer-clients.component.ts
- src/app/groups/groups-view/group-actions/manage-group-members/manage-group-members.component.ts
- src/app/groups/groups-view/groups-view.component.html
- src/app/groups/groups-view/groups-view.component.ts
- src/app/groups/groups-view/notes-tab/notes-tab.component.ts
- src/app/groups/groups.component.html
- src/app/groups/groups.component.ts
- src/app/groups/groups.service.ts
> refactor: groups module

- src/app/templates/create-template/create-template.component.ts
- src/app/templates/templates.component.html
- src/app/templates/templates.component.ts
- src/app/templates/templates.module.ts
- src/app/templates/view-template/view-template.component.html
- src/app/templates/view-template/view-template.component.ts
> refactor: templates module

- src/app/shared/cancel-dialog/cancel-dialog.component.html
- src/app/shared/cancel-dialog/cancel-dialog.component.spec.ts
- src/app/shared/cancel-dialog/cancel-dialog.component.ts
- src/app/shared/material.module.ts
- src/app/shared/shared.module.ts
- src/app/system/manage-surveys/create-survey/create-survey.component.html
- src/app/system/manage-surveys/create-survey/create-survey.component.scss
- src/app/system/manage-surveys/create-survey/create-survey.component.spec.ts
- src/app/system/manage-surveys/create-survey/create-survey.component.ts
- src/app/system/manage-surveys/manage-surveys.component.html
- src/app/system/system-routing.module.ts
- src/app/system/system.module.ts
- src/app/system/system.service.ts
- Add create survey component
- **Country Codes**: Must be two alphabetic characters. They can be lower or uppercase but they will be patched to uppercase on submit [new]
- **Value**: Must be between -9999 and 9999
- **Questions**: Can only delete questions only until one is left. (removes need to validate for empty surveys) [new]
- **Responses**: Can only delete response until there is only one left in that question (removes need to validate for empty questions) [new]
- **Key**: Restricted to 32 characters long through maxlength
- **Text**: Restricted to 255 characters long through maxlength
- **Name**: Restricted to 255 characters long through maxlength
- At the moment, if users have decided that they want a new question to be added, they can only add it at the end. 
- If they want it …
> feat: add create survey component

- src/app/clients/clients-routing.module.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/notifications/notifications-page/notifications-page.component.ts
- src/app/notifications/notifications-tray/notifications-tray.component.ts
- src/app/search/search-page/search-page.component.ts
- src/app/shares/common-resolvers/share-account-actions.resolver.ts
- src/app/shares/edit-shares-account/edit-shares-account.component.ts
- src/app/shares/shares-account-actions/apply-shares/apply-shares.component.ts
- src/app/shares/shares-account-actions/approve-shares/approve-shares.component.ts
- src/app/shares/shares-account-actions/redeem-shares/redeem-shares.component.ts
- src/app/shares/shares-account-actions/reject-shares/reject-shares.component.ts
- src/app/shares/shares-account-actions/shares-account-actions.component.html
- src/app/shares/shares-account-actions/shares-account-actions.component.ts
- src/app/shares/shares-account-view/shares-account-view.component.html
- src/app/shares/shares-account-view/shares-account-view.component.ts
- src/app/shares/shares-routing.module.ts
- src/app/shares/shares.service.ts
> refactor: shares module

- src/app/clients/clients-view/clients-view.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-stepper/fixed-deposit-account-currency-step/fixed-deposit-account-currency-step.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-stepper/fixed-deposit-account-interest-rate-chart-step/fixed-deposit-account-interest-rate-chart-step.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/custom-dialogs/inactivate-charge-dialog/inactivate-charge-dialog.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/fixed-deposit-account-view.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/standing-instructions-tab/standing-instructions-tab.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/transactions-tab/transactions-tab.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/view-transaction/view-transaction.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-routing.module.ts
- src/app/deposits/fixed-deposits/fixed-deposits.module.ts
- src/app/deposits/fixed-deposits/fixed-deposits.service.ts
> refactor: fixed deposits module

- src/app/accounting/accounting-rules/accounting-rules.component.html
- src/app/accounting/accounting-rules/create-rule/create-rule.component.html
- src/app/accounting/accounting-rules/edit-rule/edit-rule.component.html
- src/app/accounting/accounting-rules/view-rule/view-rule.component.html
- src/app/accounting/chart-of-accounts/chart-of-accounts.component.html
- src/app/accounting/chart-of-accounts/create-gl-account/create-gl-account.component.html
- src/app/accounting/chart-of-accounts/edit-gl-account/edit-gl-account.component.html
- src/app/accounting/chart-of-accounts/view-gl-account/view-gl-account.component.html
- src/app/accounting/closing-entries/closing-entries.component.html
- src/app/accounting/closing-entries/create-closure/create-closure.component.html
- src/app/accounting/closing-entries/view-closure/view-closure.component.html
- src/app/accounting/create-journal-entry/create-journal-entry.component.html
- src/app/accounting/financial-activity-mappings/create-financial-activity-mapping/create-financial-activity-mapping.component.html
- src/app/accounting/financial-activity-mappings/edit-financial-activity-mapping/edit-financial-activity-mapping.component.html
- src/app/accounting/financial-activity-mappings/financial-activity-mappings.component.html
- src/app/accounting/financial-activity-mappings/view-financial-activity-mapping/view-financial-activity-mapping.component.html
- src/app/accounting/frequent-postings/frequent-postings.component.html
- src/app/accounting/migrate-opening-balances/migrate-opening-balances.component.html
- src/app/accounting/periodic-accruals/periodic-accruals.component.html
- src/app/accounting/provisioning-entries/create-provisioning-entry/create-provisioning-entry.component.html
- src/app/accounting/provisioning-entries/provisioning-entries.component.html
- src/app/accounting/provisioning-entries/view-provisioning-entry/view-provisioning-entry.component.html
- src/app/accounting/view-transaction/view-transaction.component.html
Refactored Accounting Module for Permissions
#1196 
> refactor: accounting module

- src/app/app.module.ts
- src/app/collections/collections-routing.module.ts
- src/app/collections/collections.module.ts
- src/app/collections/collections.service.spec.ts
- src/app/collections/collections.service.ts
- src/app/collections/individual-collection-sheet/get-offices.resolver.ts
- src/app/collections/individual-collection-sheet/individual-collection-sheet.component.html
- src/app/collections/individual-collection-sheet/individual-collection-sheet.component.scss
- src/app/collections/individual-collection-sheet/individual-collection-sheet.component.spec.ts
- src/app/collections/individual-collection-sheet/individual-collection-sheet.component.ts
- src/app/core/shell/sidenav/sidenav.component.html
- Add individual collection sheet 
#255 
|Parameters|Details|
|-----------|--------------|
|![screencapture-localhost-4200-collections-individual-collection-sheet-2020-08-15-01_47_38](https://user-images.githubusercontent.com/36980003/90304931-87c08780-deda-11ea-9b53-d21e45eec327.png)|![screencapture-localhost-4200-collections-individual-collection-sheet-2020-08-15-01_48_32](https://user-images.githubusercontent.com/36980003/90304932-8b540e80-deda-11ea-9802-b90b3309d19b.png)|
> feat: add individual collection sheet

- src/app/loans/common-resolvers/loans-account-transaction-template.resolver.ts
- src/app/loans/common-resolvers/loans-account-transaction.resolver.ts
- src/app/loans/common-resolvers/loans-transaction-reciept.resolver.ts
- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/loan-account-actions/create-guarantor/create-guarantor.component.ts
- src/app/loans/loans-view/transactions-tab/transactions-tab.component.html
- src/app/loans/loans-view/transactions-tab/transactions-tab.component.scss
- src/app/loans/loans-view/transactions-tab/transactions-tab.component.ts
- src/app/loans/loans-view/transactions/edit-transaction/edit-transaction.component.html
- src/app/loans/loans-view/transactions/edit-transaction/edit-transaction.component.scss
- src/app/loans/loans-view/transactions/edit-transaction/edit-transaction.component.spec.ts
- src/app/loans/loans-view/transactions/edit-transaction/edit-transaction.component.ts
- src/app/loans/loans-view/transactions/export-transactions/export-transactions.component.html
- src/app/loans/loans-view/transactions/export-transactions/export-transactions.component.scss
- src/app/loans/loans-view/transactions/export-transactions/export-transactions.component.spec.ts
- src/app/loans/loans-view/transactions/export-transactions/export-transactions.component.ts
- src/app/loans/loans-view/transactions/view-reciept/view-reciept.component.html
- src/app/loans/loans-view/transactions/view-reciept/view-reciept.component.scss
- src/app/loans/loans-view/transactions/view-reciept/view-reciept.component.spec.ts
- src/app/loans/loans-view/transactions/view-reciept/view-reciept.component.ts
- src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.html
- src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.scss
- src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.spec.ts
- src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.ts
- src/app/loans/loans.module.ts
- src/app/loans/loans.service.ts
- Add export transaction
- Add view transactions
- Add edit transactions
- Add undo transactions
- Add view receipt
#1205
|View transaction|Edit Transaction| Export Transaction|Reciept|
|-----------------------|---------------------|--------------------------|----------|
|![screencapture-localhost-4200-clients-1-loans-3671-transactions-3682511-2020-08-15-13_35_25](https://user-images.githubusercontent.com/36980003/90310169-accdee00-df0c-11ea-9a1e-690007365dd8.png)|![screencapture-localhost-4200-clients-1-loans-3671-transactions-3682511-edit-2020-08-15-13_35_14](https://user-images.githubusercontent.com/36980003/90310175-b5bebf80-df0c-11ea-8fb2-1e6e585c8626.png)|![Screenshot from 2020-08-15 13-14-38](https://user-images.githubusercontent.com/36980003/90310188-db4bc900-df0c-11ea-9862-557f48c …
> feat: add loan transactions tab actions

- src/app/app.module.ts
- src/app/core/shell/sidenav/sidenav.component.ts
- src/app/core/shell/toolbar/toolbar.component.html
- src/app/core/shell/toolbar/toolbar.component.ts
- src/app/profile/profile-routing.module.ts
- src/app/profile/profile.component.html
- src/app/profile/profile.component.scss
- src/app/profile/profile.component.spec.ts
- src/app/profile/profile.component.ts
- src/app/profile/profile.module.ts
Developed user profile page
#1208 
> feat: user profile page

- src/app/core/shell/sidenav/frequent-activities.ts
- src/app/core/shell/sidenav/sidenav.component.html
- src/app/core/shell/sidenav/sidenav.component.ts
- src/app/shared/icons.module.ts
Automate frequent activities
#1210 
> feat: automate frequent activities

- src/app/system/account-number-preferences/account-number-preferences.component.html
- src/app/system/account-number-preferences/create-account-number-preference/create-account-number-preference.component.html
- src/app/system/account-number-preferences/edit-account-number-preference/edit-account-number-preference.component.html
- src/app/system/account-number-preferences/view-account-number-preference/view-account-number-preference.component.html
- src/app/system/codes/codes.component.html
- src/app/system/codes/create-code/create-code.component.html
- src/app/system/codes/edit-code/edit-code.component.html
- src/app/system/codes/view-code/view-code.component.html
- src/app/system/manage-data-tables/edit-data-table/edit-data-table.component.html
- src/app/system/manage-data-tables/manage-data-tables.component.html
- src/app/system/manage-data-tables/view-data-table/view-data-table.component.html
- src/app/system/manage-hooks/create-hook/create-hook.component.html
- src/app/system/manage-hooks/edit-hook/edit-hook.component.html
- src/app/system/manage-hooks/manage-hooks.component.html
- src/app/system/manage-hooks/view-hook/view-hook.component.html
- src/app/system/manage-reports/create-report/create-report.component.html
- src/app/system/manage-reports/edit-report/edit-report.component.html
- src/app/system/manage-reports/manage-reports.component.html
- src/app/system/manage-reports/view-report/view-report.component.html
- src/app/system/manage-scheduler-jobs/edit-scheduler-job/edit-scheduler-job.component.html
- src/app/system/system.service.ts
- Add permissions in the system module
#1196 
> feat: add mifos permissions in system module

- src/app/organization/offices/create-office/create-office.component.ts
- src/app/settings/settings.component.html
- src/app/settings/settings.component.ts
- src/app/settings/settings.service.spec.ts
- src/app/settings/settings.service.ts
- src/app/web-app.component.ts
Developed settings service to centralize language and df
#1213 
> feat: initialize language and date-format settings

- src/app/account-transfers/account-transfers.service.ts
- src/app/account-transfers/common-resolvers/list-transactions.resolver.ts
- src/app/account-transfers/create-standing-instructions/create-standing-instructions.component.ts
- src/app/account-transfers/edit-standing-instructions/edit-standing-instructions.component.html
- src/app/account-transfers/edit-standing-instructions/edit-standing-instructions.component.ts
- src/app/account-transfers/list-standing-instructions/list-standing-instructions.component.ts
- src/app/account-transfers/make-account-transfers/make-account-transfers.component.ts
Added centralized date formats and languages in account transfers module. 
#1213 
> refactor: Account transfers

- src/app/products/products-routing.module.ts
- src/app/shared/error-dialog/error-dialog.component.html
- src/app/shared/error-dialog/error-dialog.component.spec.ts
- src/app/shared/error-dialog/error-dialog.component.ts
- src/app/shared/shared.module.ts
- src/app/system/manage-scheduler-jobs/view-history-scheduler-job/view-history-scheduler-job.component.html
- src/app/system/manage-scheduler-jobs/view-history-scheduler-job/view-history-scheduler-job.component.scss
- src/app/system/manage-scheduler-jobs/view-history-scheduler-job/view-history-scheduler-job.component.spec.ts
- src/app/system/manage-scheduler-jobs/view-history-scheduler-job/view-history-scheduler-job.component.ts
- src/app/system/manage-scheduler-jobs/view-history-scheduler-job/view-history-scheduler-job.resolver.ts
- src/app/system/system-routing.module.ts
- src/app/system/system.module.ts
- src/app/system/system.service.ts
Component to view the history of the selected job. Also the items should be filtered according to the version.
#675 
> feat: view scheduler job history component

- src/app/centers/centers-routing.module.ts
- src/app/centers/centers-view/centers-view.component.html
- src/app/centers/centers-view/general-tab/general-tab.component.html
- src/app/centers/centers-view/general-tab/general-tab.component.ts
- src/app/clients/clients-routing.module.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/groups/groups-routing.module.ts
- src/app/groups/groups-view/general-tab/general-tab.component.html
- src/app/groups/groups-view/general-tab/general-tab.component.ts
- src/app/groups/groups-view/groups-view.component.html
- src/app/notifications/notifications-page/notifications-page.component.ts
- src/app/savings/common-resolvers/savings-account-actions.resolver.ts
- src/app/savings/common-resolvers/savings-account-template.resolver.ts
- src/app/savings/create-savings-account/create-savings-account.component.ts
- src/app/savings/edit-savings-account/edit-savings-account.component.ts
- src/app/savings/saving-account-actions/apply-annual-fees-savings-account/apply-annual-fees-savings-account.component.ts
- src/app/savings/saving-account-actions/close-savings-account/close-savings-account.component.ts
- src/app/savings/savings-account-stepper/savings-account-charges-step/savings-account-charges-step.component.ts
- src/app/savings/savings-account-stepper/savings-account-details-step/savings-account-details-step.component.ts
- src/app/savings/savings-account-view/charges-tab/charges-tab.component.ts
- src/app/savings/savings-account-view/savings-account-view.component.html
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings-account-view/transactions-tab/transactions-tab.component.html
- src/app/savings/savings-account-view/transactions-tab/transactions-tab.component.ts
- src/app/savings/savings-account-view/view-charge/view-charge.component.ts
- src/app/savings/savings-routing.module.ts
- src/app/savings/savings.service.ts
- src/app/search/search-page/search-page.component.ts
- src/app/shared/notifications-tray/notifications-tray.component.ts
Refactored savings module and connected it to groups and centers modules
#1196 
> refactor: savings module

- src/app/loans/common-resolvers/loans-transaction-reciept.resolver.ts
- src/app/loans/loans-view/transactions/export-transactions/export-transactions.component.ts
- src/app/organization/sms-campaigns/sms-campaign-stepper/edit-sms-campaign-step/edit-business-rule-parameters/edit-business-rule-parameters.component.ts
- src/app/organization/sms-campaigns/sms-campaign-stepper/sms-campaign-step/business-rule-parameters/business-rule-parameters.component.ts
- src/app/pipes/url-to-string.pipe.ts
- src/app/reports/common-models/report-parameter.model.ts
- src/app/reports/common-resolvers/run-report.resolver.ts
- src/app/reports/reports-routing.module.ts
- src/app/reports/reports.component.html
- src/app/reports/reports.service.ts
- src/app/reports/run-report/chart/chart.component.ts
- src/app/reports/run-report/pentaho/pentaho.component.ts
- src/app/reports/run-report/run-report.component.html
- src/app/reports/run-report/run-report.component.ts
- src/app/reports/run-report/table-and-sms/table-and-sms.component.html
- src/app/reports/run-report/table-and-sms/table-and-sms.component.ts
- src/app/reports/xbrl/xbrl.component.ts
- src/app/savings/common-resolvers/savings-transaction-reciept.resolver.ts
- src/app/savings/savings-account-view/transactions-tab/export-transactions/export-transactions.component.ts
Refactored reports functionality
#1196 
> refactor: reports module

- src/app/core/shell/sidenav/sidenav.component.scss
Change cursor type to pointer on hovering over app logo on sidenavbar.
#746 
> fix(sidenav): pointer cursor upon hovering over app logo

- README.md
Fixes: #1254
@abhaychawla OK for you?
I missed noticing it at the very top in that GitHub banner! ;-) This makes it much more obvious IMHO.
> docs: add link to demo site at top of README

- src/app/users/view-user/view-user.component.html
>  Fixed view user page design

- src/app/reports/run-report/pentaho/pentaho.component.ts
- src/app/reports/run-report/run-report.component.ts
- src/app/reports/xbrl-report/xbrl-report.component.ts
Added centralized date formats and languages in reports module.
#1213
> refactor (df/locale): reports module

- src/app/clients/client-stepper/client-family-members-step/client-family-member-dialog/client-family-member-dialog.component.ts
- src/app/clients/client-stepper/client-general-step/client-general-step.component.ts
- src/app/clients/clients-view/charges/client-pay-charges/client-pay-charges.component.ts
- src/app/clients/clients-view/client-actions/activate-client/activate-client.component.ts
- src/app/clients/clients-view/client-actions/add-client-charge/add-client-charge.component.ts
- src/app/clients/clients-view/client-actions/close-client/close-client.component.ts
- src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.ts
- src/app/clients/clients-view/client-actions/reject-client/reject-client.component.ts
- src/app/clients/clients-view/client-actions/transfer-client/transfer-client.component.ts
- src/app/clients/clients-view/client-actions/undo-client-rejection/undo-client-rejection.component.ts
- src/app/clients/clients-view/client-actions/withdraw-client/withdraw-client.component.ts
- src/app/clients/clients-view/datatable-tab/multi-row/multi-row.component.ts
- src/app/clients/clients-view/datatable-tab/single-row/single-row.component.ts
- src/app/clients/clients-view/family-members-tab/add-family-member/add-family-member.component.ts
- src/app/clients/clients-view/family-members-tab/edit-family-member/edit-family-member.component.ts
- src/app/clients/create-client/create-client.component.ts
- src/app/clients/edit-client/edit-client.component.ts
> refactor(df/locale): clients module

- src/app/savings/create-savings-account/create-savings-account.component.ts
- src/app/savings/edit-savings-account/edit-savings-account.component.ts
- src/app/savings/saving-account-actions/activate-savings-account/activate-savings-account.component.ts
- src/app/savings/saving-account-actions/apply-annual-fees-savings-account/apply-annual-fees-savings-account.component.ts
- src/app/savings/saving-account-actions/approve-savings-account/approve-savings-account.component.ts
- src/app/savings/saving-account-actions/close-savings-account/close-savings-account.component.ts
- src/app/savings/saving-account-actions/post-interest-as-on-savings-account/post-interest-as-on-savings-account.component.ts
- src/app/savings/saving-account-actions/reject-savings-account/reject-savings-account.component.ts
- src/app/savings/saving-account-actions/savings-account-assign-staff/savings-account-assign-staff.component.ts
- src/app/savings/saving-account-actions/savings-account-unassign-staff/savings-account-unassign-staff.component.ts
- src/app/savings/saving-account-actions/withdraw-by-client-savings-account/withdraw-by-client-savings-account.component.ts
- src/app/savings/savings-account-view/charges-tab/charges-tab.component.ts
- src/app/savings/savings-account-view/datatable-tabs/multi-row/multi-row.component.ts
- src/app/savings/savings-account-view/datatable-tabs/single-row/single-row.component.ts
- src/app/savings/savings-account-view/standing-instructions-tab/standing-instructions-tab.component.ts
- src/app/savings/savings-account-view/transactions/edit-transaction/edit-transaction.component.ts
- src/app/savings/savings-account-view/transactions/view-transaction/view-transaction.component.ts
- src/app/savings/savings-account-view/view-charge/view-charge.component.ts
Fixes: #1213 
Added centralized date formats and languages in savings module
#1213 
> refactor (df/locale): savings module

- src/app/deposits/recurring-deposits/create-recurring-deposits-account/create-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/edit-recurring-deposit-account/edit-recurring-deposit-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/activate-recurring-deposits-account/activate-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/add-charge-recurring-deposits-account/add-charge-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/approve-recurring-deposits-account/approve-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/close-recurring-deposits-account/close-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/deposit-recurring-deposits-account/deposit-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/premature-close-recurring-deposit-account/premature-close-recurring-deposit-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/reject-recurring-deposits-account/reject-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/withdraw-by-client-recurring-deposits-account/withdraw-by-client-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-charges-step/recurring-deposits-account-charges-step.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/charges-tab/charges-tab.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/datatable-tabs/single-row/single-row.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/standing-instructions-tab/standing-instructions-tab.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/edit-transaction/edit-transaction.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/view-transaction/view-transaction.component.ts
Added centralized date formats and language in recurring deposits module
#1213 
> refactor (df/locale): recurring deposit

- src/app/groups/create-group/create-group.component.ts
- src/app/groups/edit-group/edit-group.component.ts
- src/app/groups/groups-view/datatable-tabs/multi-row/multi-row.component.ts
- src/app/groups/groups-view/datatable-tabs/single-row/single-row.component.ts
- src/app/groups/groups-view/group-actions/activate-group/activate-group.component.ts
- src/app/groups/groups-view/group-actions/attach-group-meeting/attach-group-meeting.component.ts
- src/app/groups/groups-view/group-actions/close-group/close-group.component.ts
- src/app/groups/groups-view/group-actions/edit-group-meeting-schedule/edit-group-meeting-schedule.component.ts
- src/app/groups/groups-view/group-actions/edit-group-meeting/edit-group-meeting.component.ts
- src/app/groups/groups-view/group-actions/group-attendance/group-attendance.component.ts
- src/app/groups/groups-view/group-actions/group-transfer-clients/group-transfer-clients.component.ts
Added centralized date formats and language in groups module
#1213 
> refactor (df/locale): groups module

- src/app/clients/clients-view/client-actions/client-actions.component.html
- src/app/clients/clients-view/client-actions/client-actions.component.ts
- src/app/clients/clients-view/client-actions/create-self-service-user/create-self-service-user.component.html
- src/app/clients/clients-view/client-actions/create-self-service-user/create-self-service-user.component.scss
- src/app/clients/clients-view/client-actions/create-self-service-user/create-self-service-user.component.spec.ts
- src/app/clients/clients-view/client-actions/create-self-service-user/create-self-service-user.component.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.ts
- src/app/clients/clients.module.ts
- src/app/clients/clients.service.ts
- src/app/clients/common-resolvers/client-actions.resolver.ts
Add create self service user component.
#1234 
> feat: add create self service user

- src/app/loans/create-loans-account/create-loans-account.component.ts
- src/app/loans/edit-loans-account/edit-loans-account.component.ts
- src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.ts
- src/app/loans/loans-view/charges-tab/charges-tab.component.ts
- src/app/loans/loans-view/datatable-tab/multi-row/multi-row.component.ts
- src/app/loans/loans-view/datatable-tab/single-row/single-row.component.ts
- src/app/loans/loans-view/loan-account-actions/add-loan-charge/add-loan-charge.component.ts
- src/app/loans/loans-view/loan-account-actions/approve-loan/approve-loan.component.ts
- src/app/loans/loans-view/loan-account-actions/assign-loan-officer/assign-loan-officer.component.ts
- src/app/loans/loans-view/loan-account-actions/close-as-rescheduled/close-as-rescheduled.component.ts
- src/app/loans/loans-view/loan-account-actions/create-guarantor/create-guarantor.component.ts
- src/app/loans/loans-view/loan-account-actions/disburse-loan-account/disburse-loan-account.component.ts
- src/app/loans/loans-view/loan-account-actions/disburse/disburse.component.ts
- src/app/loans/loans-view/loan-account-actions/foreclosure/foreclosure.component.ts
- src/app/loans/loans-view/loan-account-actions/loan-reschedule/loan-reschedule.component.ts
- src/app/loans/loans-view/loan-account-actions/loans-account-close/loans-account-close.component.ts
- src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.ts
- src/app/loans/loans-view/loan-account-actions/prepay-loan/prepay-loan.component.ts
- src/app/loans/loans-view/loan-account-actions/recovery-repayment/recovery-repayment.component.ts
- src/app/loans/loans-view/loan-account-actions/reject-loan/reject-loan.component.ts
- src/app/loans/loans-view/loan-account-actions/withdrawn-by-client/withdrawn-by-client.component.ts
- src/app/loans/loans-view/loan-account-actions/write-off-page/write-off-page.component.ts
- src/app/loans/loans-view/standing-instructions-tab/standing-instructions-tab.component.ts
- src/app/loans/loans-view/transactions/edit-transaction/edit-transaction.component.ts
- src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.ts
- src/app/loans/loans-view/view-charge/view-charge.component.ts
Added centralized dates format and languages in loans module
#1213
> refactor (df/locale): loans module

- src/app/centers/centers-view/center-actions/activate-center/activate-center.component.ts
- src/app/centers/centers-view/center-actions/attach-center-meeting/attach-center-meeting.component.ts
- src/app/centers/centers-view/center-actions/center-attendance/center-attendance.component.ts
- src/app/centers/centers-view/center-actions/close-center/close-center.component.ts
- src/app/centers/centers-view/center-actions/edit-center-meeting-schedule/edit-center-meeting-schedule.component.ts
- src/app/centers/centers-view/center-actions/edit-center-meeting/edit-center-meeting.component.ts
- src/app/centers/centers-view/datatable-tab/multi-row/multi-row.component.ts
- src/app/centers/centers-view/datatable-tab/single-row/single-row.component.ts
- src/app/centers/create-center/create-center.component.ts
refactor (df/locale): centers module
Added centralized date formats and languages in centers module
#1213
> refactor (df/locale): centers module

- src/app/organization/bulk-loan-reassignmnet/bulk-loan-reassignmnet.component.ts
- src/app/organization/employees/create-employee/create-employee.component.ts
- src/app/organization/employees/edit-employee/edit-employee.component.ts
- src/app/organization/fund-mapping/fund-mapping.component.ts
- src/app/organization/holidays/create-holiday/create-holiday.component.ts
- src/app/organization/holidays/edit-holiday/edit-holiday.component.ts
- src/app/organization/loan-provisioning-criteria/create-loan-provisioning-criteria/create-loan-provisioning-criteria.component.ts
- src/app/organization/loan-provisioning-criteria/edit-loan-provisioning-criteria/edit-loan-provisioning-criteria.component.ts
- src/app/organization/offices/create-office/create-office.component.ts
- src/app/organization/offices/edit-office/edit-office.component.ts
- src/app/organization/offices/view-office/datatable-tabs/multi-row/multi-row.component.ts
- src/app/organization/offices/view-office/datatable-tabs/single-row/single-row.component.ts
- src/app/organization/organization.service.ts
- src/app/organization/sms-campaigns/create-campaign/create-campaign.component.ts
- src/app/organization/sms-campaigns/edit-campaign/edit-campaign.component.ts
- src/app/organization/sms-campaigns/sms-campaign-stepper/edit-sms-campaign-step/edit-business-rule-parameters/edit-business-rule-parameters.component.ts
- src/app/organization/sms-campaigns/sms-campaign-stepper/sms-campaign-step/business-rule-parameters/business-rule-parameters.component.ts
- src/app/organization/sms-campaigns/view-campaign/view-campaign.component.ts
- src/app/organization/standing-instructions-history/standing-instructions-history.component.ts
- src/app/organization/tellers/cashiers/allocate-cash/allocate-cash.component.ts
- src/app/organization/tellers/cashiers/create-cashier/create-cashier.component.ts
- src/app/organization/tellers/cashiers/edit-cashier/edit-cashier.component.ts
- src/app/organization/tellers/cashiers/settle-cash/settle-cash.component.ts
- src/app/organization/tellers/create-teller/create-teller.component.ts
- src/app/organization/tellers/edit-teller/edit-teller.component.ts
- src/app/organization/working-days/working-days.component.ts
Added centralized date formats and languages in organization module
#1213 
> refactor (df/locale): organization module

- src/app/clients/client-stepper/client-address-step/client-address-step.component.ts
- src/app/clients/client-stepper/client-preview-step/client-preview-step.component.ts
- src/app/clients/clients-view/address-tab/address-tab.component.ts
rename params for fineract.dev
#1274 
> fix: address config params for fineract.dev

- src/app/organization/organization.service.ts
This simple change was made to fix the bulk import errors that users are receiving.
1318
> Fixing mispelled parameter name "dateFormat"

- Dockerfile
- src/environments/environment.prod.ts
- src/environments/environment.ts
> shreyank: Dockerize mifos web-app

- src/app/collections/individual-collection-sheet/individual-collection-sheet.component.ts
Update dateformats and language with centralized data in collections
module
#1213 
> refractor(df/locale):collections module

- src/app/system/audit-trails/audit-trails.component.ts
- src/app/system/entity-to-entity-mapping/entity-to-entity-mapping.component.ts
Update dateformats and language with centralized data in system
module
> refactor (df/locale): system module

- src/app/deposits/fixed-deposits/create-fixed-deposit-account/create-fixed-deposit-account.component.ts
- src/app/deposits/fixed-deposits/edit-fixed-deposit-account/edit-fixed-deposit-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-stepper/fixed-deposit-account-charges-step/fixed-deposit-account-charges-step.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/charges-tab/charges-tab.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/datatable-tabs/multi-row/multi-row.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/datatable-tabs/single-row/single-row.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/standing-instructions-tab/standing-instructions-tab.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/activate-fixed-deposits-account/activate-fixed-deposits-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/add-charge-fixed-deposits-account/add-charge-fixed-deposits-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/approve-fixed-deposits-account/approve-fixed-deposits-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/close-fixed-deposits-account/close-fixed-deposits-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/premature-close-fixed-deposits-account/premature-close-fixed-deposits-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/reject-fixed-deposits-account/reject-fixed-deposits-account.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/withdraw-by-client-fixed-deposits-account/withdraw-by-client-fixed-deposits-account.component.ts
Centralized the date formats and language code in fixed-deposits module using SettingsService
#1213 
> refactor(df/locale): fixed-deposits module

- src/app/savings/common-resolvers/savings-transaction-reciept.resolver.ts
- src/app/savings/saving-account-actions/add-charge-savings-account/add-charge-savings-account.component.ts
- src/app/savings/saving-account-actions/savings-account-transactions/savings-account-transactions.component.ts
- src/app/savings/savings-account-view/transactions-tab/export-transactions/export-transactions.component.ts
The savings module code has already been refractored but some files weren't edited, refractoring the remaining files.
#1259 
#1213 
> refractor(df/locale):savings module

- src/app/shares/create-shares-account/create-shares-account.component.ts
- src/app/shares/edit-shares-account/edit-shares-account.component.ts
- src/app/shares/shares-account-actions/activate-shares-account/activate-shares-account.component.ts
- src/app/shares/shares-account-actions/apply-shares/apply-shares.component.ts
- src/app/shares/shares-account-actions/approve-shares-account/approve-shares-account.component.ts
- src/app/shares/shares-account-actions/approve-shares/approve-shares.component.ts
- src/app/shares/shares-account-actions/close-shares-account/close-shares-account.component.ts
- src/app/shares/shares-account-actions/redeem-shares/redeem-shares.component.ts
- src/app/shares/shares-account-actions/reject-shares-account/reject-shares-account.component.ts
- src/app/shares/shares-account-actions/reject-shares/reject-shares.component.ts
Update dateformats and language with centralized data in shares
module
#1213 
> refractor(df/locale):shares module

- src/app/accounting/closing-entries/create-closure/create-closure.component.ts
- src/app/accounting/create-journal-entry/create-journal-entry.component.ts
- src/app/accounting/frequent-postings/frequent-postings.component.ts
- src/app/accounting/migrate-opening-balances/migrate-opening-balances.component.ts
- src/app/accounting/periodic-accruals/periodic-accruals.component.ts
- src/app/accounting/provisioning-entries/create-provisioning-entry/create-provisioning-entry.component.ts
- src/app/accounting/search-journal-entry/search-journal-entry.component.ts
Refactored the accounting module to fetch the date and locale from service.
#{Issue Number} #1213 
> refactor (df/locale): accounting module

- src/app/products/charges/create-charge/create-charge.component.ts
- src/app/products/charges/edit-charge/edit-charge.component.ts
- src/app/products/fixed-deposit-products/create-fixed-deposit-product/create-fixed-deposit-product.component.ts
- src/app/products/fixed-deposit-products/edit-fixed-deposit-product/edit-fixed-deposit-product.component.ts
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-interest-rate-chart-step/fixed-deposit-product-interest-rate-chart-step.component.ts
- src/app/products/floating-rates/create-floating-rate/create-floating-rate.component.ts
- src/app/products/floating-rates/edit-floating-rate/edit-floating-rate.component.ts
- src/app/products/loan-products/create-loan-product/create-loan-product.component.ts
- src/app/products/loan-products/edit-loan-product/edit-loan-product.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-details-step/loan-product-details-step.component.ts
- src/app/products/manage-tax-components/create-tax-component/create-tax-component.component.ts
- src/app/products/manage-tax-components/edit-tax-component/edit-tax-component.component.ts
- src/app/products/manage-tax-groups/create-tax-group/create-tax-group.component.ts
- src/app/products/manage-tax-groups/edit-tax-group/edit-tax-group.component.ts
- src/app/products/products.service.ts
- src/app/products/recurring-deposit-products/create-recurring-deposit-product/create-recurring-deposit-product.component.ts
- src/app/products/recurring-deposit-products/edit-recurring-deposit-product/edit-recurring-deposit-product.component.ts
- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-interest-rate-chart-step/recurring-deposit-product-interest-rate-chart-step.component.ts
- src/app/products/saving-products/create-saving-product/create-saving-product.component.ts
- src/app/products/saving-products/edit-saving-product/edit-saving-product.component.ts
- src/app/products/share-products/create-dividend/create-dividend.component.ts
- src/app/products/share-products/create-share-product/create-share-product.component.ts
- src/app/products/share-products/edit-share-product/edit-share-product.component.ts
- src/app/products/share-products/share-product-stepper/share-product-market-price-step/share-product-market-price-step.component.ts
Update dateformats and language with centralized data in products
module
#1213 
> refractor(df/locale):products module

- src/app/web-app.component.ts
Adds `https://qa.mifos.io` in the server selection drop-down list.
> adds qa instance url in web-app.component.ts

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/core/core.module.ts
- src/app/core/http/api-prefix.interceptor.ts
- src/app/core/i18n/i18n.service.ts
- src/app/core/shell/toolbar/toolbar.component.html
- src/app/shared/language-selector/language-selector.component.ts
- src/assets/translations/en-US.json
- src/assets/translations/fr-FR.json
Fixed implementation of translated because it is not working correctly
#1304
> Solution for TranslateModule not exported from SharedModule #1304

- src/theme/pink-bluegrey.scss
- src/theme/purple-green.scss
Solution for Text not visible in dark mode #1307 to correctly display text in tables and alerts
#1307
> Solution for Text not visible in dark mode #1307

- .dockerignore
- Dockerfile
Fix docker build failure
#1379
> fix: docker build failure

- .github/workflows/create-docker-hub-image.yml
Adding GitHub Action for publishing image on Docker Hub
> Adding GitHub Action for publishing image on Docker Hub

- src/app/clients/client-stepper/client-general-step/client-general-step.component.html
- src/app/clients/client-stepper/client-general-step/client-general-step.component.ts
- src/app/clients/client-stepper/client-preview-step/client-preview-step.component.html
- src/app/clients/clients-routing.module.ts
- src/app/clients/clients-view/general-tab/general-tab.component.ts
- src/app/clients/edit-client/edit-client.component.html
- src/app/clients/edit-client/edit-client.component.ts
- src/app/settings/settings.service.ts
- src/app/shared/language-selector/language-selector.component.html
- src/app/shared/language-selector/language-selector.component.scss
- src/app/shared/language-selector/language-selector.component.ts
- src/app/web-app.component.ts
Allow add contact details to Client entity
[Apache Fineract JIRA ticket FINERACT-1587](https://issues.apache.org/jira/browse/FINERACT-1587)
> FINERACT-1587: Add email field to Client

- src/app/centers/centers-view/datatable-tab/multi-row/multi-row.component.ts
- src/app/centers/centers-view/datatable-tab/single-row/single-row.component.ts
- src/app/clients/clients-view/datatable-tab/multi-row/multi-row.component.ts
- src/app/clients/clients-view/datatable-tab/single-row/single-row.component.ts
- src/app/loans/loans-view/datatable-tab/multi-row/multi-row.component.ts
- src/app/loans/loans-view/datatable-tab/single-row/single-row.component.ts
- src/app/system/manage-data-tables/app-table-data.ts
- src/app/system/manage-data-tables/create-data-table/create-data-table.component.html
- src/app/system/manage-data-tables/create-data-table/create-data-table.component.ts
Process automatic fields (created_at and updated_at) for Datatables 
https://mifosforge.jira.com/browse/PERF-228
Before
After
View Datatable data
> New Data Tables Creation not working : 1402

- src/app/core/utils/dates.spec.ts
- src/app/core/utils/dates.ts
- src/app/loans/common-resolvers/loan-action-button.resolver.ts
- src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.html
- src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.ts
A couple of issues related to Loan Repayment, due for commented code
- https://github.com/openMF/web-app/issues/1401
- https://github.com/openMF/web-app/issues/1356 
> Fix for Loan repayment issues

- angular.json
> Disable serviceworker for production build

- src/app/app.module.ts
> Disable serviceworker prod

- src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.ts
Wrong initial transaction date;
Fix transaction date disappearance after submit;
Redirect to the "transactions" list
> Fix repayment date change issue

- src/app/products/share-products/share-product-stepper/share-product-details-step/share-product-details-step.component.html
- src/app/products/share-products/share-product-stepper/share-product-details-step/share-product-details-step.component.ts
> Unable to create new loan product or share product #1406

- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-details-step/fixed-deposit-product-details-step.component.html
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-interest-rate-chart-step/fixed-deposit-product-interest-rate-chart-step.component.ts
> Unable to create any product account(loans/FD and RD accounts)

- src/app/clients/clients-view/general-tab/general-tab.component.html
View loan screen at client screen is showing the summary properly now.
#1419
> fix: Client Loan Accounts Summary fix

- package-lock.json
- src/app/system/manage-scheduler-jobs/manage-scheduler-jobs.component.html
- src/app/system/manage-scheduler-jobs/manage-scheduler-jobs.component.scss
- src/app/system/manage-scheduler-jobs/manage-scheduler-jobs.component.ts
- src/app/system/system-routing.module.ts
- src/app/system/system.service.ts
The scheduler view with the Batch jobs the buttons: 
- Suspend/Active,  
- Run Selected Jobs and 
- Refresh 
They were without any function linked in the click event
https://github.com/openMF/web-app/issues/1321
https://github.com/openMF/web-app/issues/1322
> Fixes for missing button actions

- src/app/products/charges/create-charge/create-charge.component.html
- src/app/products/charges/create-charge/create-charge.component.ts
Added Fields to Add maximum charge limit and minimum charge limit
#1428 
> Added Charges cap

- src/app/loans/loans-view/loan-account-actions/loan-reschedule/loan-reschedule.component.html
Allowed future date selections for the fields "Reschedule from installments on" and "change repayment date" field.
#1432 
> Enabled future dates for rescheling loans

- src/app/core/route/route.service.ts
Fix for the issue After login the screen is not refreshed: stuck on login page.
[1452](https://github.com/openMF/web-app/issues/1452)
> Fix stuck on login page

- .github/workflows/build.yml
- package.json
Due Angular main dependencies upgrades, we need to upgrade the Angular CLI version and the node/npm versions in the Github actions
> Set a LTS node version to 16

- .github/workflows/build.yml
- Dockerfile
- package-lock.json
- package.json
- src/app/centers/centers-view/centers-view.component-theme.scss
- src/app/clients/clients-view/clients-view.component-theme.scss
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/fixed-deposit-account-view.component-theme.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component-theme.scss
- src/app/groups/groups-view/groups-view.component-theme.scss
- src/app/home/dashboard/dashboard.component-theme.scss
- src/app/loans/loans-view/loans-view.component-theme.scss
- src/app/savings/savings-account-view/savings-account-view.component-theme.scss
- src/app/shared/theme-picker/theme-picker.component.scss
- src/app/shares/shares-account-view/shares-account-view.component-theme.scss
- src/app/system/configure-maker-checker-tasks/configure-maker-checker-tasks.component.ts
- src/theme/custom/denim-yellowgreen.scss
- src/theme/custom/pictonblue-yellowgreen.scss
In order to apply a progressive upgrade for Angular, here is an upgrade from Angular 11 to 12
This upgrade involves more files, mainly `sccs` files that were updated in the way to use some Angular material functions
> Upgrade to Angular 12

- src/environments/environment.prod.ts
> Fixed backend configuration ability

- src/app/loans/loans.service.ts
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-interest-rate-chart-step/fixed-deposit-product-interest-rate-chart-step.component.ts
Couple of fixes for the Fixed Deposit Product
- Charts data to be required
The tab is marked with error
- Edition without Description
> Fix Fixed Deposit product edition

- src/app/organization/organization.service.ts
Passing the wrong parameter into API related to Home/Organization/Bulk Loan/Reassignment FIxed.
#1440 
> fix: wrong parameter passed in API

- .github/workflows/stale.yml
> Stale pull request workflow

- src/app/accounting/closing-entries/create-closure/create-closure.component.ts
- src/app/accounting/create-journal-entry/create-journal-entry.component.ts
- src/app/accounting/frequent-postings/frequent-postings.component.ts
- src/app/accounting/migrate-opening-balances/migrate-opening-balances.component.ts
- src/app/accounting/periodic-accruals/periodic-accruals.component.ts
- src/app/accounting/provisioning-entries/create-provisioning-entry/create-provisioning-entry.component.ts
- src/app/accounting/search-journal-entry/search-journal-entry.component.html
- src/app/accounting/search-journal-entry/search-journal-entry.component.ts
- src/app/accounting/view-journal-entry/view-journal-entry.component.html
- src/app/accounting/view-transaction/view-transaction.component.html
In the Auditing module, some of the date formatting was broken. 
The sent date was not formatted as per the provided date formatter.
> Search and Create Journal entry page is broken + Add filter by submitted on date

- src/app/loans/create-loans-account/create-loans-account.component.ts
- src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.html
- src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.ts
Marking the collaterals as optional for now.
> Fix Collaterals on Loan: It is optional

- src/app/loans/edit-loans-account/edit-loans-account.component.ts
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html
- src/app/loans/loans-view/transactions-tab/transactions-tab.component.ts
The new loan transactions were not able to be undone
> Allow undo for new loan transactions

- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html
> Add missing maxOutstandingLoanBalance-field

- src/app/loans/create-loans-account/create-loans-account.component.html
- src/app/loans/create-loans-account/create-loans-account.component.ts
- src/app/loans/edit-loans-account/edit-loans-account.component.html
- src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.html
- src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.ts
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
Moved the collateral selection screen at the loan level a step above the charges section
Removed the mandatory validations
#1334 
> fix: collateral fixes

- src/app/loans/loans-view/loans-view.component.html
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.html
- src/app/loans/loans-view/transactions-tab/transactions-tab.component.ts
- src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.html
- src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.ts
Fix Undo Credit loan transaction
> Fix for Credit loan transaction

- Dockerfile
- docker-compose.yml
> Ability to parameterize build

- src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.html
- src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.ts
> Already reverted transaction cannot be edited / undo

- src/app/core/shell/breadcrumb/breadcrumb.component.ts
- src/app/loans/common-resolvers/loan-delinquency-tags.resolver.ts
- src/app/loans/create-loans-account/create-loans-account.component.html
- src/app/loans/create-loans-account/create-loans-account.component.ts
- src/app/loans/edit-loans-account/edit-loans-account.component.ts
- src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.html
- src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.ts
- src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.html
- src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.ts
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/loan-delinquency-tags-tab/loan-delinquency-tags-tab.component.html
- src/app/loans/loans-view/loan-delinquency-tags-tab/loan-delinquency-tags-tab.component.scss
- src/app/loans/loans-view/loan-delinquency-tags-tab/loan-delinquency-tags-tab.component.spec.ts
- src/app/loans/loans-view/loan-delinquency-tags-tab/loan-delinquency-tags-tab.component.ts
- src/app/loans/loans-view/loans-view.component.html
- src/app/loans/loans.module.ts
- src/app/loans/loans.service.ts
When a loan account receives credits on the overdue outstanding payments, his/her Delinquency Classification may change with that. Delinquency classification of the loan should be checked and correct in Real-time when new transactions are made on the loan account
- Loan Account Classification below of Client Name
- Delinquency Tag (history) tab on the right of Transactions tab
> Real time Loan Delinquency Classification

- src/app/system/configurations/global-configurations-tab/edit-configuration/edit-configuration.component.html
- src/app/system/system-routing.module.ts
When hitting the edit button in the System Configurations, the user was navigated to a 404 page
> Fix for editing values system configurations

- docker-compose.yml
> Docker compose fix

- src/app/products/saving-products/saving-product-stepper/saving-product-accounting-step/saving-product-accounting-step.component.ts
Updated the escheatLiabilityId part.
#1475 
Fixed the bug, now the form is pre populated with the values as inputted by user.
- [ -] If you have multiple commits please combine them into one commit by squashing them.
- [ -] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.
> Fix - #1475

- src/app/system/audit-trails/audit-trails.component.html
Sorting is working now on certain columns in audit trails
#483 
> fix: sorting added for checker, status, madeby in audit trails

- src/app/loans/loans-view/loan-tranche-details/loan-tranche-details.component.html
- src/app/loans/loans-view/loan-tranche-details/loan-tranche-details.component.ts
- src/app/loans/loans.service.ts
The Loan Tranches management were not implemented in web-app Now we can add, edit or delete the Loan account disbursement data 
- Original view to add, edit or delete a disbursement detail
- After any change we can to apply the changes using the proper edit disbursement Fineract endpoint
> Loan tranches Management

- src/app/clients/clients-view/identities-tab/identities-tab.component.html
- src/app/clients/clients-view/identities-tab/identities-tab.component.ts
- src/app/core/shell/breadcrumb/breadcrumb.component.html
- src/app/core/shell/sidenav/sidenav.component.html
- src/app/core/shell/toolbar/toolbar.component.html
- src/app/home/home.component.html
- src/app/home/home.module.ts
- src/app/loans/loans-view/loans-view.component.html
- src/app/loans/loans-view/loans-view.component.scss
- src/app/login/login-form/login-form.component.html
- src/app/login/login.component.html
- src/app/login/login.module.ts
- src/app/shared/footer/footer.component.html
- src/app/shared/language-selector/language-selector.component.html
- src/app/shared/server-selector/server-selector.component.html
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/environments/environment.prod.ts
- src/environments/environment.ts
Translate for Login and Home views
> Translate Login and Home

- src/app/system/manage-jobs/scheduler-jobs/manage-scheduler-jobs.component.ts
- src/app/system/manage-jobs/workflow-jobs/workflow-jobs.component.html
- src/app/system/manage-jobs/workflow-jobs/workflow-jobs.component.ts
- src/app/system/system.service.ts
In the Workflow Jobs management is possible to add, remove Job steps even change the execution order
> Allow add new Job step to Workflow Jobs

- src/assets/translations/es-MX.json
Spanish words have been fixed.
> Spanish translation fix

- src/app/clients/clients-view/clients-view.component.html
Fix for showing activation Date in the General View
> Fix for Showing Client Activation Date in the General View

- src/app/clients/clients-view/client-actions/take-survey/take-survey.component.html
- src/app/clients/clients-view/custom-dialogs/upload-image-dialog/upload-image-dialog.component.html
- src/app/clients/clients-view/custom-dialogs/upload-signature-dialog/upload-signature-dialog.component.html
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html
- src/app/organization/bulk-import/view-bulk-import/view-bulk-import.component.html
- src/app/self-service/users/view-user/view-user.component.html
- src/app/shared/file-upload/file-upload.component.html
- src/app/shared/file-upload/file-upload.component.ts
- src/app/system/configurations/business-date-tab/business-date-tab.component.html
Set in some views that upload file(s) the filter according to the file that can be uploaded, like image or just spreadsheet file
> Apply filter in the file uploads

- README.md
- env.sample
- src/app/clients/create-client/create-client.component.ts
- src/app/core/authentication/authentication.interceptor.ts
- src/app/core/shell/sidenav/sidenav.component.html
- src/app/core/shell/sidenav/sidenav.component.ts
- src/app/login/login-form/login-form.component.html
- src/app/login/login.component.html
- src/app/organization/tellers/cashiers/allocate-cash/allocate-cash.component.ts
- src/app/organization/tellers/cashiers/transactions/transactions.component.html
- src/app/profile/profile.component.html
- src/app/profile/profile.component.ts
- src/app/settings/settings.service.ts
- src/app/shared/shared.module.ts
- src/app/shared/tenant-selector/tenant-selector.component.html
- src/app/shared/tenant-selector/tenant-selector.component.scss
- src/app/shared/tenant-selector/tenant-selector.component.spec.ts
- src/app/shared/tenant-selector/tenant-selector.component.ts
- src/app/web-app.component.ts
- src/assets/env.template.js
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/environments/environment.prod.ts
- src/environments/environment.ts
In the case when we have more than one Tenant, we'll be able to set an environment variable to define a `Tenant Identifier` list that will be displayed in the Login form as dropdown menu to choose on which of these Tenants we want to logon. By default  will be the `default` Tenant Identifier as current
If the list has only one option or the environment variable is not defined the dropdown input will be disabled
```
FINERACT_PLATFORM_TENANT_IDENTIFIER
```
Fineract Tenant identifier to be used by default, It must be aligned with the Fineract `tenants` table. Default value:
```
default
```
```
FINERACT_PLATFORM_TENANTS_IDENTIFIER
```
Fineract Tenant identifier list to be used, Those must be aligned with the Fineract `tenants` table. 
For these environment variables or others available please …
> Login form with Tenant dropdown menu

- .github/workflows/publish-docker-image.yml
Publish Docker Image to JFrog Artifactory
> Publish Docker Image to JFrog Artifactory

- src/app/loans/loans-view/loans-view.component.html
- src/app/loans/loans-view/loans-view.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-currency-step/loan-product-currency-step.component.ts
When the loan account is multi tranche and It has been disbursed for the first time, there was not an option to disburse one time more.
- Loan account view with multiple disbursements with the button to apply additional disbursement If It is needed
> Add the disburse button when the loan is multi tranche

- src/app/centers/centers-view/datatable-tab/multi-row/multi-row.component.html
- src/app/centers/centers-view/datatable-tab/multi-row/multi-row.component.ts
- src/app/centers/centers-view/datatable-tab/single-row/single-row.component.html
- src/app/clients/clients-view/datatable-tab/multi-row/multi-row.component.html
- src/app/clients/clients-view/datatable-tab/multi-row/multi-row.component.ts
- src/app/clients/clients-view/datatable-tab/single-row/single-row.component.html
- src/app/groups/groups-view/datatable-tabs/multi-row/multi-row.component.html
- src/app/groups/groups-view/datatable-tabs/multi-row/multi-row.component.ts
- src/app/groups/groups-view/datatable-tabs/single-row/single-row.component.html
- src/app/loans/loans-view/datatable-tab/multi-row/multi-row.component.html
- src/app/loans/loans-view/datatable-tab/multi-row/multi-row.component.ts
- src/app/loans/loans-view/datatable-tab/single-row/single-row.component.html
- src/app/loans/loans-view/datatable-tab/single-row/single-row.component.scss
- src/app/loans/loans-view/view-charge/view-charge.component.html
- src/app/loans/loans-view/view-charge/view-charge.component.ts
- src/app/organization/offices/view-office/datatable-tabs/multi-row/multi-row.component.html
- src/app/organization/offices/view-office/datatable-tabs/multi-row/multi-row.component.ts
- src/app/organization/offices/view-office/datatable-tabs/single-row/single-row.component.html
- src/app/pipes/date-format.pipe.ts
- src/app/pipes/datetime-format.pipe.ts
- src/app/savings/savings-account-view/datatable-tabs/multi-row/multi-row.component.html
- src/app/savings/savings-account-view/datatable-tabs/multi-row/multi-row.component.ts
- src/app/savings/savings-account-view/datatable-tabs/single-row/single-row.component.html
Datatable views updates for display values with format
> Datatable views updates for display values with format

- angular.json
- src/app/account-transfers/make-account-transfers/make-account-transfers.component.html
- src/app/account-transfers/make-account-transfers/make-account-transfers.component.ts
- src/app/account-transfers/view-account-transfer/view-account-transfer.component.html
- src/app/account-transfers/view-account-transfer/view-account-transfer.component.ts
- src/app/accounting/accounting.module.ts
- src/app/accounting/search-journal-entry/search-journal-entry.component.html
- src/app/accounting/view-journal-entry/view-journal-entry.component.html
- src/app/accounting/view-transaction/view-transaction.component.html
- src/app/accounting/view-transaction/view-transaction.component.scss
- src/app/accounting/view-transaction/view-transaction.component.ts
- src/app/clients/clients-view/charges/view-charge/view-charge.component.html
- src/app/loans/loans-view/transactions/view-reciept/view-reciept.component.html
- src/app/pipes/status-lookup.pipe.ts
- src/app/savings/saving-account-actions/manage-savings-account/manage-savings-account.component.html
- src/app/savings/saving-account-actions/manage-savings-account/manage-savings-account.component.ts
- src/app/savings/saving-account-actions/saving-account-actions.component.html
- src/app/savings/savings-account-view/savings-account-view.component.html
- src/app/savings/savings-account-view/savings-account-view.component.ts
- src/app/savings/savings-account-view/savings-buttons.config.ts
- src/app/savings/savings-account-view/transactions/view-transaction/view-transaction.component.html
- src/app/savings/savings-routing.module.ts
- src/assets/styles/_status.scss
Allow the Block and Unblock actions in the Savings Accounts
- Savings account Active (default), with the normal menu and the Block option
- Input the reason for Blocking the Savings account
- Savings account Blocked, only with the option to Unblock It
> Savings account status and substatus management

- angular.json
Fix in Angular build process in the file angular.json for budgets
> Fix Angular build process

- src/app/core/http/api-prefix.interceptor.ts
- src/app/loans/loans-view/loan-account-actions/edit-repayment-schedule/edit-repayment-schedule.component.html
- src/app/loans/loans-view/loan-account-actions/edit-repayment-schedule/edit-repayment-schedule.component.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans-view/loan-account-actions/undo-disbursal/undo-disbursal.component.html
- src/app/loans/loans-view/loan-account-actions/undo-disbursal/undo-disbursal.component.ts
- src/app/loans/loans-view/loans-view.component.ts
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.html
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.scss
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.ts
- src/app/loans/loans.service.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts
- src/app/savings/saving-account-actions/manage-savings-account/manage-savings-account.component.ts
- src/app/shared/footer/footer.component.html
- src/app/shared/footer/footer.component.ts
- src/app/system/manage-data-tables/edit-data-table/edit-data-table.component.html
- src/app/system/manage-data-tables/edit-data-table/edit-data-table.component.ts
- src/app/system/manage-data-tables/view-data-table/view-data-table.component.html
The Loan Account Repayment Schedule edition now It's available as It was in the previous application. It'll be available after the Loan Account request only. That means only available in the mean time the Loan Account is in Status Submitted and Pending Approval
- Edit Repayment Schedule initial view
- Apply pattern to set the installment(s) amount, From one period To other period
- Repayment Schedule with amount in blue to know which of them are being updated
- Repayment Schedule validated and ready to be Submitted
> Loan Repayment Schedule edition to have variations

- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html
There was an issue in the Loan account creation when the Loan product allows to define the installment amount
> Display the input for Installment amount when It can be defined

- src/app/loans/loans-view/view-charge/view-charge.component.ts
Fix the payload message in the Loan charge pay command
> fix the Loan charge pay command payload

- src/app/accounting/accounting-routing.module.ts
- src/app/accounting/accounting-rules/create-rule/create-rule.component.html
- src/app/accounting/accounting-rules/edit-rule/edit-rule.component.html
- src/app/accounting/create-journal-entry/create-journal-entry.component.html
- src/app/accounting/frequent-postings/frequent-postings.component.html
- src/app/accounting/search-journal-entry/search-journal-entry.component.html
- src/app/accounting/search-journal-entry/search-journal-entry.component.ts
- src/app/clients/clients.component.ts
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
Enhancement the accounting view to go back to the Accounting menu instead of Journal Entries search view 
> Enhancement for accounting view in back button

- src/app/loans/loans-view/loans-view.component.html
- src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.html
- src/app/loans/loans-view/view-charge/view-charge.component.html
- src/app/loans/loans-view/view-charge/view-charge.component.ts
- src/app/reports/reports.component.html
- src/app/system/manage-reports/create-report/create-report.component.html
- src/app/system/manage-reports/create-report/create-report.component.ts
- src/app/system/manage-reports/edit-report/edit-report.component.html
- src/app/system/manage-reports/edit-report/edit-report.component.ts
Manage report view updated to use dropdown menu in the Report Type
> Manage Report views updated

- src/app/clients/clients-routing.module.ts
- src/app/loans/common-resolvers/loan-reschedules.resolver.spec.ts
- src/app/loans/common-resolvers/loan-reschedules.resolver.ts
- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/loans-view.component.html
- src/app/loans/loans-view/reschedule-loan-tab/reschedule-loan-tab.component.html
- src/app/loans/loans-view/reschedule-loan-tab/reschedule-loan-tab.component.scss
- src/app/loans/loans-view/reschedule-loan-tab/reschedule-loan-tab.component.spec.ts
- src/app/loans/loans-view/reschedule-loan-tab/reschedule-loan-tab.component.ts
- src/app/loans/loans.module.ts
- src/app/loans/loans.service.ts
- src/app/tasks/checker-inbox-and-tasks-tabs/checker-inbox/checker-inbox.component.html
- src/app/tasks/checker-inbox-and-tasks-tabs/reschedule-loan/reschedule-loan.component.html
- src/app/tasks/checker-inbox-and-tasks-tabs/reschedule-loan/reschedule-loan.component.ts
- src/app/tasks/view-checker-inbox/view-checker-inbox.component.html
Loan Reschedule management in Loan Account in the `Loan Reschedule `tab to Add, Approve or Reject Loan Reschedule request
> Loan Reschedule management in Loan Account

- src/app/core/shell/breadcrumb/breadcrumb.component.scss
- src/app/loans/loans-view/loan-account-actions/add-loan-charge/add-loan-charge.component.ts
- src/app/shared/tabs/entity-datatable-tab/datatable-single-row/datatable-single-row.component.html
- src/app/shared/tabs/entity-datatable-tab/datatable-single-row/datatable-single-row.component.scss
- src/app/shared/tabs/entity-datatable-tab/datatable-single-row/datatable-single-row.component.ts
Allow add loan charge in future date including a head of the business or current date
> Allow add loan charge in future date

- src/app/accounting/view-transaction/view-transaction.component.html
- src/app/accounting/view-transaction/view-transaction.component.scss
- src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.ts
- src/app/products/manage-tax-components/create-tax-component/create-tax-component.component.ts
- src/app/products/manage-tax-components/edit-tax-component/edit-tax-component.component.html
- src/app/products/manage-tax-components/edit-tax-component/edit-tax-component.component.ts
- src/app/products/manage-tax-components/view-tax-component/view-tax-component.component.html
- src/app/settings/settings.service.ts
- src/app/system/manage-data-tables/app-table-data.ts
- src/assets/styles/_align.scss
- src/assets/styles/_helper.scss
> GL view transaction enhanced

- src/app/home/dashboard/amount-disbursed-pie/amount-disbursed-pie.component.html
- src/app/home/dashboard/amount-disbursed-pie/amount-disbursed-pie.component.ts
- src/app/home/home.service.ts
- src/app/loans/common-resolvers/loan-action-button.resolver.ts
- src/app/loans/glim-account/create-glim-account/create-glim-account.component.ts
- src/app/loans/loans-view/loan-account-actions/disburse-to-savings-account/disburse-to-savings-account.component.ts
- src/app/loans/loans-view/loan-account-actions/foreclosure/foreclosure.component.html
- src/app/loans/loans-view/loan-account-actions/foreclosure/foreclosure.component.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- src/app/loans/loans-view/loan-account-actions/withdrawn-by-client/withdrawn-by-client.component.ts
- src/app/loans/loans-view/loan-account-actions/write-off-page/write-off-page.component.ts
- src/app/loans/loans-view/loans-view.component.ts
- src/app/loans/loans-view/reschedule-loan-tab/reschedule-loan-tab.component.ts
- src/app/loans/loans.service.ts
- src/app/loans/models/loan-status.nodel.ts
- src/app/organization/bulk-import/view-bulk-import/view-bulk-import.component.html
- src/app/organization/bulk-loan-reassignmnet/bulk-loan-reassignmnet.component.ts
- src/app/savings/gsim-account/create-gsim-account/create-gsim-account.component.ts
- src/app/savings/gsim-account/gsim-account.component.ts
- src/app/savings/savings-account-view/transactions/view-transaction/view-transaction.component.ts
- src/app/system/manage-jobs/scheduler-jobs/view-history-scheduler-job/view-history-scheduler-job.component.ts
- src/app/system/manage-reports/edit-report/edit-report.component.ts
- src/app/system/manage-surveys/edit-survey/edit-survey.component.ts
- src/app/tasks/checker-inbox-and-tasks-tabs/loan-disbursal/loan-disbursal.component.ts
Update the `Dashboard` graphs 
> Update dashboard table reports

- src/app/system/manage-jobs/workflow-jobs/workflow-jobs.component.ts
> Fix GET workflow job names response handling

- src/app/clients/client-stepper/client-general-step/client-general-step.component.html
- src/app/loans/loans-view/general-tab/general-tab.component.html
- src/app/loans/loans-view/loan-account-actions/disburse/disburse.component.html
- src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.html
- src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.ts
- src/app/loans/loans-view/loan-account-actions/prepay-loan/prepay-loan.component.html
- src/app/loans/loans-view/loan-account-actions/recovery-repayment/recovery-repayment.component.html
- src/app/loans/loans-view/loan-account-actions/undo-approval/undo-approval.component.html
- src/app/loans/loans-view/loans-view.component.ts
- src/app/loans/loans-view/transactions-tab/transactions-tab.component.html
- src/app/loans/loans-view/transactions-tab/transactions-tab.component.scss
- src/app/loans/loans-view/transactions-tab/transactions-tab.component.ts
- src/app/loans/loans.service.ts
- src/app/savings/saving-account-actions/close-savings-account/close-savings-account.component.html
- src/app/savings/saving-account-actions/savings-account-transactions/savings-account-transactions.component.html
- src/app/savings/savings-account-view/transactions-tab/transactions-tab.component.html
- src/app/savings/savings-account-view/transactions-tab/transactions-tab.component.ts
Enhancement loan transactions tab for sort and pagination
> Enhancement loan transactions tab for sort and pagination

- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/general-tab/general-tab.component.html
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.html
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.scss
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.ts
- src/app/products/charges/charges.component.html
- src/app/products/charges/charges.component.ts
- src/app/products/charges/create-charge/create-charge.component.html
- src/app/products/charges/edit-charge/edit-charge.component.html
- src/app/products/charges/edit-charge/edit-charge.component.scss
- src/app/products/charges/edit-charge/edit-charge.component.ts
- src/app/products/charges/view-charge/view-charge.component.html
- src/app/products/products-routing.module.ts
- src/assets/styles/_align.scss
Enhancement for Charge management to:
- Get more details in the Charge list view,
- Reuse the Fee frequency set in the Loan Charge creation
> Enhancement for Charge management

- src/app/loans/common-resolvers/loan-action-button.resolver.ts
- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/charges-tab/charges-tab.component.html
- src/app/loans/loans-view/charges-tab/charges-tab.component.ts
- src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.html
- src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.scss
- src/app/loans/loans-view/loan-account-actions/prepay-loan/prepay-loan.component.html
- src/app/loans/loans-view/loan-account-actions/prepay-loan/prepay-loan.component.scss
- src/app/loans/loans-view/loan-account-actions/prepay-loan/prepay-loan.component.ts
- src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.html
- src/app/loans/loans.service.ts
- src/assets/styles/_form.scss
Use of currency in payment transaction amount for repayment and prepay loan
- Prepay Loan
> Enhancement in loan payment views

- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-interest-rate-chart-step/fixed-deposit-product-interest-rate-chart-step.component.html
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-interest-rate-chart-step/fixed-deposit-product-interest-rate-chart-step.component.ts
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-settings-step/fixed-deposit-product-settings-step.component.html
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-settings-step/fixed-deposit-product-settings-step.component.ts
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-terms-step/fixed-deposit-product-terms-step.component.html
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-terms-step/fixed-deposit-product-terms-step.component.ts
Added ToolTips in Fixed Deposit Products that provided a valuable aid to understanding functionality of the system .
#1654 
https://user-images.githubusercontent.com/76156941/216444727-a2f262f5-ea48-472f-a63b-d882357f1875.mov
> feat: add tooltips in fixed deposit products

- src/app/products/loan-products/loan-product-stepper/loan-product-charges-step/loan-product-charges-step.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-currency-step/loan-product-currency-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-currency-step/loan-product-currency-step.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-details-step/loan-product-details-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-details-step/loan-product-details-step.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-terms-step/loan-product-terms-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-terms-step/loan-product-terms-step.component.ts
added tooltips in creating loan product screen to provide valuable aid in understanding the functionality of the system.
#1668 
https://user-images.githubusercontent.com/76156941/217546841-9b2e95b9-8579-4c1c-b6c0-048ee4704415.mov
> feat:add tooltip in create loan product screen

- src/app/products/share-products/share-product-stepper/share-product-accounting-step/share-product-accounting-step.component.ts
- src/app/products/share-products/share-product-stepper/share-product-charges-step/share-product-charges-step.component.ts
- src/app/products/share-products/share-product-stepper/share-product-currency-step/share-product-currency-step.component.html
- src/app/products/share-products/share-product-stepper/share-product-currency-step/share-product-currency-step.component.ts
- src/app/products/share-products/share-product-stepper/share-product-details-step/share-product-details-step.component.html
- src/app/products/share-products/share-product-stepper/share-product-details-step/share-product-details-step.component.ts
- src/app/products/share-products/share-product-stepper/share-product-market-price-step/share-product-market-price-step.component.html
- src/app/products/share-products/share-product-stepper/share-product-market-price-step/share-product-market-price-step.component.ts
- src/app/products/share-products/share-product-stepper/share-product-settings-step/share-product-settings-step.component.html
- src/app/products/share-products/share-product-stepper/share-product-settings-step/share-product-settings-step.component.ts
- src/app/products/share-products/share-product-stepper/share-product-terms-step/share-product-terms-step.component.html
- src/app/products/share-products/share-product-stepper/share-product-terms-step/share-product-terms-step.component.ts
added tooltips in creating share product screens to provide valuable aid in understanding the functionality of the system.
#1670 
https://user-images.githubusercontent.com/76156941/218171887-b113e130-e922-4679-8a78-03b4e1895da5.mov
> feat:add tooltip in create share product screen

- src/app/clients/client-stepper/client-family-members-step/client-family-member-dialog/client-family-member-dialog.component.html
- src/app/clients/client-stepper/client-family-members-step/client-family-member-dialog/client-family-member-dialog.component.ts
- src/app/clients/clients-view/family-members-tab/add-family-member/add-family-member.component.html
- src/app/clients/clients-view/family-members-tab/add-family-member/add-family-member.component.ts
- src/app/clients/clients-view/family-members-tab/edit-family-member/edit-family-member.component.html
- src/app/clients/clients-view/family-members-tab/edit-family-member/edit-family-member.component.ts
now we can select the dob of a family member before 2000 year also
#1682 
https://user-images.githubusercontent.com/76156941/218531968-0e405384-0d1f-4fcb-a39f-5ad1a397c1a2.mov
> fix: family details date of birth issue

- src/app/loans/loans-view/loan-account-actions/disburse/disburse.component.ts
- src/app/products/charges/edit-charge/edit-charge.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-accounting-step/loan-product-accounting-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-accounting-step/loan-product-accounting-step.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-preview-step/loan-product-preview-step.component.html
- src/app/products/loan-products/view-loan-product/general-tab/general-tab.component.html
- src/app/products/loan-products/view-loan-product/general-tab/general-tab.component.scss
Recently we have introduced new GL mapping parameters at the loan product level for Charge-off and Goodwill credit. 
We need to be able to define GLs for these newly introduced parameters from Front end.
> New GL mapping parameters at the loan product level for Charge-off

- src/app/products/floating-rates/create-floating-rate/create-floating-rate.component.html
- src/app/products/floating-rates/create-floating-rate/create-floating-rate.component.ts
- src/app/products/floating-rates/edit-floating-rate/edit-floating-rate.component.html
- src/app/products/floating-rates/edit-floating-rate/edit-floating-rate.component.ts
added tooltips in floating rate screen to provide valuable aid in understanding the functionality of the system.
#1673 
https://user-images.githubusercontent.com/76156941/218777345-756f0649-479f-4131-9c69-0c4859e34764.mov
> feat:add tooltip in floating rate screen

- src/app/clients/clients-view/family-members-tab/add-family-member/add-family-member.component.html
- src/app/clients/clients-view/family-members-tab/add-family-member/add-family-member.component.ts
now we cannot give negative input in age field
#1686
https://user-images.githubusercontent.com/76156941/220039856-629d4ae5-d64f-411a-855a-24f2b380176b.mov
> fix: negative value is allowed in age field while adding family member of client

- src/app/clients/client-stepper/client-family-members-step/client-family-member-dialog/client-family-member-dialog.component.html
- src/app/clients/client-stepper/client-family-members-step/client-family-member-dialog/client-family-member-dialog.component.ts
Now the family member can be added. The issue was that PR: #1568 contained the changes which affected the functionality.
#1666 
https://user-images.githubusercontent.com/76156941/220079601-f2f0b973-7c41-4f99-b4f7-dd5330623db8.mov
> fix: feature not working: add family member in create client

- src/app/loans/loans-view/transactions/export-transactions/export-transactions.component.ts
- src/app/organization/bulk-import/view-bulk-import/view-bulk-import.component.ts
Type error fix to export entity client bulk import template
> Fix to export entity client bulk import template

- Dockerfile
- angular.json
Use of Node 19 in the Dockerfile 
> Support for Node 19

- src/app/loans/loans-account-stepper/loans-account-preview-step/loans-account-preview-step.component.html
- src/app/users/create-user/create-user.component.ts
There was an error If we were sent the staffId value empty
> Fix for adding an user without staff

- src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.html
- src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.ts
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
Added tooltips in creating loan account screen to provide valuable aid in understanding the functionality of the system.
#1675 
https://user-images.githubusercontent.com/76156941/224125341-a5bcd5b9-ccaf-452f-8fc0-197aab9d82bc.mov
> feat:add tooltip in create loan account screens

- src/app/products/loan-products/create-loan-product/create-loan-product.component.scss
- src/app/products/loan-products/edit-loan-product/edit-loan-product.component.scss
- src/app/products/loan-products/loan-product-stepper/loan-product-accounting-step/loan-product-accounting-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-accounting-step/loan-product-accounting-step.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-preview-step/loan-product-preview-step.component.html
We have introduced new GL mapping parameters at the loan product level for Goodwill credit Interest, Fees and Penalties income
> Loan product accounting mappings to Income from Goodwill Credit

- src/app/core/utils/datatables.ts
- src/app/loans/common-resolvers/loan-datatable.resolver.ts
- src/app/loans/loans-view/loan-documents-tab/loan-documents-tab.component.ts
- src/app/loans/loans-view/notes-tab/notes-tab.component.ts
- src/app/savings/saving-account-actions/saving-account-actions.component.ts
- src/app/savings/savings-account-view/notes-tab/notes-tab.component.ts
- src/app/savings/savings-account-view/savings-documents-tab/savings-documents-tab.component.ts
- src/app/savings/savings-account-view/transactions-tab/transactions-tab.component.ts
- src/app/shared/tabs/entity-datatable-tab/datatable-single-row/datatable-single-row.component.html
- src/app/shared/tabs/entity-datatable-tab/datatable-single-row/datatable-single-row.component.scss
- src/app/shared/tabs/entity-datatable-tab/datatable-single-row/datatable-single-row.component.ts
Fix for account id parameter in account tabs because we were getting http code 404 in some of them like datatables, notes or documents tabs
> Fix for account id parameter in account tabs

- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-interest-rate-chart-step/recurring-deposit-product-interest-rate-chart-step.component.html
- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-interest-rate-chart-step/recurring-deposit-product-interest-rate-chart-step.component.ts
now we are able to create recurring deposit product by adding atleast one slab and using information from JIRA how to fill it
#1705 
https://user-images.githubusercontent.com/76156941/226093075-6271287d-5ff0-4eda-8f31-db724ad5d115.mov
> fix: not able to create recurring deposit product

- src/app/keyboards-shortcut-config.ts
now the keyboard shortcuts are working in mac os google chrome too
#1716 
https://user-images.githubusercontent.com/76156941/226636999-15fe853e-0539-40f9-b534-49b9cf2691b9.mov
> refactor: keyboard shortcuts on google chrome browser on mac os

- src/app/loans/create-loans-account/create-loans-account.component.html
- src/app/loans/create-loans-account/create-loans-account.component.ts
- src/app/loans/edit-loans-account/edit-loans-account.component.html
- src/app/loans/edit-loans-account/edit-loans-account.component.ts
- src/app/loans/loans-account-stepper/loans-account-schedule-step/loans-account-schedule-step.component.html
- src/app/loans/loans-account-stepper/loans-account-schedule-step/loans-account-schedule-step.component.ts
- src/app/loans/loans-view/charges-tab/charges-tab.component.html
- src/app/loans/loans-view/general-tab/general-tab.component.html
- src/app/loans/loans-view/general-tab/general-tab.component.ts
- src/app/loans/loans-view/loans-view.component.html
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.html
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.ts
- src/app/products/charges/edit-charge/edit-charge.component.ts
- src/app/savings/savings-account-view/charges-tab/charges-tab.component.html
- src/app/savings/savings-account-view/savings-account-view.component.html
- src/app/savings/savings-account-view/savings-account-view.component.ts
Use of account currency display symbol
- Sample in EUR
- Sample in USD
> Use of account currency display symbol

- src/app/loans/loans-view/loan-account-actions/approve-loan/approve-loan.component.ts
- src/app/loans/loans-view/loan-account-actions/disburse/disburse.component.ts
- src/app/products/charges/edit-charge/edit-charge.component.ts
Fix charge payment method edition
> Fix charge payment method edition

- src/app/clients/edit-client/edit-client.component.html
- src/app/clients/edit-client/edit-client.component.ts
- src/app/loans/loans-view/loan-account-actions/approve-loan/approve-loan.component.ts
- src/app/loans/loans-view/loan-account-actions/disburse/disburse.component.ts
- src/app/products/charges/edit-charge/edit-charge.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-preview-step/loan-product-preview-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts
- src/app/products/loan-products/view-loan-product/general-tab/general-tab.component.html
Fix loan product allow partial period interest calculation `allowPartialPeriodInterestCalculation`
> Fix loan product allow partial period interest calculation

- src/app/loans/loans-view/general-tab/general-tab.component.html
- src/app/system/manage-jobs/cob-workflow/loan-locked/loan-locked.component.html
- src/app/tasks/checker-inbox-and-tasks-tabs/loan-disbursal/loan-disbursal.component.html
- src/app/tasks/checker-inbox-and-tasks-tabs/reschedule-loan/reschedule-loan.component.html
Display the Loan Purpose name value due typo error
> Display the Loan Purpose name value

- src/app/loans/loans-view/charges-tab/charges-tab.component.html
- src/app/loans/loans-view/charges-tab/charges-tab.component.ts
- src/app/system/manage-jobs/scheduler-jobs/manage-scheduler-jobs.component.html
- src/app/system/manage-jobs/scheduler-jobs/manage-scheduler-jobs.component.ts
Fix to sort loan charges by due date
> Fix to sort loan charges by due date

- src/app/shared/tabs/entity-datatable-tab/datatable-multi-row/datatable-multi-row.component.html
- src/app/shared/tabs/entity-datatable-tab/datatable-multi-row/datatable-multi-row.component.ts
Fix datatable multirow refresh
> Fix datatable multirow refresh

- .github/CONTRIBUTING.md
- README.md
I came across several typos while viewing the README.md and Contributing.md file of this repository.
Typos in README.md :
confiurations (Should be configurations)
mifos (Should be Mifos)
Typos in CONTRIBUTING.md :
commited (Should be committed)
commiting (Should be committing)
I have rectified the above typos and have made changes in only those files
Since this isn't related to a bug fix or a feature request, I didn't make an issue regarding it.
> docs: fixed typos in README.md and CONTRIBUTING.md file

- angular.json
- package.json
- src/app/clients/clients.component.html
- src/app/clients/clients.component.ts
- src/app/clients/clients.service.ts
- src/app/core/http/api-prefix.interceptor.ts
- src/app/settings/settings.service.ts
> FINERACT-1724: Server-side pagination support for clients screen

- src/app/clients/clients.component.ts
> FINERACT-1724: Clients screen resetting the paginator after search

- src/app/clients/clients.component.ts
> FINERACT-1724: Avoiding double loading of client list for Clients screen

- src/app/clients/clients.component.ts
- src/app/clients/clients.service.ts
- src/app/core/utils/datatables.ts
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
- src/app/loans/loans.service.ts
- src/app/savings/savings-account-stepper/savings-account-terms-step/savings-account-terms-step.component.ts
- src/app/shared/tabs/entity-datatable-tab/datatable-multi-row/datatable-multi-row.component.html
- src/app/shared/tabs/entity-datatable-tab/datatable-multi-row/datatable-multi-row.component.ts
Fix datatable multirow multiple selection and deletion
https://github.com/openMF/web-app/assets/44206706/d8c473b2-4842-4255-b7c1-6a9e35dd474d
> Fix datatable multirow multiple selection and deletion

- src/app/shared/tabs/entity-datatable-tab/datatable-multi-row/datatable-multi-row.component.html
- src/app/shared/tabs/entity-datatable-tab/datatable-multi-row/datatable-multi-row.component.ts
Fix datatable multirow delete rows 
https://github.com/openMF/web-app/assets/44206706/ac66947f-d4f3-409f-8ee8-eabd683101ce
> Fix datatable multirow delete rows

- src/app/groups/groups-view/group-actions/manage-group-members/manage-group-members.component.html
- src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.ts
- src/app/reports/run-report/table-and-sms/table-and-sms.component.html
- src/app/reports/run-report/table-and-sms/table-and-sms.component.scss
- src/app/reports/run-report/table-and-sms/table-and-sms.component.ts
Message in run report when It is being exported to S3
> Message in run report when It is being exported to S3

- src/app/loans/loans-account-stepper/loans-account-preview-step/loans-account-preview-step.component.html
- src/app/loans/loans-view/charges-tab/charges-tab.component.html
- src/app/loans/loans-view/charges-tab/charges-tab.component.ts
- src/app/products/loan-products/create-loan-product/create-loan-product.component.ts
- src/app/products/loan-products/edit-loan-product/edit-loan-product.component.ts
- src/app/products/loan-products/loan-products.ts
Fix Loan products to use global settings in default
> Fix Loan products to use global settings in default

- src/app/loans/loans-view/charges-tab/charges-tab.component.html
- src/app/loans/loans-view/loans-view.component.ts
- src/app/reports/run-report/pentaho/pentaho.component.ts
- src/app/reports/run-report/run-report.component.html
- src/app/reports/run-report/run-report.component.ts
- src/app/reports/run-report/table-and-sms/table-and-sms.component.ts
- src/app/tasks/checker-inbox-and-tasks-tabs/loan-approval/loan-approval.component.html
Fix to display due or submitted date in Loan charges based on the Global configuration  `charge-accrual-date` 
> Fix to display due or submitted date in Loan charges

- src/app/loans/loans-view/transactions-tab/transactions-tab.component.scss
- src/app/loans/loans-view/transactions-tab/transactions-tab.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-preview-step/loan-product-preview-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-terms-step/loan-product-terms-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-terms-step/loan-product-terms-step.component.ts
- src/app/products/loan-products/view-loan-product/general-tab/general-tab.component.html
- src/app/savings/common-resolvers/transaction-datatable.resolver.ts
- src/app/savings/common-resolvers/transaction-datatables.resolver.ts
- src/app/savings/savings-account-view/transactions/view-transaction/datatable-transaction-tab/datatable-transaction-tab.component.ts
- src/app/savings/savings-account-view/transactions/view-transaction/view-transaction.component.ts
- src/app/savings/savings.service.ts
- src/assets/styles/_colours.scss
We are able to configure repayment start date at product level with the options: `submission date` or loan `disbursal date` in order to have repayment schedule generation as per requirement 
> Loan Product Repayment Start date configuration

- src/app/clients/clients-view/clients-view.component.html
Corrected the permissions for the 'Create' and 'View Standing Instructions' actions to align with their respective functionalities.
> Correct Permissions for Create and View Standing Instructions Actions

- src/app/core/http/api-prefix.interceptor.ts
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-accounting-step/fixed-deposit-product-accounting-step.component.html
- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-accounting-step/recurring-deposit-product-accounting-step.component.html
- src/app/products/saving-products/saving-product-stepper/saving-product-accounting-step/saving-product-accounting-step.component.html
- src/app/products/share-products/share-product-stepper/share-product-accounting-step/share-product-accounting-step.component.html
- src/app/settings/settings.service.ts
- src/app/shared/footer/footer.component.html
- src/app/shared/footer/footer.component.ts
- src/app/system/version.service.ts
- src/assets/env.template.js
- src/environments/environment.prod.ts
- src/environments/environment.ts
Now with the info endpoint we are able to know the details of Fineract build version, tags, etc. So I can report issues properly if needed
> Display Fineract version and build

- src/app/system/manage-jobs/scheduler-jobs/custom-parameters-popover/custom-parameters-popover.component.html
- src/app/system/manage-jobs/scheduler-jobs/custom-parameters-popover/custom-parameters-popover.component.scss
- src/app/system/manage-jobs/scheduler-jobs/custom-parameters-popover/custom-parameters-popover.component.spec.ts
- src/app/system/manage-jobs/scheduler-jobs/custom-parameters-popover/custom-parameters-popover.component.ts
- src/app/system/manage-jobs/scheduler-jobs/custom-parameters-popover/custom-parameters-table/custom-parameters-table.component.html
- src/app/system/manage-jobs/scheduler-jobs/custom-parameters-popover/custom-parameters-table/custom-parameters-table.component.scss
- src/app/system/manage-jobs/scheduler-jobs/custom-parameters-popover/custom-parameters-table/custom-parameters-table.component.spec.ts
- src/app/system/manage-jobs/scheduler-jobs/custom-parameters-popover/custom-parameters-table/custom-parameters-table.component.ts
- src/app/system/manage-jobs/scheduler-jobs/manage-scheduler-jobs.component.html
- src/app/system/manage-jobs/scheduler-jobs/manage-scheduler-jobs.component.ts
- src/app/system/system.module.ts
- src/app/system/system.service.ts
The scheduled Jobs could be ran with optional parameters, then in the UI we have added a button to open a new dialog to input the Parameter name and value
https://github.com/openMF/web-app/assets/44206706/9171e27f-c659-4900-90eb-46cfdea7090b
> Input to run Jobs with Parameters

- package.json
- src/app/clients/clients-view/family-members-tab/family-members-tab.component.html
- src/app/loans/loans-view/external-asset-owner-tab/external-asset-transfer/external-asset-transfer.component.html
- src/app/loans/loans-view/external-asset-owner-tab/external-asset-transfer/external-asset-transfer.component.ts
- src/app/organization/investors/investors.component.html
- src/app/organization/investors/investors.component.scss
- src/app/organization/investors/investors.component.ts
- src/app/reports/run-report/run-report.component.ts
- src/app/shared/footer/footer.component.html
- src/app/shared/footer/footer.component.scss
- src/app/shared/footer/footer.component.ts
Search External Asset Owner
Filtering by Text over the external Ids
> Search External Asset Owner

- src/app/clients/clients-view/clients-view.component.html
- src/app/core/shell/toolbar/toolbar.component.html
- src/app/core/shell/toolbar/toolbar.component.ts
- src/app/products/loan-products/create-loan-product/create-loan-product.component.html
- src/app/products/loan-products/create-loan-product/create-loan-product.component.ts
- src/app/products/loan-products/edit-loan-product/edit-loan-product.component.html
- src/app/products/loan-products/edit-loan-product/edit-loan-product.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-payment-strategy-step/loan-product-payment-strategy-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-payment-strategy-step/loan-product-payment-strategy-step.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-payment-strategy-step/payment-allocation-model.ts
- src/app/shared/tabs/entity-datatable-tab/datatable-multi-row/datatable-multi-row.component.html
- src/app/shared/tabs/entity-datatable-tab/datatable-multi-row/datatable-multi-row.component.ts
- src/app/users/users-routing.module.ts
- src/app/users/users.service.ts
- src/assets/styles/_colours.scss
Fix Loan product Payment Allocation
> Fix Loan product Payment Allocation

- src/app/loans/glim-account/create-glim-account/create-glim-account.component.ts
- src/app/loans/glim-account/glim-account.component.html
- src/app/loans/glim-account/glim-account.component.scss
- src/app/products/loan-products/loan-product-stepper/loan-product-payment-strategy-step/loan-product-payment-strategy-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-payment-strategy-step/loan-product-payment-strategy-step.component.ts
Minor fixes in Loan product Advanced Payment Allocation
> Minor fixes in Loan product Advanced Payment Allocation

- Dockerfile
- package.json
- src/app/system/manage-jobs/scheduler-jobs/custom-parameters-popover/custom-parameters-popover.component.html
- src/app/system/manage-jobs/scheduler-jobs/custom-parameters-popover/custom-parameters-popover.component.ts
- src/app/system/manage-jobs/scheduler-jobs/custom-parameters-popover/custom-parameters-table/custom-parameters-table.component.ts
- version.js
> Fix Job Parameters

- .github/workflows/build.yml
- Dockerfile
- docker-compose.yml
- src/app/core/shell/shell.component.ts
- src/app/organization/investors/investors.component.html
- src/app/organization/investors/investors.component.scss
- src/app/organization/investors/investors.component.ts
Investor Search data with actions when the Transfer is pending we can Cancel
> Investor Search data with actions

- .github/workflows/build.yml
- Dockerfile
> Rollback to use Node 19

- src/app/account-transfers/create-standing-instructions/create-standing-instructions.component.html
- src/app/account-transfers/edit-standing-instructions/edit-standing-instructions.component.html
- src/app/account-transfers/list-standing-instructions/list-standing-instructions.component.html
- src/app/account-transfers/list-transactions/list-transactions.component.html
- src/app/account-transfers/make-account-transfers/make-account-transfers.component.html
- src/app/account-transfers/view-account-transfer/view-account-transfer.component.html
- src/app/account-transfers/view-standing-instructions/view-standing-instructions.component.html
- src/app/app.module.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-stepper/fixed-deposit-account-currency-step/fixed-deposit-account-currency-step.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-currency-step/recurring-deposits-account-currency-step.component.html
- src/app/products/recurring-deposit-products/create-recurring-deposit-product/create-recurring-deposit-product.component.html
- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-currency-step/recurring-deposit-product-currency-step.component.html
- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-details-step/recurring-deposit-product-details-step.component.html
- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-interest-rate-chart-step/recurring-deposit-product-interest-rate-chart-step.component.html
- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-settings-step/recurring-deposit-product-settings-step.component.html
- src/app/products/recurring-deposit-products/recurring-deposit-products.component.html
- src/assets/translations/en-US.json
- src/assets/translations/fr-FR.json
Script for Account transfer module for managing internationalization.
> Account transfer module translation

- src/app/accounting/accounting-rules/accounting-rules.component.html
- src/app/accounting/accounting-rules/create-rule/create-rule.component.html
- src/app/accounting/accounting-rules/edit-rule/edit-rule.component.html
- src/app/accounting/accounting-rules/view-rule/view-rule.component.html
- src/app/accounting/accounting.component.html
- src/app/accounting/chart-of-accounts/chart-of-accounts.component.html
- src/app/accounting/chart-of-accounts/create-gl-account/create-gl-account.component.html
- src/app/accounting/chart-of-accounts/edit-gl-account/edit-gl-account.component.html
- src/app/accounting/chart-of-accounts/view-gl-account/view-gl-account.component.html
- src/app/accounting/closing-entries/closing-entries.component.html
- src/app/accounting/closing-entries/create-closure/create-closure.component.html
- src/app/accounting/closing-entries/edit-closure/edit-closure.component.html
- src/app/accounting/closing-entries/view-closure/view-closure.component.html
- src/app/accounting/create-journal-entry/create-journal-entry.component.html
- src/app/accounting/financial-activity-mappings/create-financial-activity-mapping/create-financial-activity-mapping.component.html
- src/app/accounting/financial-activity-mappings/edit-financial-activity-mapping/edit-financial-activity-mapping.component.html
- src/app/accounting/financial-activity-mappings/financial-activity-mappings.component.html
- src/app/accounting/financial-activity-mappings/view-financial-activity-mapping/view-financial-activity-mapping.component.html
- src/app/accounting/frequent-postings/frequent-postings.component.html
- src/app/accounting/migrate-opening-balances/migrate-opening-balances.component.html
- src/app/accounting/periodic-accruals/periodic-accruals.component.html
- src/app/accounting/provisioning-entries/create-provisioning-entry/create-provisioning-entry.component.html
- src/app/accounting/provisioning-entries/provisioning-entries.component.html
- src/app/accounting/provisioning-entries/view-provisioning-entry/view-provisioning-entry.component.html
- src/app/accounting/provisioning-entries/view-provisioning-journal-entries/view-provisioning-journal-entries.component.html
- src/app/accounting/revert-transaction/revert-transaction.component.html
- src/app/accounting/search-journal-entry/search-journal-entry.component.html
> Accounting translate module

- src/app/centers/centers-view/center-actions/activate-center/activate-center.component.html
- src/app/centers/centers-view/center-actions/attach-center-meeting/attach-center-meeting.component.html
- src/app/centers/centers-view/center-actions/center-assign-staff/center-assign-staff.component.html
- src/app/centers/centers-view/center-actions/center-attendance/center-attendance.component.html
- src/app/centers/centers-view/center-actions/close-center/close-center.component.html
- src/app/centers/centers-view/center-actions/edit-center-meeting-schedule/edit-center-meeting-schedule.component.html
- src/app/centers/centers-view/center-actions/edit-center-meeting/edit-center-meeting.component.html
- src/app/centers/centers-view/center-actions/manage-groups/manage-groups.component.html
- src/app/centers/centers-view/center-actions/staff-assignment-history/staff-assignment-history.component.html
- src/app/centers/centers-view/centers-view.component.html
- src/app/centers/centers-view/general-tab/general-tab.component.html
- src/app/centers/centers-view/notes-tab/notes-tab.component.html
- src/app/centers/centers.component.html
- src/app/centers/create-center/create-center.component.html
- src/app/centers/edit-center/edit-center.component.html
> feat: Center Translate Module

- src/app/configuration-wizard/completion-dialog/completion-dialog.component.html
- src/app/configuration-wizard/configuration-wizard.component.html
- src/app/configuration-wizard/continue-setup-dialog/continue-setup-dialog.component.html
- src/app/configuration-wizard/next-step-dialog/next-step-dialog.component.html
> feat:Configuration-wizard Translate Module

- src/app/home/dashboard/amount-collected-pie/amount-collected-pie.component.html
- src/app/home/dashboard/amount-disbursed-pie/amount-disbursed-pie.component.html
- src/app/home/dashboard/client-trends-bar/client-trends-bar.component.html
- src/app/home/dashboard/dashboard.component.html
- src/app/home/home.component.html
> feat:Home Translate Module

- src/app/core/shell/breadcrumb/breadcrumb.component.html
- src/app/core/shell/sidenav/sidenav.component.html
- src/app/core/shell/toolbar/toolbar.component.html
> feat:Core Translate Module

- src/app/login/login.component.html
- src/app/login/reset-password/reset-password.component.html
- src/app/login/two-factor-authentication/two-factor-authentication.component.html
> feat: Login Translate Module

- src/app/navigation/center-navigation/center-navigation.component.html
- src/app/navigation/client-navigation/client-navigation.component.html
- src/app/navigation/group-navigation/group-navigation.component.html
- src/app/navigation/loan-account-table/loan-account-table.component.html
- src/app/navigation/member-groups/member-groups.component.html
- src/app/navigation/navigation.component.html
- src/app/navigation/office-navigation/office-navigation.component.html
- src/app/navigation/savings-account-table/savings-account-table.component.html
- src/app/navigation/share-account-table/share-account-table.component.html
- src/app/navigation/staff-navigation/staff-navigation.component.html
> feat:Navigation Translate Module

- src/app/notifications/notifications-page/notifications-page.component.html
> feat:Notification Translate Module

- src/app/profile/profile.component.html
> feat:Profile Translate Module

- src/app/shares/create-shares-account/create-shares-account.component.html
- src/app/shares/edit-shares-account/edit-shares-account.component.html
- src/app/shares/shares-account-actions/activate-shares-account/activate-shares-account.component.html
- src/app/shares/shares-account-actions/apply-shares/apply-shares.component.html
- src/app/shares/shares-account-actions/approve-shares-account/approve-shares-account.component.html
- src/app/shares/shares-account-actions/approve-shares/approve-share-dialog/approve-share-dialog.component.html
- src/app/shares/shares-account-actions/approve-shares/approve-shares.component.html
- src/app/shares/shares-account-actions/close-shares-account/close-shares-account.component.html
- src/app/shares/shares-account-actions/redeem-shares/redeem-shares.component.html
- src/app/shares/shares-account-actions/reject-shares-account/reject-shares-account.component.html
- src/app/shares/shares-account-actions/reject-shares/reject-share-dialog/reject-share-dialog.component.html
- src/app/shares/shares-account-actions/reject-shares/reject-shares.component.html
- src/app/shares/shares-account-actions/undo-approval-shares-account/undo-approval-shares-account.component.html
- src/app/shares/shares-account-stepper/shares-account-charges-step/shares-account-charges-step.component.html
- src/app/shares/shares-account-stepper/shares-account-details-step/shares-account-details-step.component.html
- src/app/shares/shares-account-stepper/shares-account-preview-step/shares-account-preview-step.component.html
- src/app/shares/shares-account-stepper/shares-account-terms-step/shares-account-terms-step.component.html
- src/app/shares/shares-account-view/charges-tab/charges-tab.component.html
- src/app/shares/shares-account-view/dividends-tab/dividends-tab.component.html
- src/app/shares/shares-account-view/shares-account-view.component.html
- src/app/shares/shares-account-view/transactions-tab/transactions-tab.component.html
> feat:Shares Translate Module

- src/app/self-service/app-configuration/app-configuration.component.html
- src/app/self-service/task-management/task-management.component.html
- src/app/self-service/users/create-user/create-user.component.html
- src/app/self-service/users/edit-user/edit-user.component.html
- src/app/self-service/users/users.component.html
- src/app/self-service/users/view-user/view-user.component.html
> feat:Self-service Translate Module

- src/app/users/create-user/create-user.component.html
- src/app/users/edit-user/edit-user.component.html
- src/app/users/users.component.html
- src/app/users/view-user/view-user.component.html
> feat:Users Translate Module

- src/app/centers/centers.service.ts
- src/app/clients/clients-view/address-tab/address-tab.component.ts
- src/app/clients/clients-view/client-actions/add-client-collateral/add-client-collateral.component.ts
- src/app/configuration-wizard/popover/popover.component.ts
- src/app/core/shell/toolbar/toolbar.component.ts
- src/app/loans/create-loans-account/create-loans-account.component.ts
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
- src/app/organization/investors/investors.component.ts
- src/app/organization/organization.component.ts
- src/app/products/loan-products/create-loan-product/create-loan-product.component.html
- src/app/products/loan-products/create-loan-product/create-loan-product.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-payment-strategy-step/payment-allocation-model.ts
The loan term parameter in loan products and loan accounts is the default-calculated field based on the 
number of repayments and repaid every value entered by the user.
for example:
if number of repayment = 4 and repaid every = 15 days (down-payment is disabled)
the Loan Term is set as 60 days (4*15).
https://github.com/openMF/web-app/assets/44206706/295d5c4b-60a2-4c85-9e07-401f52d00627
> Loan Account Term calculation

- src/app/core/authentication/authentication.service.ts
- src/app/home/home.component.ts
- src/app/home/home.module.ts
- src/app/home/warning-dialog/warning-dialog.component.html
- src/app/home/warning-dialog/warning-dialog.component.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
Implemented a configurable legal warning popup that appears after the login screen. The content of the popup message is configurable and customizable, allowing for easy updates and modifications of the information displayed.
> Added configurable warning message

- src/app/products/saving-products/saving-product-stepper/saving-product-accounting-step/saving-product-accounting-step.component.html
- src/app/products/saving-products/saving-product-stepper/saving-product-accounting-step/saving-product-accounting-step.component.ts
Combined all possible accountingMappingOptions in order to fix PaymentFundSource.
#1888
> combined and ordered accountingMappingOptions

- package.json
- src/app/pipes/pipes.module.ts
- src/app/pipes/pretty-print.pipe.ts
- src/app/savings/savings-account-view/transactions/view-transaction/view-transaction.component.scss
- src/app/shared/tabs/entity-datatable-tab/datatable-single-row/datatable-single-row.component.html
- src/app/shared/tabs/entity-datatable-tab/datatable-single-row/datatable-single-row.component.ts
datatable-single-row.component.html now shows json obejcts correctly.
#1895
> datatable-single-row now supports json object

- package-lock.json
- src/app/core/utils/datatables.ts
- src/app/pipes/pretty-print.pipe.ts
- src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.ts
- src/app/shared/tabs/entity-datatable-tab/datatable-single-row/datatable-single-row.component.ts
- src/environments/.env.ts
> Fix in Loan Product edition

- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-preview-step/recurring-deposits-account-preview-step.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.ts
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
Fix issues on missed translations for product and account views
> Fix issues on missed translations

- src/app/deposits/recurring-deposits/common-resolvers/recurring-deposit-account-actions.resolver.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/deposit-recurring-deposits-account/deposit-recurring-deposits-account.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/deposit-recurring-deposits-account/deposit-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/recurring-deposits-account-actions.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits.service.ts
- src/theme/_content.scss
Recurring Deposit account deposit and withdrawal transactions
- Deposit Transaction
- Withdrawal Transaction
> Recurring Deposit account deposit and withdrawal transactions

- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts
Loan product delinquency bucket should not be mandatory
> Loan product delinquency bucket should not be mandatory

- src/app/products/share-products/dividends-share-product/dividends.resolver.ts
- src/app/products/share-products/view-dividend/view-dividend-data.resolver.ts
- src/app/products/share-products/view-dividend/view-dividend.component.ts
there should be id, instead of productId therefore it was not working
#1933 
https://github.com/openMF/web-app/assets/76156941/c5b9db7d-3437-4e9d-b19e-e2e676818598
> fix: now dividend is working

- src/app/savings/savings-account-view/transactions-tab/transactions-tab.component.html
- src/app/savings/savings-account-view/transactions-tab/transactions-tab.component.scss
- src/app/savings/savings-account-view/transactions-tab/transactions-tab.component.ts
Savings account transactions with check to hide accrual transactions
- Savings account transactions 
- Savings account transactions hiding accruals
> Savings account transactions with check to hide accrual transactions

- src/app/shares/shares-account-stepper/shares-account-charges-step/shares-account-charges-step.component.ts
now able to add charge in shares account
#1934 
https://github.com/openMF/web-app/assets/76156941/e5423dfc-4bd2-4bd3-9468-df941574483a
> fix: now able to add charge in shares account

- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts
In Loan Product - the drop down value for Loan Schedule Processing Type changes during the Edit screen
https://github.com/openMF/web-app/assets/44206706/6d78bdc9-9cc0-4319-a748-42de7fe4f8b6
> Fix Loan product edition Loan Schedule Processing Type issue

- src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.ts
- src/app/loans/models/loan-transaction-type.model.ts
Allow Chargeback option for Downpayment Transaction type
- Downpayment transaction
- Downpayment transaction relations
> Allow Chargeback option for Downpayment Transaction type

- src/app/account-transfers/edit-standing-instructions/edit-standing-instructions.component.html
- src/app/account-transfers/edit-standing-instructions/edit-standing-instructions.component.ts
- src/app/account-transfers/list-standing-instructions/list-standing-instructions.component.html
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
Submit button on edit standing instructions was not active until Validity to date is selected
#1981 
https://github.com/openMF/web-app/assets/76156941/511c318b-d376-45d3-b558-43944d5e9cdc
> fix: now submit doesn't require to select validDate

- src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts
- src/app/products/loan-products/models/loan-product.model.ts
> Remove `disableScheduleExtensionForDownPayment`

- src/app/loans/loans-view/loan-delinquency-tags-tab/loan-delinquency-tags-tab.component.ts
On UI Resume button is visible after pause period ended, but creating new pause period was not possible because the button was not visible
> Allow new Loan delinquency pause

- angular.json
- src/app/account-transfers/edit-standing-instructions/edit-standing-instructions.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts
Fix edit Loan product with delinquency bucket unassigned
> Fix edit Loan product with delinquency bucket unassigned

- src/app/clients/clients-routing.module.ts
- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/general-tab/general-tab.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/charges-tab/charges-tab.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/general-tab/general-tab.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component.ts
- src/app/notifications/notifications-page/notifications-page.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts
- src/app/search/search-page/search-page.component.ts
- src/app/search/search.model.ts
- src/app/shared/notifications-tray/notifications-tray.component.ts
Fix search entities view for savings and deposits accounts using the sub entity type to route the view for savings or fixed deposit or recurring deposit
> Fix search entities view for savings and deposits accounts

- src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html
- src/app/products/loan-products/edit-loan-product/edit-loan-product.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-payment-strategy-step/advance-payment-allocation-tab/advance-payment-allocation-tab.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-payment-strategy-step/advance-payment-allocation-tab/advance-payment-allocation-tab.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-payment-strategy-step/loan-product-payment-strategy-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-payment-strategy-step/loan-product-payment-strategy-step.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-payment-strategy-step/payment-allocation-model.ts
- src/app/search/search-page/search-page.component.ts
Fix: Loan product edition with Advanced Allocation for Payment and Credit transactions
> Fix: Loan product edition with Adv Allocation for Payment and Credit

- src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html
Fix Loan product with overdue charges
> Fix Loan product with overdue charges

- src/app/clients/clients-view/family-members-tab/family-members-tab.component.html
- src/app/clients/clients-view/family-members-tab/family-members-tab.component.ts
Display family member data where the data is filled and avoid empty spaces
> Display family member data

- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
Fix: Allow Loan account creation that uses Floating rate
> Fix: Allow Loan account creation that uses Floating rate

- src/app/shared/notifications-tray/notifications-tray.component.html
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
Enhance notification template for improved user experience
Fix: #2005
Improved notification display to address the issue of a blank box when clicking the icon. Now, a centered icon with "No notification" is shown for a clearer user experience. This change enhances UI clarity and user-friendliness.
#2005 
> feat: Enhance notification template for better UX

- src/app/organization/adhoc-query/adhoc-query.component.html
- src/app/organization/manage-funds/manage-funds.component.html
- src/app/organization/manage-funds/manage-funds.component.scss
- src/app/organization/payment-types/payment-types.component.html
- src/app/organization/payment-types/payment-types.component.scss
- src/app/organization/sms-campaigns/sms-campaigns.component.html
- src/app/reports/xbrl/xbrl.component.html
- src/app/system/audit-trails/audit-trails.component.html
- src/app/system/manage-external-events/manage-external-events.component.html
- src/app/system/manage-reports/manage-reports.component.html
- src/assets/styles/_overflow.scss
Fix: Overflow in Navbar by Making Table Scrollable (To avoid overflow) in these components XBRL, Manage Funds, Payment Type, SMS Campaigns, Adhoc Query, Manage External Events, Audit Trails and Manage Report
#2009 
[Screencast from 2024-03-02 02-21-58.webm](https://github.com/openMF/web-app/assets/106796672/4247825b-89b2-4dd6-a47f-d4f6e6bc05d8)
>  Fix: Overflow in Navbar by Making Table Scrollable (To avoid overflow)

- src/app/core/shell/sidenav/sidenav.component.scss
- src/app/home/dashboard/amount-collected-pie/amount-collected-pie.component.scss
- src/app/home/dashboard/amount-disbursed-pie/amount-disbursed-pie.component.scss
- src/app/home/dashboard/client-trends-bar/client-trends-bar.component.html
- src/app/home/dashboard/client-trends-bar/client-trends-bar.component.scss
- src/app/home/dashboard/dashboard.component.html
- src/app/home/dashboard/dashboard.component.scss
Enhance the dashboard to make it responsive and correct the logo at Sidenav
Enhancing the dashboard's responsiveness and correcting the logo placement in the side navigation. 
- Implemented responsive design principles to ensure optimal user experience across various devices.
- Corrected the logo placement in the side navigation for a more cohesive and visually pleasing layout.
#2018
[Screencast from 2024-03-06 23-27-09.webm](https://github.com/openMF/web-app/assets/106796672/a24ff956-83da-40fa-9864-07948527f5e7)
> Enhance the dashboard to make it responsive and correct the logo at sidenav

- src/app/keyboards-shortcut-config.ts
Changed shortcuts keymap to make it work for all kind of OS and without having browser defaults issues 
#2012 
https://github.com/openMF/web-app/assets/103763618/3ce4dc4a-edf5-4915-9b4c-40833427dc12
> Fix : Updated shortcut keymap to make it work on all browsers and OS .

- src/app/account-transfers/view-account-transfer/view-account-transfer.component.html
- src/app/account-transfers/view-account-transfer/view-account-transfer.component.ts
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/transactions-tab/transactions-tab.component.html
- src/app/keyboards-shortcut-config.ts
Fix to mark with strike the reversed FD Account transactions
> Fix to mark with strike the reversed FD Account transactions

- src/app/loans/loans-view/loan-account-actions/loan-reaging/loan-reaging.component.html
- src/app/loans/loans-view/loan-account-actions/loan-reaging/loan-reaging.component.ts
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
> Add frequency number for Reaging component

- src/app/shares/shares-account-stepper/shares-account-terms-step/shares-account-terms-step.component.html
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
Fix: Updated input label on Share account creation
#2051 
> Fix: Share Account Creation Page missing labels

- src/assets/mock/user.mock.json
Small change to remove PII from mock file
> Remove PII from mock file

- src/app/system/external-services/notification/notification.component.html
- src/app/system/external-services/notification/notification.component.ts
Masking the server configuration for external services
> Masking the server configuration for external services

- src/app/accounting/chart-of-accounts/chart-of-accounts.component.html
- src/app/accounting/chart-of-accounts/chart-of-accounts.component.ts
- src/app/organization/offices/offices.component.html
- src/app/organization/offices/offices.component.ts
- src/app/shared/common-logic/tree-control.service.ts
Enhanced the Collapse All or Expand All button by implementing both in the same button and also fixed the
translation for both.
- Before Change
[Screencast from 2024-04-23 00-41-29.webm](https://github.com/openMF/web-app/assets/106796672/9055fd97-ecb0-432b-8cf7-996ffa9c4ea8)
- After Change
[Screencast from 2024-04-23 00-38-27.webm](https://github.com/openMF/web-app/assets/106796672/9698f9b6-e913-4c4a-b1ba-6e6faef6f288)
> Enhanced the Collapse all or Expand All button and fix the translation

- Dockerfile
> WA-2086:add new arg  PUPPETEER_SKIP_DOWNLOAD_ARG

- src/app/loans/loans-account-stepper/loans-account-preview-step/loans-account-preview-step.component.html
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
- src/app/loans/loans-view/account-details/account-details.component.html
- src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html
- src/app/products/loan-products/view-loan-product/shared/view-advance-paymeny-allocation/view-advance-paymeny-allocation.component.html
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
Fix missed labels in the loan and loan product views
> Fix: missed labels in loan and loan product

- src/app/loans/loans-account-stepper/loans-account-schedule-step/loans-account-schedule-step.component.ts
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
- src/app/loans/loans-view/account-details/account-details.component.html
- src/app/loans/loans-view/general-tab/general-tab.component.html
Update Loan account view to use Delinquency installment
> Update Loan account view to use Delinquency installment

- .gitignore
- src/app/accounting/migrate-opening-balances/migrate-opening-balances.component.html
- src/app/accounting/migrate-opening-balances/migrate-opening-balances.component.scss
- src/app/accounting/migrate-opening-balances/migrate-opening-balances.component.ts
- src/app/accounting/migrate-opening-balances/only-one-of-the-fields-is-required.validator.ts
- src/app/products/charges/create-charge/create-charge.component.html
- src/app/products/charges/edit-charge/edit-charge.component.html
- src/app/products/charges/view-charge/view-charge.component.html
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
Accounting Migrate Opening Balances view was having some issues mainly to enable the submit button
- Before
- After
> fix: Accounting Migrate Opening Balances view

- src/app/loans/loans-view/transactions-tab/transactions-tab.component.html
- src/app/loans/loans-view/transactions-tab/transactions-tab.component.scss
- src/app/savings/savings-account-view/transactions-tab/transactions-tab.component.html
- src/app/savings/savings-account-view/transactions-tab/transactions-tab.component.scss
Account transactions table row mouse pointer
> fix: Account transactions table row mouse pointer

- src/app/loans/loans-view/transactions-tab/transactions-tab.component.html
- src/app/loans/loans-view/transactions-tab/transactions-tab.component.scss
- src/app/savings/savings-account-view/general-tab/general-tab.component.html
- src/app/savings/savings-account-view/transactions-tab/transactions-tab.component.html
- src/app/savings/savings-account-view/transactions-tab/transactions-tab.component.scss
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
fix: Account transaction tab select row, to be clic on any part of the row and see the transaction details
> fix: Account transaction tab select row

- src/app/deposits/fixed-deposits/fixed-deposit-account-view/transactions-tab/transactions-tab.component.html
- src/app/deposits/fixed-deposits/fixed-deposit-account-view/transactions-tab/transactions-tab.component.scss
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/transactions-tab.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/transactions-tab.component.scss
- src/app/loans/edit-loans-account/edit-loans-account.component.ts
- src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.ts
- src/app/loans/loans-view/transactions-tab/transactions-tab.component.html
- src/app/savings/savings-account-view/transactions-tab/transactions-tab.component.html
Account Transaction tab homologation for the different kind of products
> Account Transaction tab homologation

- src/app/deposits/fixed-deposits/common-resolvers/fixed-deposit-account-actions.resolver.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-account-actions.component.html
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-account-actions.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-cash-transaction/fixed-deposits-cash-transaction.component.html
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-cash-transaction/fixed-deposits-cash-transaction.component.scss
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-cash-transaction/fixed-deposits-cash-transaction.component.spec.ts
- src/app/deposits/fixed-deposits/fixed-deposits-account-actions/fixed-deposits-cash-transaction/fixed-deposits-cash-transaction.component.ts
- src/app/deposits/fixed-deposits/fixed-deposits.module.ts
- src/app/deposits/fixed-deposits/fixed-deposits.service.ts
- src/app/deposits/recurring-deposits/edit-recurring-deposit-account/edit-recurring-deposit-account.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/deposit-recurring-deposits-account/deposit-recurring-deposits-account.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-actions/deposit-recurring-deposits-account/deposit-recurring-deposits-account.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-charges-step/recurring-deposits-account-charges-step.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-interest-rate-chart-step/recurring-deposits-account-interest-rate-chart-step.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-preview-step/recurring-deposits-account-preview-step.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-settings-step/recurring-deposits-account-settings-step.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-settings-step/recurring-deposits-account-settings-step.component.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-stepper/recurring-deposits-account-terms-step/recurring-deposits-account-terms-step.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/general-tab/general-tab.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/interest-rate-chart-tab/interest-rate-chart-tab.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-buttons.config.ts
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/edit-transaction/edit-transaction.component.html
- src/app/deposits/recurring-deposits/recurring-deposits-account-view/transactions-tab/edit-transaction/edit-transaction.component.ts
Recurring Deposit account view updated to fix some issues 
> fix: Recurring Deposit accounts issues

- src/app/system/manage-surveys/create-survey/create-survey.component.html
- src/app/system/manage-surveys/edit-survey/edit-survey.component.html
- src/app/system/manage-surveys/manage-surveys.component.html
- src/app/system/manage-surveys/view-survey/view-survey.component.html
translation of survery file inside system module
> translation of survery file inside system module

- src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.ts
The Chargeback transaction has been enhanced to support more Loan transactions than Repayment, now we have Interest Payment Waiver transaction
- Loan Repayment
- Loan Interest Payment Waiver
> Support Chargeback for different Loan transactions

- src/app/directives/format-amount.directive.ts
- src/app/products/loan-products/edit-loan-product/edit-loan-product.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts
- src/app/system/manage-jobs/cob-workflow/loan-locked/loan-locked.component.ts
- src/app/system/manage-jobs/scheduler-jobs/error-log-popover/error-log-popover.component.ts
- src/app/system/manage-jobs/workflow-jobs/workflow-jobs.component.ts
- src/app/system/manage-reports/create-report/create-report.component.ts
- src/app/system/roles-and-permissions/view-role/view-role.component.ts
In the Loan Product edition we were not able to identify If the Loan Product is using or not the Global configurations 
> fix: Loan Product using global configurations for repayments

- src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.html
- src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.ts
- src/app/loans/loans-account-stepper/loans-account-preview-step/loans-account-preview-step.component.html
- src/app/loans/loans-account-stepper/loans-account-preview-step/loans-account-preview-step.component.ts
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
- src/app/loans/loans-routing.module.ts
- src/app/loans/loans-view/account-details/account-details.component.html
- src/app/loans/loans-view/loan-account-actions/approve-loan/approve-loan.component.html
- src/app/loans/loans-view/loan-account-actions/approve-loan/approve-loan.component.ts
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.scss
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.ts
This is needed to decide dynamically the loan is downpayment loan or not under the same product constraints
https://github.com/openMF/web-app/assets/154766431/b0ae3924-1bb1-4b86-928e-96b45eb9c17a
> Enable or Disable DownPayment at Loan account level

- src/app/home/dashboard/client-trends-bar/client-trends-bar.component.scss
- src/app/home/dashboard/dashboard.component.html
- src/app/home/dashboard/dashboard.component.scss
- src/app/home/dashboard/dashboard.component.ts
add Search Activity to our dashboard and fix html & css of the dashboard
> add Search Activity to our dashboard and fix html & css of the dashboard

- package-lock.json
- package.json
- src/app/loans/loans-view/original-schedule-tab/original-schedule-tab.component.html
- src/app/loans/loans-view/original-schedule-tab/original-schedule-tab.component.ts
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.html
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.scss
- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.ts
- src/app/loans/models/loan-account.model.ts
- src/app/products/fixed-deposit-products/fixed-deposit-product-stepper/fixed-deposit-product-settings-step/fixed-deposit-product-settings-step.component.ts
- src/app/products/recurring-deposit-products/recurring-deposit-product-stepper/recurring-deposit-product-settings-step/recurring-deposit-product-settings-step.component.ts
- src/assets/styles/_colours.scss
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
- src/environments/.env.ts
There is a new option in the Loan Repayment Schedule tab to export the current repayment schedule as PDF
> Loan Repayment Schedule with Export to PDF option

- src/app/home/dashboard/amount-collected-pie/amount-collected-pie.component.ts
- src/app/home/dashboard/amount-disbursed-pie/amount-disbursed-pie.component.ts
- src/app/home/dashboard/client-trends-bar/client-trends-bar.component.ts
> add some style to dashboard

- src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html
- src/app/products/loan-products/create-loan-product/create-loan-product.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-interest-refund-step/loan-product-interest-refund-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-interest-refund-step/loan-product-interest-refund-step.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-payment-strategy-step/loan-product-payment-strategy-step.component.html
- src/assets/styles/_colours.scss
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
Fix missed labels for Loan Product
> fix: Loan Product missed labels

- src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.scss
- src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-interest-refund-step/loan-product-interest-refund-step.component.ts
fix: Loan Repayment Schedule colours to present the Installment paid
> fix: Loan Repayment Schedule colours

- src/app/centers/centers-view/center-actions/center-attendance/center-attendance.component.ts
- src/app/centers/centers-view/notes-tab/notes-tab.component.html
- src/app/centers/centers-view/notes-tab/notes-tab.component.ts
- src/app/clients/client-stepper/client-address-step/client-address-step.component.ts
- src/app/clients/clients-view/address-tab/address-tab.component.ts
- src/app/clients/clients-view/family-members-tab/add-family-member/add-family-member.component.html
- src/app/clients/clients-view/family-members-tab/edit-family-member/edit-family-member.component.html
- src/app/clients/clients-view/identities-tab/identities-tab.component.ts
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
add missed translation to client module
> add missed translation to client module

- src/app/accounting/accounting.component.html
- src/app/accounting/accounting.component.ts
add some style to accounting to enhance our user experience
https://github.com/user-attachments/assets/14a60946-06ad-41b1-a9a5-8b0d2a4f2a1e
> add some style to accounting to enhance our user experience

- src/app/accounting/accounting.component.html
- src/app/organization/bulk-import/bulk-import.component.html
- src/app/organization/bulk-import/bulk-import.component.ts
- src/app/organization/organization.component.html
- src/app/organization/organization.component.ts
- src/app/products/products.component.html
- src/app/products/products.component.ts
- src/app/system/system.component.html
- src/app/system/system.component.ts
add style to the remaining components in our website
> add style to the remaining components in our website

- src/app/products/manage-delinquency-buckets/manage-delinquency-buckets.component.html
- src/app/products/manage-delinquency-buckets/manage-delinquency-buckets.component.ts
- src/app/products/manage-tax-configurations/manage-tax-configurations.component.html
- src/app/products/manage-tax-configurations/manage-tax-configurations.component.ts
- src/app/system/external-services/external-services.component.html
- src/app/system/external-services/external-services.component.ts
add style to remaining components
> add style to remaining components

- src/app/clients/clients.component.html
- src/app/clients/clients.component.scss
- src/app/organization/investors/investors.component.html
- src/app/organization/investors/investors.component.scss
- src/app/reports/run-report/table-and-sms/table-and-sms.component.html
- src/app/reports/run-report/table-and-sms/table-and-sms.component.scss
- src/app/savings/savings-account-view/general-tab/general-tab.component.html
- src/app/savings/savings-account-view/general-tab/general-tab.component.scss
add new progress bar to remaining components in our app
> add new progress bar to remaining components in our app

- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html
- src/app/reports/run-report/run-report.component.ts
- src/app/reports/run-report/table-and-sms/table-and-sms.component.scss
fix: Run report view horizontal scroll issue due overflow 
> fix: Run report view horizontal scroll issue

- src/app/clients/clients-view/clients-view.component.html
- src/app/clients/clients-view/clients-view.component.scss
- src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.ts
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
> Client view with details

- src/app/clients/clients-view/clients-view.component.html
Client view broken when the client has not client type
> fix: Client view broken when the client has not client type

- src/app/clients/client-stepper/client-general-step/client-general-step.component.html
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
> fix: Loan COB step missed labels

- .github/workflows/create-docker-hub-image.yml
> Do not try to create docker image for PRs

- .github/workflows/build.yml
> Update github pages deploy version

- src/app/products/loan-products/loan-product-stepper/loan-product-accounting-step/loan-product-accounting-step.component.ts
- src/app/savings/savings-account-view/transactions/view-transaction/savings-transaction-general-tab/savings-transaction-general-tab.component.html
in the Loan Product edition we were not able to edit the charge-Off advanced accounting mappings
https://github.com/user-attachments/assets/f8510ee0-b12d-42b8-a921-df804491ede6
> fix: Loan Product charge-off advanced accounting mappings

- src/app/system/manage-jobs/scheduler-jobs/manage-scheduler-jobs.component.html
- src/app/system/manage-jobs/scheduler-jobs/manage-scheduler-jobs.component.ts
- src/app/system/manage-jobs/scheduler-jobs/run-selected-jobs-popover/run-selected-jobs-popover.component.html
- src/app/system/manage-jobs/scheduler-jobs/run-selected-jobs-popover/run-selected-jobs-popover.component.scss
- src/app/system/manage-jobs/scheduler-jobs/run-selected-jobs-popover/run-selected-jobs-popover.component.spec.ts
- src/app/system/manage-jobs/scheduler-jobs/run-selected-jobs-popover/run-selected-jobs-popover.component.ts
- src/app/system/manage-jobs/scheduler-jobs/run-selected-jobs-popover/run-selected-jobs-table/run-selected-jobs-table.component.html
- src/app/system/manage-jobs/scheduler-jobs/run-selected-jobs-popover/run-selected-jobs-table/run-selected-jobs-table.component.scss
- src/app/system/manage-jobs/scheduler-jobs/run-selected-jobs-popover/run-selected-jobs-table/run-selected-jobs-table.component.spec.ts
- src/app/system/manage-jobs/scheduler-jobs/run-selected-jobs-popover/run-selected-jobs-table/run-selected-jobs-table.component.ts
- src/app/system/system.module.ts
- src/app/system/system.service.ts
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
- src/environments/.env.ts
Confirmation window when running batch jobs in Mifos WebApp
> Confirmation window when running batch jobs in Mifos WebApp

- .github/CODE_OF_CONDUCT.md
- .github/COMMIT_MESSAGE.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/user-story-template.md
- .github/PULL_REQUEST_TEMPLATE.md
- .prettierignore
- README.md
- docs/analytics.md
- docs/backend-proxy.md
- docs/coding-guides/angular.md
- docs/coding-guides/e2e-tests.md
- docs/coding-guides/html.md
- docs/coding-guides/sass.md
- docs/coding-guides/typescript.md
- docs/coding-guides/unit-tests.md
- docs/corporate-proxy.md
- docs/i18n.md
- docs/routing.md
- docs/updating.md
Stop ignoring .md files in prettier and fix existing issues.
> build: Use prettier for markdown

- .github/ISSUE_TEMPLATE/DMP_2024_DESIGN.yml
- .github/workflows/build.yml
- .github/workflows/create-docker-hub-image.yml
- .github/workflows/stale.yml
- .prettierignore
Stop ignoring .yml files in prettier and fix existing issues.
> build: Use prettier for yaml

- .gitignore
- .husky/pre-commit
- package-lock.json
- package.json
- src/app/loans/loans-view/loan-term-variations-tab/loan-term-variations-tab.component.scss
- src/app/system/manage-jobs/scheduler-jobs/run-selected-jobs-popover/run-selected-jobs-popover.component.scss
- src/app/system/manage-jobs/scheduler-jobs/run-selected-jobs-popover/run-selected-jobs-table/run-selected-jobs-table.component.scss
- src/app/system/manage-jobs/scheduler-jobs/run-selected-jobs-popover/run-selected-jobs-table/run-selected-jobs-table.component.ts
Introducing `lint-staged` with `husky` to lint files before they are committed. This will help maintain the code standards in the project.
HTML files should be included after current issues with `htmlhint` are fixed.
> build: Use lint-staged

- src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html
- src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-accounting-step/loan-product-accounting-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-accounting-step/loan-product-accounting-step.component.ts
- src/app/products/loan-products/models/loan-product.model.ts
- src/app/shared/models/general.model.ts
- src/app/system/manage-jobs/scheduler-jobs/run-selected-jobs-popover/run-selected-jobs-table/run-selected-jobs-table.component.ts
> Advanced accounting - Charge-off reason mapping

- src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html
- src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-accounting-step/loan-product-accounting-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-accounting-step/loan-product-accounting-step.component.ts
- src/app/shared/models/general.model.ts
> Advanced accounting - Charge-off reason mapping fix

- src/assets/env.template.js
> Fix boolean values in env.template.js

- src/app/products/loan-products/loan-product-stepper/loan-product-accounting-step/loan-product-accounting-step.component.ts
> Charge off reason accounting 3

- .github/workflows/build.yml
- Dockerfile
- README.md
> Upgrade NodeJs and Nginx

- README.md
Add Github Action Build Status and update link to Slack channel
Add Github Action Build Status and update link to Slack channel
> Add Github Action Build Status

- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html
- src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts
- src/app/loans/loans-view/loans-view.component.ts
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
As of now the UI was allowing to Charge-off a loan, but there is no “Undo Charge-off” option available.
https://github.com/user-attachments/assets/ac2734f6-56cf-4514-a636-628903ff6a28
> Undo Loan Charge-off transaction

- README.md
add apache fineract link in readme file
Jira Task: https://mifosforge.jira.com/browse/WEB-7
- [yes ] If you have multiple commits please combine them into one commit by squashing them.
- [yes ] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.
> docs(README.md) add apache fineract link in readme file

- src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.ts
- src/app/products/loan-products/edit-loan-product/edit-loan-product.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-accounting-step/loan-product-accounting-step.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-accounting-step/loan-product-accounting-step.component.ts
- src/assets/env.js
Allow only one charge-off reason at time in the Loan product advance GL accounting mappings
https://github.com/user-attachments/assets/7ff32bbe-041e-4b90-b8dd-8e3c9ae0f453
> fix: Loan product charge-off reasons accounting mappings

- src/app/system/manage-jobs/scheduler-jobs/run-selected-jobs-popover/run-selected-jobs-table/run-selected-jobs-table.component.ts
fix: Batch jobs dialog confirmation delete button, the window is freezed
> fix: Batch jobs dialog confirmation delete button

- src/app/system/manage-jobs/scheduler-jobs/manage-scheduler-jobs.component.html
> Allow run Batch inactive jobs

- src/app/products/loan-products/loan-product-stepper/loan-product-accounting-step/loan-product-accounting-step.component.ts
> Reset advanced accounting rules if checkbox is unchecked on loan product

- src/assets/translations/es-MX.json
> Fix translation

- README.md
Added Jira board and Jira Web app project link in readme file.
I forked the web app repo to my profile and then made changes.
https://mifosforge.jira.com/browse/WEB-6
> Added Jira board and Jira Web app project link readme

- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
- src/app/loans/loans-view/account-details/account-details.component.html
- src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html
- src/app/products/loan-products/loan-product-stepper/loan-product-terms-step/loan-product-terms-step.component.html
> interestChargedFromDisbursementDate flag only for cumulative loans

- src/app/accounting/chart-of-accounts/gl-account-tree.service.ts
Make Chart of Accounts Javascript run without error when no accounts exist
Fixes: WEB-10
> fix: Javascript "is undefined" error

- src/app/login/login-form/login-form.component.html
- src/app/login/login-form/login-form.component.ts
Included a button to toggle the visibility of the password input field, improving user experience by allowing users to see the password they are typing. Added a loading indicator to show progress during form submission.
> feat: button to password toggle, appropriate error message

- src/app/self-service/task-management/task-management.component.ts
Add type annotations to improve the type safety of the task-management.component.ts file.
> fix: add type annotations

- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
Avoid Javascript error, make Delinquency section work, clean up
Fixes: WEB-20
> fix: correct issues with client loan creation

- src/main.scss
Updated scroll-bar for to fix app-sidebar component. Also fixes scroll-bar for every component. Makes UI looky bettter
> Updated scroll-bar to take less space in every component

- src/app/shared/theme-picker/theme-storage.service.ts
- src/main.scss
- src/theme/deeppurple-amber.scss
- src/theme/indigo-pink.scss
- src/theme/mifosx-theme.scss
- src/theme/pictonblue-yellowgreen.scss
- src/theme/pink-bluegrey.scss
- src/theme/purple-green.scss
Fixes Issue WEB-29
1. Fixed theme selector component
2.  Added corresponding theme scss files for themes.
and few more themes.
> fix: Working of theme selector

- .github/workflows/create-docker-hub-image.yml
> Publish hashed docker image tags as well

- .github/workflows/create-docker-hub-image.yml
> Fix for docker publication

- .github/workflows/create-docker-hub-image.yml
> Fix multi arch image building

- .github/workflows/create-docker-hub-image.yml
> Branch fix for docker publication workflow

- src/app/shared/accounting/gl-account-selector/gl-account-selector.component.html
- src/app/shared/accounting/gl-account-selector/gl-account-selector.component.ts
Fixed placeholder text in different language to chosen language
[WEB-54](https://mifosforge.jira.com/browse/WEB-54?atlOrigin=eyJpIjoiNzllZDkxNjYwNGU3NDJlZGJmM2M0NGNmMzk4ZDQzNTYiLCJwIjoiaiJ9)
[WEB-54]: https://mifosforge.jira.com/browse/WEB-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Web-54 Wrong Text In Placeholder for Every Language

- src/app/home/home.component.html
Refactored the Home Component to improve readability, maintainability, and efficiency while preserving existing functionality
- Fixed layout inconsistencies and improved responsiveness
- Applied Prettier formatting to adhere to coding standards
- No functional changes were introduced
Fixes: [Web-43](https://mifosforge.jira.com/browse/WEB-43)
> refactor:home component

- src/app/accounting/chart-of-accounts/view-gl-account/view-gl-account.component.ts
[WEB-55](https://mifosforge.jira.com/browse/WEB-55?atlOrigin=eyJpIjoiNjRjMWZiYWY1ODc0NGI3ZmIyODA2MmQxOTBmMDJkODEiLCJwIjoiaiJ9)
[fix1.webm](https://github.com/user-attachments/assets/fff88bae-8e34-477e-b1d8-9b7768aa0bb3)
[WEB-55]: https://mifosforge.jira.com/browse/WEB-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Web 55 back button navigates incorrectly after creating editing a gl account

- src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.html
- src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.ts
- src/app/organization/currencies/manage-currencies/manage-currencies.component.html
- src/app/organization/currencies/manage-currencies/manage-currencies.component.ts
Fixes placeholders in German even if the language is different.  
All the search components (i.e. 3) affected by this issue are solved.
#2321 
[WEB-60](https://mifosforge.jira.com/browse/WEB-60?atlOrigin=eyJpIjoiZTBmZTFiNjA1ZTAwNGQyMWExODk5ZDA3OTlmZmIxMzEiLCJwIjoiaiJ9)  
[WEB-60]: https://mifosforge.jira.com/browse/WEB-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: WEB-60 Globally Fix Search Placeholder In Different Language

- package-lock.json
- package.json
- src/app/groups/groups-view/groups-view.component.html
- src/app/loans/loans-account-stepper/loans-account-preview-step/loans-account-preview-step.component.html
- src/app/loans/loans-account-stepper/loans-account-preview-step/loans-account-preview-step.component.ts
- src/app/savings/gsim-account/create-gsim-account/create-gsim-account.component.html
- src/app/savings/savings-account-stepper/savings-account-preview-step/savings-account-preview-step.component.html
- src/app/savings/savings-account-stepper/savings-account-preview-step/savings-account-preview-step.component.ts
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-CL.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
This shows a list of participating members in GLIM resp. GSIM preview step.
It also changes "GLIM Loan" to "GLIM" in a menu item.
Fixes: WEB-64
> fix: Show members in GLIM and GSIM preview

- README.md
- src/app/system/system.component.html
- src/app/system/system.component.scss
- src/app/system/system.component.ts
- src/environments/.env.ts
Completed all the necessary changes required for disabling manage surveys navigation meanwhile the survey functionality starts working.
> fix: WEB-79 Grey out "Manage Surveys"

- src/app/shared/change-password-dialog/change-password-dialog.component.html
- src/app/shared/change-password-dialog/change-password-dialog.component.ts
We are not able to change the user password in the Web UI. All attempts at satisfying the password requirements are failing. See screenshot.
https://github.com/user-attachments/assets/e3a66057-8175-40fa-8030-e0e8c815966f
> fix: Change password dialog password validation issue

- src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts
Set a Default value in the Loan Product  `daysInYearCustomStrategy` property 
> fix: Loan Product default value for Days In Year Custom strategy

- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-CL.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
slag variable translation added
before : 
after :
> slag variable translation added

- src/app/loans/loans-view/loan-collateral-tab/loan-collateral-tab.component.html
- src/app/loans/loans-view/loan-collateral-tab/loan-collateral-tab.component.ts
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-CL.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
- Fixed values of individual collaterals not showing up
- Added a new sentence for all the languages 
[WEB-81](https://mifosforge.jira.com/browse/WEB-81?atlOrigin=eyJpIjoiNjMzODg1YTU2NzQ4NGM2MzllZmVlODkyZjI0NTUxZGIiLCJwIjoiaiJ9)
[WEB-67](https://mifosforge.jira.com/browse/WEB-67?atlOrigin=eyJpIjoiMTA0ODM3YzI2NWEzNDg5Njg4Y2I5NzA3ZmQwNzAzMTIiLCJwIjoiaiJ9)
[WEB-81]: https://mifosforge.jira.com/browse/WEB-81?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-67]: https://mifosforge.jira.com/browse/WEB-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WEB-67 fix: Values of individual collaterals & new sentences added

- src/assets/translations/en-US.json
password require label correted.
#web-105
before : 
after :
> password require label corrected

- src/app/loans/glim-account/create-glim-account/create-glim-account.component.html
- src/app/loans/glim-account/create-glim-account/create-glim-account.component.ts
- src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.html
- src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.ts
- src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
- src/app/loans/loans-account-stepper/loans-active-client-members/loans-active-client-members.component.html
- src/app/loans/loans-account-stepper/loans-active-client-members/loans-active-client-members.component.scss
- src/app/loans/loans-account-stepper/loans-active-client-members/loans-active-client-members.component.spec.ts
- src/app/loans/loans-account-stepper/loans-active-client-members/loans-active-client-members.component.ts
- src/app/loans/loans.module.ts
- src/app/savings/gsim-account/create-gsim-account/create-gsim-account.component.html
- src/app/savings/gsim-account/create-gsim-account/create-gsim-account.component.ts
- src/app/savings/savings-account-stepper/savings-account-charges-step/savings-account-charges-step.component.html
- src/app/savings/savings-account-stepper/savings-account-charges-step/savings-account-charges-step.component.ts
- src/app/savings/savings-account-stepper/savings-active-client-members/savings-active-client-members.component.html
- src/app/savings/savings-account-stepper/savings-active-client-members/savings-active-client-members.component.scss
- src/app/savings/savings-account-stepper/savings-active-client-members/savings-active-client-members.component.spec.ts
- src/app/savings/savings-account-stepper/savings-active-client-members/savings-active-client-members.component.ts
- src/app/savings/savings.module.ts
- src/assets/translations/en-US.json
Same change for GSIM Application
> fix: glim, gsim account create

- package-lock.json
- src/app/web-app.component.ts
- src/environments/.env.ts
The tab text also gets displayed with the correct mapping of its page titles now.
> Tab text translation issue solved

- .github/CONTRIBUTING.md
- .github/workflows/build.yml
- .github/workflows/create-docker-hub-image.yml
- .github/workflows/stale.yml
- .github/workflows/test.yml
Reverts openMF/web-app#2396
Did not follow project governance.
> Revert "WEB-132: Replace `master` with `main` in GitHub Actions workflow"

- package.json
package.json updates: Version becomes 1.0.0, bug tracker becomes Jira
FIXES: WEB-127
> build: Update version and bug tracker in package.json

- src/app/web-app.component.ts
Fixes tab titles both in English and other languages.
From what I can tell #2376 worked only for 3 
pages - those 3 with translations in labels.titles.*. On 
the other hand, it did not even work for English on most pages.
In addition to that, #2376 removed code regarding 
top 100 user activities, without any explanation.
The PR here is meant to fix all of that and hopefully doesn't affect #2385.
FIXES: WEB-130, WEB-40
> fix: Fixes tab titles, reinstates top 100 activities code

- src/app/loans/loans-view/account-details/account-details.component.html
- src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html
- src/app/products/loan-products/create-loan-product/create-loan-product.component.ts
- src/app/products/loan-products/loan-product-stepper/loan-product-capitalized-income-step/loan-product-capitalized-income-step.component.ts
We are supporting the Capitalized Income functionality in Loan Product that uses Advanced Payment Allocation
> fix: Loan Product Capitalized Income values

- src/theme/deeppurple-amber.scss
- src/theme/indigo-pink.scss
- src/theme/mifosx-theme.scss
- src/theme/pictonblue-yellowgreen.scss
- src/theme/pink-bluegrey.scss
- src/theme/purple-green.scss
> Revert "fix: Correct themes for Angular 15"

- src/app/loans/loans-view/account-details/account-details.component.html
- src/assets/translations/cs-CS.json
- src/assets/translations/de-DE.json
- src/assets/translations/en-US.json
- src/assets/translations/es-CL.json
- src/assets/translations/es-MX.json
- src/assets/translations/fr-FR.json
- src/assets/translations/it-IT.json
- src/assets/translations/ko-KO.json
- src/assets/translations/lt-LT.json
- src/assets/translations/lv-LV.json
- src/assets/translations/ne-NE.json
- src/assets/translations/pt-PT.json
- src/assets/translations/sw-SW.json
> Loan account details - income capitalization type

- src/app/products/charges/create-charge/create-charge.component.html
- src/app/products/charges/create-charge/create-charge.component.ts
- src/app/products/charges/edit-charge/edit-charge.component.html
- src/app/products/charges/edit-charge/edit-charge.component.ts
- src/app/products/charges/view-charge/view-charge.component.html
- src/app/shared/validators/min-max-values.validator.ts
Charge management minimum and maximum cap values validation to have a Minimum value equal or lower than Maximum Cap value
> fix: Charge management minimum and maximum cap values validation

- src/app/shared/material.module.ts
Correct all references to
- MatLegacyProgressBarModule
in the angular-update branch and verify the result works by testing.
[WEB-152](https://mifosforge.jira.com/browse/WEB-152?atlOrigin=eyJpIjoiMDgyZTM0MjkxMGVlNGEwYzhjOGM4MGQ5NWY5OWZiZDYiLCJwIjoiaiJ9)
[WEB-152]: https://mifosforge.jira.com/browse/WEB-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WEB-152 Replace references to MatLegacyProgressBarModule in Angular 15 project

- src/app/core/shell/toolbar/toolbar.component.html
- src/app/core/shell/toolbar/toolbar.component.scss
- src/app/products/loan-products/loan-product-stepper/loan-product-payment-strategy-step/loan-product-payment-strategy-step.component.ts
- src/app/shared/material.module.ts
- src/app/system/manage-jobs/manage-jobs.component.ts
Correct all references to
- MatLegacyTabsModule
- MatLegacyTabGroup
- MatLegacyTabChangeEvent
in the angular-update branch and verify the result works by testing.
[WEB-155](https://mifosforge.jira.com/browse/WEB-155?atlOrigin=eyJpIjoiZWIxM2NlNzk0MWU1NGZmM2FiYzMyMGVmMjY4YzU3YTgiLCJwIjoiaiJ9)
[WEB-155]: https://mifosforge.jira.com/browse/WEB-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WEB-155 Replace references to MatLegacyTabsModule,MatLegacyTabGroup and MatLegacyTabChangeEvent in Angular 15 project

- src/app/clients/client-stepper/client-general-step/client-general-step.component.html
- src/app/shared/material.module.ts
- src/app/system/manage-hooks/edit-hook/edit-hook.component.ts
- src/app/web-app.component.ts
Correct all references to
- MatLegacySnackBar
- MatLegacySnackBarModule
in the angular-update branch and verify the result works by testing.
[WEB-159](https://mifosforge.jira.com/browse/WEB-159?atlOrigin=eyJpIjoiNzhjMGRmNmFhNTA1NDBiNjlkYmFhNWI1MWY3OWNjMzkiLCJwIjoiaiJ9)
[WEB-159]: https://mifosforge.jira.com/browse/WEB-159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WEB-159 Replace references to MatLegacySnackBar and MatLegacySnackBarModule in Angular 15 project

- src/app/account-transfers/list-transactions/list-transactions.component.html
- src/app/centers/centers-view/center-actions/attach-center-meeting/attach-center-meeting.component.html
This is (hopefully) the remaining bit necessary to correct all HTML issues covered by the ticket.
FIXES: WEB-150
> fix: broken HTML due to unterminated quotes

- src/app/accounting/accounting-rules/edit-rule/edit-rule.component.html
- src/app/centers/centers-view/centers-view.component.html
3 broken *ngIf expressions that got outside of their elements in 2 files.
FIXES: WEB-150
> fix: broken ngIf continuation

- CONTRIBUTING.md
The CONTRIBUTING.md file has been updated to clarify that we use the dev branch for development. In addition to that, I have slightly shortened and restructured the text.
FIXES: WEB-165
> docs: Improve contributing guidelines

- src/app/loans/loans-account-stepper/loans-account-schedule-step/loans-account-schedule-step.component.ts
- src/app/products/charges/create-charge/create-charge.component.html
- src/app/products/charges/create-charge/create-charge.component.ts
- src/app/products/charges/edit-charge/edit-charge.component.html
- src/app/products/charges/edit-charge/edit-charge.component.ts
- src/app/shared/validators/min-number-value.validator.ts
The `Charge` with `percentage` calculation when there are min and max gap values were not being validated 
> Charges using percentage with min and max gap values validations
